### ISSUE TITLE
GifImagePlugin does not Support Setting Duration or Loops

### ISSUE THREAD

**Issue by cancan101** [python-pillow/Pillow#1085]
See: https://github.com/python-pillow/Pillow/blob/42b59046e7daaa80283255cb9f94e1894e56d8ca/PIL/GifImagePlugin.py#L335
where the duration value is not set. Currently that value is read by not settable.

Further, this block is only written when there is a transparency.

Compare that to http://visvis.googlecode.com/hg/vvmovie/images2gif.py , `getGraphicsControlExt`. 

The same applies for the number of times to loop. Currently that value is read by not settable.

**Comment by wiredfool** [comment]
Feel free to send a Pull Request.

**Comment by aclark4life** [comment]
Yep, PR now and enjoy your code in 2.8.0

**Comment by hugovk** [comment]
Fixed via https://github.com/python-pillow/Pillow/pull/1172

**Comment by phoet** [comment]
@cancan101 i tried to use your changes to loop and duration, but it looks like the resulting gif is broken. Loop and duration are set appropriately though.

Have a look at this example: https://github.com/agschwender/pilbox/pull/43/files

**Comment by hugovk** [comment]
ping @radarhere

**Comment by radarhere** [comment]
Yep. I've created a PR to fix the bug. Sorry about that, but thanks to @phoet for reporting!

**Comment by hugovk** [comment]
PR #1269 merged. @phoet, please can you retest with latest master? Thanks!

**Comment by phoet** [comment]
tested it with the PR branch, looks good! i pushed the changes, take a look yourself.

**Comment by phoet** [comment]
@radarhere it looks like you are the GIF pro here :smile_cat: 

i was trying to get an identical copy out of an existing gif, but it looks like i can't copy all the header information. background, extension and version are set automatically. would it make sense to make them accessible either?
i'm asking because it looks like the resulting gif is somewhat truncated and i was wondering if that was due to some missing/wrong headers?

```
# frames info:
{'background': 53, 'extension': ('NETSCAPE2.0', 219), 'version': 'GIF89a', 'transparency': 53, 'duration': 60, 'loop': 0}
{'background': 53, 'extension': ('NETSCAPE2.0', 219), 'version': 'GIF89a', 'transparency': 53, 'duration': 60, 'loop': 0}
{'background': 53, 'extension': ('NETSCAPE2.0', 219), 'version': 'GIF89a', 'transparency': 53, 'duration': 60, 'loop': 0}
[...]
# resulting animated gif info:
{'background': 0, 'extension': ('NETSCAPE2.0', 803), 'version': 'GIF87a', 'transparency': 53, 'duration': 60, 'loop': 0}
```

**Comment by radarhere** [comment]
I'm not sure who the GIF expert is, but I don't think it's me. I was just the expert on the last problem because it was my code that caused it!

Without an example gif, I'm not quite sure what you mean when you say that it's truncated. However, I can see that the background info isn't making the transition. So I've created a PR to fix that.
