### ISSUE TITLE
Why Pillow is not integrated in the standard library and does not come with distributions of Python?

### ISSUE THREAD

**Issue by dossan** [python-pillow/Pillow#1086]
Hi,

This is not exactly a problem, but I was wondering why _Pillow_ is not included automatically in the distributions of the standard library and the interpreter? Is it because it would make the distribution to heavy, or are there or kind of problems?

By the way, why is it called Pillow? I know PIL stands for Python Image Library, but in the case of Pillow, I don't have ideas.

Thanks.

**Comment by homm** [comment]
The short answer: because there is only one actual version of Pillow for now. If it was included in Python library, it would be several actual versions of Pillow at the same time.

**Comment by dossan** [comment]
@homm Ok, thanks for the answer. So it might be included in the futures versions, if Pillow will also be expanded for those versions. That would be nice!

**Comment by hugovk** [comment]
> This is not exactly a problem, but I was wondering why Pillow is not included automatically in the distributions of the standard library and the interpreter? Is it because it would make the distribution to heavy, or are there or kind of problems?

Some Linux distributions (Fedora, Debian/Ubuntu, and ArchLinux) include Pillow already. I've no idea how one would go about getting a package integrated into a Python release. As it stands, pip installing works well, and we have precompiled binaries for common platforms.

> By the way, why is it called Pillow? I know PIL stands for Python Image Library, but in the case of Pillow, I don't have ideas.

Pillow is a fork of PIL. When it was forked, the PIL project was dormant, and Pillow was initially just to package it up so it can be pip installed. It wasn't (and still isn't) clear if the main PIL project would be revived or not. The [last PIL release was in 2009](http://www.pythonware.com/products/pil/) and the [PIL code last updated in 2011](http://hg.effbot.org/pil-2009-raclette/overview). Since the fork, Pillow has fixed lots of bugs, added lots of new features, and added lots of new tests. Python 3 support has been added.

So the Pillow name was to make it clear that it's not quite the same as PIL. Why exactly "Pillow"? You'll have to ask @aclark4life!

**Comment by aclark4life** [comment]
The Pillow project began in 2010 when I was an active Plone developer and found myself annoyed at the proliferation of third party repackagings of PIL which ["fixed" PIL's packaging](https://github.com/python-pillow/Pillow/commit/6ad52162a18229b48c1919959897571acd940101).

Meanwhile the PIL release available on PyPI was "broken" with no foreseeable way to get the author to "fix it". As a "packaging guy", I found this unacceptable so I decided repackage it, as many others had done before (e.g. PILwoTk, dist.plone.org's PIL, dist.repoze.org's PIL, etc.), then upload the results to PyPI under a similar name so that I could simplify the installation of PIL in my Plone deployments and all Plone deployments.

If you start with the letters **P** **I** **L** and try to make a similar word, you probably don't have a lot of choices. Actually, I take that back; I just consulted ``/usr/share/dict/words`` and found plenty :smile:. However I didn't look there then and instead somehow came up with the name "Pillow", perhaps due to its similarity to "Plone" and went with it.

I still like the name but If I had it to do over, I would have chosen "pillow" instead of "Pillow".

**Comment by aclark4life** [comment]
And to address the issue, I think of PIL as a specialty library for a special purpose, and am not sure it belongs in the standard library. Further, I have no idea what the logistics of putting it there would be but I suspect it wouldn't be easy.

**Comment by dossan** [comment]
@aclark4life Thanks for the answer. I was asking why it is not integrated in the standard library, maybe with tkinter, because tkinter does not many support to image manipulation, and a graphics library should have, in opinion. Would it be possible to extend tkinter in order to have more images formats support? I would really like to see it! 

Yes, I think lower case would be better, since now naming packages in that way seems to be the convention. You can still modify for the next releases. It would be nice, and I think it would not have many backward compatibility problems.

Thanks.

**Comment by aclark4life** [comment]
I'm not terribly inclined to rename Pillow to pillow. I think it may be confusing and/or better to live with it as-is. But I'm willing to listen to counter-arguments. Maybe if we ever released a 3.0, that would be a good time to do it.

**Comment by hugovk** [comment]
Perhaps we should release 3.0 after 2.9? See issue https://github.com/python-pillow/Pillow/issues/1087.

**Comment by wiredfool** [comment]
I don't think Pillow is a good fit for the standard library, especially with the pace of releases that we've been doing. It's perfectly reasonable to be a module, especially given that it's become much more reliable to install over the past few years.
