### ISSUE TITLE
Add Homm to Pillow Core Team?

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1149]
Hi @Homm,

@wiredfool has mentioned he likes your contributions, and I've seen you around and appreciate your presence. As such, I'm wondering if you are interested in joining the core team?

**Comment by homm** [comment]
Sorry, I haven't seen the notification because there are so much notifications from Pillow in past few days :)

The question is what will be my responsibilities? I've made the changes required for my project and I try to ask to all related questions. I also have some plans for further improvements, but in truth I don't ready to fix arbitrary bugs and prepare releases.

**Comment by aclark4life** [comment]
Hi @homm: No problem. You would only be responsible for being a "steward of the Pillowship", i.e. "someone that cares about the Pillow project". You don't have to do releases, bug fixes, or anything that you don't want to do. :smile: Just keep doing what you are doing.

**Comment by homm** [comment]
Well, there is no reasons to disagree. Will be glad to join :)

**Comment by aclark4life** [comment]
Great! Sent you an invite. Welcome to the Pillow Team. CC: @wiredfool

**Comment by hugovk** [comment]
Welcome!

**Comment by dmitry-mukhin** [comment]
yay!
