### ISSUE TITLE
Install gifmaker as library

### ISSUE THREAD

**Issue by cancan101** [python-pillow/Pillow#1271]
Right now `gifmaker` is only usable as an executable script.
Otherwise people have to copy and paste: https://github.com/Jimdo/pilbox/commit/f56abc7d5ed7af5c889b841de0c92536ef713f90#diff-a4ab3a3327863e8d763c59ca95bb0152R20

I suggest making the `makedelta` callable once pillow is installed.

**Comment by radarhere** [comment]
Issue #733 is a request for the ability to save multipage images. I'd be keen to implement this as a first step towards that, but as you can see from my [comment](https://github.com/python-pillow/Pillow/issues/733#issuecomment-113745019) over there, I'm not quite sure how to proceed.

In the meantime, I can see that you had the idea of importing ImageSequence, rather than what the gifmaker script currently does, which is to rewrite the whole class. I think that's a good idea for a simple PR. Would you mind if I went ahead and created that change? Or you can if you want.

**Comment by cancan101** [comment]
Sure, go ahead and given that change a shot.

**Comment by radarhere** [comment]
Sweet, thanks. PR #1294

**Comment by aclark4life** [comment]
PR #1294 has been merged, what's next on this one?

**Comment by radarhere** [comment]
Next is my question, [originally asked in #733](https://github.com/python-pillow/Pillow/issues/733#issuecomment-113745019) - if we're adding the ability to save multiframe gifs into the core library, what should happen when you trying to roundtrip a multiframe gif? At the moment, only the first frame is saved. It would make more sense to me that when opening a multiframe gif, by default, it saves again with all the frames, but that would be a change in behaviour.
