### ISSUE TITLE
[docs] script missing (http 500)

### ISSUE THREAD

**Issue by pierriko** [python-pillow/Pillow#1336]
`_static/js/modernizr.min.js` [1] seems missing (HTTP 500)

The docs wont show untill the request times out (60 seconds!).

[1] http://pillow.readthedocs.org/en/latest/handbook/_static/js/modernizr.min.js

**Comment by radarhere** [comment]
Thanks for finding that problem.

It's not actually that the file is missing. It works fine for http://pillow.readthedocs.org/ but not for http://pillow.readthedocs.org/releasenotes/index.html - it's that when the file is referred to in HTML - `<script src="_static/js/modernizr.min.js"></script>` the path is relative rather than absolute - so it doesn't load on subdirectory pages.

However, Pillow does not control this. It's actually the sphinx_rtd_theme in readthedocs. The problem line is located over at https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L78

**Comment by radarhere** [comment]
This has actually already been fixed over at https://github.com/snide/sphinx_rtd_theme/pull/195, and will be released according to their schedule.
