### ISSUE TITLE
Container-based infrastructure on TravisCI

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#1371]
Assuming I'm not missing something, any reason why we're not using the container-based infrastructure on Travis?

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

**Comment by hugovk** [comment]
It's because we're using sudo, in .travis.yml and depends/*.

> **Using sudo isn't possible (right now)**

> Our new container stack uses Docker under the hood. This has a lot of benefits like fast boot times and better utilization of available machine resources. But it also comes with restrictions imposed by security.

> At this point, it's not possible to use any command requiring sudo in your builds.

> If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build, installing them into a non-root directory.

http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

I've had a bit of a play a while back in this <a href="https://github.com/hugovk/Pillow/tree/container">branch</a> but it's far from complete. 

I asked Travis to <a href="https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=APT+whitelist+is%3Aissue+author%3Ahugovk+is%3Aclosed+">whitelist some packages</a> which weren't already, and they've done so. More may be needed.

See http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-do-I-install-APT-sources-and-packages%3F

We also need non-sudo builds for depends/*.
