### ISSUE TITLE
README links

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#1471]
In the README section of the base repository, the Installation and Handbook links do not work - https://github.com/python-pillow/Pillow

I would just create a PR to update them, but I'm uncertain of which version of the docs to link to - latest, or a specific version - and how people would like to update them through the process of version releases.

**Comment by wiredfool** [comment]
I think that's an artifact of having more than one version of the docs in readthedocs. They really should put a redirect in to the preferred one, since this winds up breaking the web when they change their url structure to add a version/lang in the url. 

I think I'd link to latest, since that's the one that is likely to be stable over long time frames, rather than 3.0.x, which will require updating every 3 months. And we've already got too many places where the version number changes every release.

**Comment by radarhere** [comment]
Okay, thanks. I've created the PR accordingly.
