### ISSUE TITLE
Test for Windows clipboard

### ISSUE THREAD

**Issue by techtonik** [python-pillow/Pillow#1527]
To solve #1293 Pillow needs a test that saves current screen to clipboard. The relevant C code for WinAPI is located in https://stackoverflow.com/questions/3291167/how-to-make-screen-screenshot-with-win32-in-c Can anybody compile it into executable and tell what it returns on AppVeyor?

**Comment by radarhere** [comment]
Are you talking about the top voted answer? If so, that code is nearly identical to the existing `GrabScreenWin32` function - https://github.com/python-pillow/Pillow/blob/master/display.c#L323

If you're just asking what happens when the function is run on AppVeyor, that's fine, just trying to figure it out, thanks.

**Comment by hugovk** [comment]
`GrabScreenWin32` in the C layer is called through `Image.core.grabscreen` [in the Python layer](https://github.com/python-pillow/Pillow/blob/a0a0e8e39f0f2b7fd321d904a2d8c8704730fa4e/PIL/ImageGrab.py#L25
), but they can't be called on AppVeyor due to [some graphics issue with the headless VM](https://github.com/python-pillow/Pillow/issues/1293#issuecomment-114191525).

It'd still be good to have regression tests for any #1293 fixes, even if they can only be run locally on a Windows machine. (If running them causes failures on AppVeyor, name then `check_*` instead of `test_*` so the CI doesn't pick them up.)

**Comment by techtonik** [comment]
@hugovk what exactly doesn't work with headless VM? Can it happen that it is only Pillow code that doesn't work because of the same reasons it doesn't work on Windows in #1293.

**Comment by techtonik** [comment]
This is how people save screens on AppVeyor - https://github.com/FeodorFitsner/selenium-tests/blob/master/take-screenshot.ps1

**Comment by hugovk** [comment]
I've not investigated myself but doubt it's caused by #1293.

**Comment by techtonik** [comment]
@hugovk the description in #1293 is shady - `the ImageGrab functions don't work on the windows CI`. What exactly doesn't work is not clear and that's why I created this ticket. It may happen that it is AppVeyor specific problem, but without test it is hard to tell.

**Comment by radarhere** [comment]
A test for `ImageGrab.grab` has been enabled in #3424. Whatever issue may have existed with testing it on AppVeyor in the past, it no longer applies.
