### ISSUE TITLE
TgaImagePlugin doesn't handle corrupt/empty file

### ISSUE THREAD

**Issue by dsoodak** [python-pillow/Pillow#1693]
```
File "C:\Users\dsoodak\Anaconda2\lib\site-packages\PIL\TgaImagePlugin.py", line 57, in _open
idlen = i8(s[0])
IndexError: string index out of range
```

Happens when trying to read corrupt file
Fixed it in my local copy of TgaImagePlugin.py with 2 lines of code

``` python
def _open(self):
    s = self.fp.read(18)
   #Fix:
    if len(s)==0: #Make sure file was read
        raise SyntaxError("no lines read")
```

I made it a "Syntax Error" to match all the other errors thrown from this function so the library I am using knows how to handle it.

**Comment by radarhere** [comment]
Hi. When I attempt to replicate this error, I find that the IndexError is caught at https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L2278 and subsequently throws `IOError: cannot identify image file`.

If this isn't happening for you, then I assume you're calling `TgaImagePlugin` more directly. Would you be able to post the code you are using to produce this error, so that we can get a sense of the bigger picture?
