### ISSUE TITLE
Image.save does not work with pathlib.Path objects that represent non-existant files

### ISSUE THREAD

**Issue by spencera1** [python-pillow/Pillow#1747]
Using Pillow 3.1.1, I'm running into an issue while trying to use pathlib.Path objects with Image.save. Image.save does not work with pathlib.Path objects that represent non-existant files.

```
>>> from pathlib import Path
>>> from PIL import Image
>>> path_exists = Path('existing_file.jpg')
>>> path_not_exists = Path('non-existant_file.jpg')
>>> test_img = Image.new('RGBA', (100,100))
>>> # no issues with this one
>>> test_img.save(path_exists)
>>> # FileNotFoundError: [Errno 2] No such file or directory: 'non-existant_file.jpg'
>>> test_img.save(path_not_exists)
```

**Comment by radarhere** [comment]
Thanks for reporting this bug. The problem is because the pathlib.Path `resolve` method throws this error if the file does not exist. So rather than performing `str(fp.resolve)`, I think the solution is to use `str(fp)`.

You possibly have more experience in using pathlib than I do. Does this sound like a reasonable plan?

**Comment by spencera1** [comment]
Since the working directory isn't changing in the save code, and the path isn't being used to generate another path, I would think you'd be safe with str(fp). Canonicalization doesn't appear to be getting done on a regular string path, so it's probably more consistent to do str(fp) anyway.
