### ISSUE TITLE
PDFs and 1 bit pixels

### ISSUE THREAD

**Issue by wfbradley** [python-pillow/Pillow#1775]
I posted this question [on Stack Overflow](http://stackoverflow.com/questions/36121914/pillow-pdf-and-1-bit-pixels) before realizing that perhaps I should post it here.

I'm trying to create a PDF of a complicated black-and-white rectangular grid, nominally 7 inches wide by 10 inches tall.  I'm using Pillow to do the conversion.  If I specify a PNG, everything works fine (that is, the aspect ratio is 7 by 10).  If I specify a PDF, the output is 200 inches wide and 0.04 inches tall.  What's going on?

Incidentally, if I set `mode='RGB'`, then the output PDF dimensions are correct, but Pillow performs a JPEG encoding of the image. JPEG converts my sharp black and white grid into smoother shades of gray (which is anathema for my application).

```python
import PIL
from PIL import Image

# Let's consider a 7" x 10" rectangle of pixels
inches_wide=7
inches_tall=10
dpi=200
num_pixel_rows=inches_tall*dpi
num_pixel_cols=inches_wide*dpi

# Make an image
mode='1'
img = Image.new( mode, (num_pixel_cols,num_pixel_rows))
img.info['dpi'] = (dpi,dpi)

# Saving it as PNG, we get a black rectangle, as expected.
img.save('big_rectangle.png','png',resolution=dpi)
# Saving it as a PDF, we get a 200" x 0.04" all-white line?!
img.save('big_rectangle.pdf','pdf',resolution=dpi)

# Versioning info:
print 'PILLOW',PIL.PILLOW_VERSION
print 'PIL',PIL.VERSION
#  My output:
#  PILLOW 3.1.1
#  PIL 1.1.7
```

**Comment by aclark4life** [comment]
Not sure what's going on… should we call this a bug?

**Comment by nawagers** [comment]
So I investigated this a bit and it is a bug that existed pre-fork as best I can tell. The lines in question are in PdfImagePlugin.py(line:173):

```
if filter == "/ASCIIHexDecode":
    if bits == 1:
        # FIXME: the hex encoder doesn't support packed 1-bit
        # images; do things the hard way...
        data = im.tobytes("raw", "1")
        im = Image.new("L", (len(data), 1), None)
        im.putdata(data)
    ImageFile._save(im, op, [("hex", (0, 0)+im.size, 0, im.mode)])
```

The problem lies in the im = Image.new() call. The size is specified as (len(data),1) which is (350000, 1) in the example code. It works to change it to im.size, but that has no compression.

I would assume anyone using mode 1 is probably wanting to keep their output file super small. The ASCIIHex filter has no 'image' compression or data compression and generates a 5.5 MB file in the example. The equivalent PNG is 421 Bytes. The ideal situation would be for someone to implement one of the lossless algorithms and supply a flag to the save() function to use DCT or lossless encoding. Options are:

1. Change to im.size and convert to mode "L" as now
2. Convert to mode "P" further upstream (uses ASCIIHex instead of DCT)
3. Generate some sort error on mode "1", forcing user to convert to P

**Comment by radarhere** [comment]
#3827 has been merged, so the dimensions problem should now be fixed. However, there seems to also be a request for compression here.

**Comment by radarhere** [comment]
I've created PR #5430 to add DCTDecode compression for 1-bit PDFs.

**Comment by radarhere** [comment]
I've created PR #6470, which uses CCITTTaxDecode compression, reducing the PDF down to 1kb.
