### ISSUE TITLE
Error in Image.new

### ISSUE THREAD

**Issue by liminspace** [python-pillow/Pillow#1808]
After update to 3.2.0 I have broken test in my project with error.

``` python
from PIL import Image

Image.new('P', (200, 200), color='#DDEEFF')

ERROR:
  File "/home/igor/.virtualenvs/dju-image/local/lib/python2.7/site-packages/PIL/Image.py", line 2036, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)
```

**Comment by liminspace** [comment]
Maybe I should pass color as integer 0-255. But I can't pass RGB color as before.

**Comment by wiredfool** [comment]
Pretty sure that's from the cleanup of the _getink function so that it doesn't use uninitialized variables. 

Try passing in a tuple of (0xdd, 0xee, 0xff).

**Comment by hugovk** [comment]
Looks like an unintentional bug, especially as it's occurring between the Python and C layers of Pillow.

`git bisect` says 5ff9f24fcc713795b580e6e22b42e50e7f17fcf0 is the first bad commit from PR https://github.com/python-pillow/Pillow/pull/1663.

**Comment by hugovk** [comment]
`Image.new('P', (200, 200), color=(0xdd, 0xee, 0xff))` also has the same error.

**Comment by wiredfool** [comment]
Did the previous version work correctly, or did it just run?

When doing getink in a `P` mode image, it has to be a integer, since there's no support for quantizing the rgb color into a number. 

I think for it to work correctly, the image would have to be created as `RGB(A)` and then converted to a `P` mode so that it would go through the quantization process.

**Comment by hugovk** [comment]
```python
from PIL import Image
im = Image.new('P', (200, 200), color='#DDEEFF')
im.save("out.png")
```
3.1.0 runs but not correctly:
![out](https://cloud.githubusercontent.com/assets/1324225/14261048/7adc3b6a-fab7-11e5-979d-9cb5a0042456.png)

**Comment by hugovk** [comment]
```python
from PIL import Image
im = Image.new('RGBA', (200, 200), color='#DDEEFF')
im.convert("P")
im.save("out2.png")
```
Converting with 3.1.0 works correctly:
![out2](https://cloud.githubusercontent.com/assets/1324225/14261153/0f2976d4-fab8-11e5-925c-df11f32cd96f.png)

**Comment by hugovk** [comment]
Converting with 3.2.0 also works correctly:
![out3](https://cloud.githubusercontent.com/assets/1324225/14261303/a8975020-fab8-11e5-8272-9b9d9c924a47.png)


So: 
 * the original snippet didn't work in 3.1.0 but otherwise ran smoothly so the error wasn't visible,
 * in 3.2.0 the original snippet also doesn't work, and also results in an error,
 * creating as RGBA and coverting to P works with both 3.1.0 and 3.2.0.

**Comment by radarhere** [comment]
I've created PR #3719 to resolve this.
