### ISSUE TITLE
Paste issues

### ISSUE THREAD

**Issue by simonschofield** [python-pillow/Pillow#1911]
### What did you do?
I am using pillow image paste to construct large collage images from many small ones. The large target image is initially set to have an overall alpha of 0, so is like an empty transparent Photoshop layer if you like. I am pasting smaller images with various alphas onto this
You can see such images at www.simonschofield.net.
### What did you expect to happen?
I expect that the paste function mimics the Duff Porter OVER composite algorithm
### What actually happened?
I have noticed two things wrong with paste.
1/ If you paste onto a fully transparent area of the target canvas image it seems to blend with a mid-grey creating dark halos around light objects. This is not in accordance with Duff Porter: it should set the colour to that of the incoming pasted pixel, and set the alpha to the same as the incoming pixel.
2/ Multiple applications of Alphas of pasted pixels to the same point in the large canvas image should should always contribute (i.e. always get greater, stopping at 255). I have noticed that pasted images with low alpha seem to lessen the alpha of the existing pixels in the canvas image, making those areas more transparent.

Also, is paste the only way of compositing a small image into a larger one?

### What versions of Pillow and Python are you using?
Pillow is about v3
Python 3.3.3 64bit

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python
code goes here
```

**Comment by wiredfool** [comment]
You might want to look at `Image.alpha_composite`: http://pillow.readthedocs.io/en/3.2.x/reference/Image.html?highlight=alpha_composite#PIL.Image.alpha_composite

**Comment by simonschofield** [comment]
Thanks, sounds promising. Will do. Is this a new feature, I don't remember seeing it in my in my version?


________________________________

**Comment by simonschofield** [comment]
Ahh but it says the source must have the same size as the target image, I want to paste smaller images into a big image.


________________________________

**Comment by simonschofield** [comment]
Ignore last email. I was looking at blend by mistake


________________________________

**Comment by simonschofield** [comment]
No, alpha composite need two images of the same size. I want to composite image A at point P within image B


________________________________

**Comment by simonschofield** [comment]
The documentation admits my second point

"Where the mask is 0, the current value is preserved. Intermediate values will mix the two images together, including their alpha channels if they have them."

This is not useful in a standard paste operation and should be altered to accumulate the alpha or at least have the choice with a flag


________________________________

**Comment by wiredfool** [comment]
Does alpha composite do the right thing if it could compose a small image over a large one?

**Comment by syranide** [comment]
@wiredfool I've encountered this as well, the current behavior seems useless and not what one would expect, and the only way around it I've found is rather hacky. Are you amenable to changing this behavior?

Alpha composite is not applicable to my use-case as I'm trying to render an image mask with different colors (i.e. setting im to a color a value rather than an image).

**Comment by wiredfool** [comment]
In general -- we don't tend to want to break existing use of the function. 

Practically, a parameter to paste, like disposition, may be appropriate, or alpha_composite might be the right approach, if extended to take a region of interest.

**Comment by syranide** [comment]
@wiredfool alpha_composite isn't really well suited for many small operations though as it's not inplace. So by that logic extending `paste` with a new argument would make most sense? Or perhaps inplace + box for alpha_composite?

**Comment by wiredfool** [comment]
Is alpha_composite the operation that you're looking for? (leaving aside efficiency)

**Comment by syranide** [comment]
@wiredfool Sorry, got a bit distracted there. No it's not, I'm specifically using `paste` with a solid color and a mask, so that I can dynamically change the color of what I'm rendering. `alpha_composite` does not support that, and as far as I can tell `alpha_composite` is pretty much the same thing as `paste` with just an image (which works fine, it's paste with a mask that doesn't).

> In general -- we don't tend to want to break existing use of the function.

Just so that it is said. Pasting an transparent image onto a transparent image works fine, pasting a mask onto an opaque image works fine, pasting a mask onto a transparent image mixes colors from the destination regardless of destination alpha. This seems backwards and not at all useful to anyone, IMHO it really seems like a bug. But I get it if you want to keep it that way.

PS. Even `paste` isn't perfect for my use-case, I'm pasting pieces from an alpha spritesheet so I first have to `crop` out the sprite and then `paste` that onto the final image. But it works well enough.

**Comment by wiredfool** [comment]
So, I'm not really sure that I understand what you're aiming for. Here's my understanding:

- You have an 8 bit grayscale image (of a sprite) that you're using as alpha.
- You combine that with a flat color, to yield a partially transparent image of the sprite, in the color that you're using. 
- You're combining this on some form of background (unclear here, flat color? image? overlapping? transparent?).

In stage 3, `paste` with a hard mask will replace the existing pixels with the new one. `paste` with a partial mask will blend the pixels. `alpha_composite` will use the alpha mask from the sprite to blend it in. (e.g., monochrome sprite on background color, so a duotone)  

E.g.:

```
(vpy27)erics@builder-1204-x64:~/test$ python
Python 2.7.3 (default, Aug  1 2012, 05:14:39) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.open('Tests/images/hopper.png').convert('L')
>>> sprite = Image.new('RGBA', im.size, 'red')
>>> sprite.putalpha(im)
>>> sprite.save('issue_1911_sprite.png')
```
![issue_1911_sprite](https://user-images.githubusercontent.com/19792/27076543-71e011fc-5025-11e7-876f-b13ed9ae9d71.png)

```
>>> background = Image.new('RGBA', (200,200), 'blue')

>>> mask = Image.new('L', sprite.size, 'white')
>>> mask.paste('black', (0,0,64,64))
>>> mask.paste((128), (65,65,128,128))
>>> mask.save('issue_1911_mask.png')
```
![issue_1911_mask](https://user-images.githubusercontent.com/19792/27076559-7be97db4-5025-11e7-9e02-527212ffb44a.png)
```
>>> paste = background.copy()
>>> paste.paste(sprite, box=(32,32), mask=mask)
>>> paste.save('issue_1911_pasted.png')
```
![issue_1911_pasted](https://user-images.githubusercontent.com/19792/27076563-80ad0140-5025-11e7-9b64-c38212d76d75.png)
```
>>> alpha = Image.alpha_composite(background.resize(sprite.size), sprite)
>>> alpha.save('issue_1911_alpha.png')
```
![issue_1911_alpha](https://user-images.githubusercontent.com/19792/27076571-875b2c56-5025-11e7-859a-0b2aee82ec27.png)


So does one of these operations cover what you want as output? If so, which one, and if not, can you explain with some sample code?

**Comment by syranide** [comment]
@wiredfool Sorry for the delay, been out of country. Sorry I thought I was being more clear, should've posted my testcode from the start. Yes that is exactly what I'm expecting, but that's not what pillow gives me when pasting a mask on a *non-opaque* background.

See:

```
from PIL import Image

im = Image.open('img.png')

im1 = Image.new('RGBA', (im.width, im.height), (0, 255, 0, 0))
im1.paste(im)
im1.save('a0.png')

im1 = Image.new('RGBA', (im.width, im.height), (0, 0, 255, 0))
im1.paste(im)
im1.save('a1.png')

im1 = Image.new('RGBA', (im.width, im.height), (255, 0, 0, 0))
im1.paste((0, 255, 0), mask=im)
im1.save('b0.png')

im1 = Image.new('RGBA', (im.width, im.height), (0, 0, 255, 0))
im1.paste((0, 255, 0), mask=im)
im1.save('b1.png')
```

![a0](https://user-images.githubusercontent.com/1714255/27171625-773e0d5a-51b2-11e7-878f-49f1a586e115.png)
![a1](https://user-images.githubusercontent.com/1714255/27171631-7b2c9cf6-51b2-11e7-8767-a101c47e5093.png)

I would expect `a0.png` and `a1.png` above to be the red transparent dude, they are.

![b0](https://user-images.githubusercontent.com/1714255/27171637-7e556fc0-51b2-11e7-8821-ede3220cd15f.png)
![b1](https://user-images.githubusercontent.com/1714255/27171643-8144cf5a-51b2-11e7-8ec4-94a097b306c8.png)

I would expect `b0.png` and `b1.png` above to be a green transparent dude, they are not, `b0.png` has a red tinge and `b1.png` a blue tinge, sample from the totally transparent background. Because even though it's totally transparent the color channels are still mixed in.

**Comment by syranide** [comment]
Now I see that `paste` doesn't alpha composite at all, which I thought it did. But when using `mask` it kind of does, but badly as above. I'm trying to render text (custom font system), so I need to alpha composite individual letters from a mask sprite sheet (which can also be colored then). So `paste` with color, bbox and mask given that it would alpha composite correctly is exactly what I need. But plain `paste` does not alpha composite and so does not work. `alpha_ composite` only takes takes two equally sized images and so is clunky/slow, it requires me to first use `paste` to render the character in the desired color to a separate buffer (final image sized) and then alpha composite that into the final image, for each letter.

**Comment by wiredfool** [comment]
(FYI, the 'dude' is Admiral Grace Hopper, the writer of the first compiler, namer of the computer bug, distributor of nanoseconds.)

Masks are not alpha channels. Similar but different ideas. 

A mask is a selection, possibly partial, that will select an area to paste. It's similar to a selection mask in photoshop, though there might be implementation details.

Alpha is a transparency function, and alpha composite uses that transparency as a mask to overlay the second image on the first. 

As for the last two images, they are poorly specified in 2 ways:
- a fully transparent color is arbitrary. It's imaginary in the same way that some L*ab colors are imaginary, such as a ultra dark saturated yellow.  It's possible that we should be doing this conversion in the premultiplied alpha space (RGBa). I know that we've had to do that with transforms.
- Off hand, I'm not sure what alpha value (0,0,255) has. It's not specified, it may default to 255, but I'm not sure. 

If I were to do this with the current tools, I'd do this: 

- Three buffers, of the final size. 
- `RGBA` background buffer, `RGB` color buffer, and `L` alpha buffer. 
- For each letter, get the bounding box. Paste the color into that bounding box in the color buffer, and paste the mask into the same bounding box in the alpha buffer. 
- use color_buffer.putalpha(alpha_buffer)
- final_image = Image.alpha_composite(background, color_buffer)

**Comment by syranide** [comment]
> If I were to do this with the current tools, I'd do this:

@wiredfool Yeah that makes sense a lot of sense actually. However, we support kerning so the bounding boxes overlap, which means I require alpha compositing for each letter. So it seems `paste` is not usable for this and `alpha_composite` is too heavy-handed (both because it returns a new buffer and requires an equally sized input buffer).

I.e. my use-case requires an alpha compositing paste (if it could have a source bbox as well that would be even better). I'm a little surprised this doesn't already exist considering it is generally a core feature of most libraries.

**Comment by wiredfool** [comment]
So, to finally circle around to answer the original question -- alpha composite is the proper image operation, and if it were extended using a bounding box for placement it would solve your problem.

**Comment by syranide** [comment]
@wiredfool `alpha_composite` is the right image operation yes and the one I'm currently using. Let's put it like this, for my use-case I see the following possible enhancements of `alpha_composite`:

1. Support "target point/bounding box". I no longer have to pad each character before rendering to final buffer.
2. Support "inplace". So that each character no longer generates a new final-sized buffer (slow).
3. Support "source bounding box". So that I do not need to crop letters out before-hand (although I still might for coloring purposes).

**Comment by wiredfool** [comment]
Thinking about this a bit more, it's possible that the procedure here: https://github.com/python-pillow/Pillow/issues/1911#issuecomment-308869854 would work.

If, instead of pasting in a flat color in the bounding box, you added a mask of the letter as well, filtered through a point function where f(0) = 0, and f(x>0) = 255. That would solve the bounding box overlap problem, at least for any letters that didn't physically intersect. 

I'm looking at the alpha composite issue as well, I've got a trial implementation in python here: https://github.com/wiredfool/Pillow/tree/issue_1911 . It implements a method on PIL.Image.Image: im.alpha_composite(over_img, box), where the source/background image is modified in place. (sort of, but at an API level, that's what's going on. It's going to require tweaking on the C level to actually do it in place. But if this is an API we can live with, then that's a start ).

**Comment by syranide** [comment]
@wiredfool Looks good, but I would add a source-point parameter as well considering "box" already crops the source, it seems weird not to allow control over the positioning but force it to `(0, 0)`.

**Comment by wiredfool** [comment]
Ok, I've added the source. I'm not 100% on how the size is specified as an optional part of the 4 tuple. There has to be only one size, I'm not into adding a scale factor in this, as ultimately it's going to wind up in C and I'd like for it to be as straightforward as possible at that layer.

**Comment by syranide** [comment]
@wiredfool :+1: Yeah scaling doesn't make sense. Just a nitpick, personally I think it makes more sense logically to specify size in the source-argument rather than target-argument, but end result is the same.
