### ISSUE TITLE
What is the difference between Image and ImageFile?

### ISSUE THREAD

**Issue by rlam3** [python-pillow/Pillow#1971]
### What did you do?

Trying to extract size form image via url. I want to minimize delay and download least amount of info.
Came across two differen way to do this...
Not sure which one is better than the other. 
Would love some feedback on this. Thanks!

### What versions of Pillow and Python are you using?

3.1.0

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python

    import urllib, cStringIO
    from PIL import ImageFile, Image

        URL = self.some_URL

        # OPTION 1
        
        image_file = cStringIO.StringIO(urllib.urlopen(URL).read())
        image = Image.open(image_file)
        
        image_size = image.size
        return image.size

        # OPTION 2
        file = urllib.urlopen(URL)
        p = ImageFile.Parser()

        data = file.read(1024)
        p.feed(data)

        width, height = p.image.size

        return width, height


```

**Comment by wiredfool** [comment]
Generally, ignore ImageFile.   Use `Image.open`.

**Comment by wiredfool** [comment]
The problem with `ImageFile.parser` is that in a lot of cases, it doesn't actually gain you a whole lot, and you can get in a state where it's much more expensive than opening the file directly. 

1) Several of the image plugins are not compatible with the feed interface, so if you're actually decoding them, they basically loop around, store the data, and then finally decode it when you close the parser. This includes common types like JPEG and PNG.  So, if you're using the feed interface to cut down on the duplicate copies of the data, you aren't.

2) If you have an invalid image that throws an exception due to corrupt metadata or an unsupported format, the Parser class will silently attempt to parse the whole thing every time you call feed with new data. 

That being said, if you know that you're only looking for image size, most (but my no means all, like TIFFs) images store the size in a header somewhere and you can just feed it 1k or so and you'll get the data you're looking for.
