### ISSUE TITLE
Rebase label

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#2003]
Throwing out this idea - a 'Needs Rebase' label?

It would be helpful to be able to see that information when looking through the list of PRs.

**Comment by wiredfool** [comment]
Yeah, sure. In fact, labels that in general indicate the next step that needs to happen are helpful. For example, a red X can mean real or irrelevant test failures, coveralls is whacked, or a merge error.  This can mean that we need input from the submitter.  Things like 'needs test case' on bug issues could be useful as well, if we've got a minor issue that gets in that state and then doesn't get anything for a month, we can just close it down rather than have it sit open for a year. 

The other thing that I tried to do yesterday in my issue sweep was to tie some of the issues together. There are a lot of palette issues, and I think the core is just a couple of bugs that I'm close to finding.

**Comment by radarhere** [comment]
Yep, sounds good. Thanks for those thoughts. I'm surprised that the palette issues have overlap, although I probably shouldn't be.

I can see that you've created the 'Needs Rebase' and 'Needs Test Case' labels, and I've gone through and added 'Needs Rebase' to the appropriate PRs.
