### ISSUE TITLE
ImageGrab on Linux

### ISSUE THREAD

**Issue by techtonik** [python-pillow/Pillow#2028]
### What did you do?

Got Ubuntu 16.04.

```python
>>> from PIL import ImageGrab
```
### What did you expect to happen?

```python
>>>
```
### What actually happened?

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/PIL/ImageGrab.py", line 22, in <module>
    raise ImportError("ImageGrab is OS X and Windows only")
```
### What versions of Pillow and Python are you using?

```python
>>> PIL.VERSION
'1.1.7'
>>> PIL.PILLOW_VERSION
'3.1.2'
```

So, what is the proper way for saving screens on Linux?

**Comment by techtonik** [comment]
Found this - http://stackoverflow.com/a/16141058/239247 - not sure if that is a good way.

**Comment by Metallicow** [comment]
Second thought:
pyscreenshot https://pypi.python.org/pypi/pyscreenshot is a replacement module for ImageGrab.
But yes, it would be nice to have ImageGrab completely cross compatible in the Pillow library. 
Maybe try asking the author to license it under PIL/Pillow license.
Or look at the code and review what changes might need to ImageGrab and implement them similarly in the module.

**Comment by lesmana** [comment]
https://github.com/BoboTiG/python-mss

it seems to do all the work itself without calling other tools. it claims to work on all platforms. cannot test because i do not have windows nor mac.

license is zlib/libpng. do not know how easy it is to integrate code in PIL/Pillow MIT like license.

**Comment by BoboTiG** [comment]
I am the developer of the [MSS](https://github.com/BoboTiG/python-mss) module. I changed the license for MIT in the `dev` branch. I added a good documentation and tests are coming. If you are interested in the use of my work and need few adjustments in the API, we can talk :)

**Comment by techtonik** [comment]
@BoboTiG basically Pillow needs to know what is the format of raw data that is returned from some screenshot call to give it a type. Another issue is that PIL code doesn't have any install dependencies, so either include the code as-is, or make it as optional dependency. @aclark4life should know better what is the proper way to resolve this with PR.

**Comment by BoboTiG** [comment]
The format is always simple "RGB".  For the unique dependence, it is optional but will boost the screenshot. I am still working on to speed-up the process.

**Comment by BoboTiG** [comment]
Another update to notify that MSS has no more dependencies. Changes are in the `dev` branch.

**Comment by rajatgoyal715** [comment]
[pyscreenshot](https://github.com/ponty/pyscreenshot) library can be used
Refer here : https://stackoverflow.com/a/43636492/5463601

**Comment by shish** [comment]
I'm interested in getting this working, but curious which approach to take since I don't own either of the libraries:
- copy-paste code from mss into pillow (all the users get fast, cross-platform screenshots all the time, but code is duplicated between pillow and mss - I'm not sure if @BoboTiG is happy to have his code "stolen" like this, or if the Pillow maintainers are happy to maintain the code; but as an end user I like this approach because everything is awesome out of the box)
- add mss as an optional dependency from pillow, and have ImageGrab just become a simple wrapper, replacing the current code, raising an exception if mss isn't installed (users get fast cross-platform screenshots, but they need to install an extra library)
- add mss as an optional dependency, and keep the current ImageGrab code as a fallback (the most compatibility; but ImageGrab will be slow by default, and there's more code to maintain, and there's no way for users to know that they could get a 100x performance improvement by installing mss)
- add mss as a hard dependency (This would also be good as an end user, but if I'm understanding correctly, Pillow has a rule of "no hard dependencies"?)

**Comment by BoboTiG** [comment]
Thanks @shish !

IMO the option 1 is not ideal for either part. Code duplication will result in too many issues, patches not sent upstream or big code difference between implementations with time.

Option 2 may be good. It can let the user to not use MSS. A simple warning can be triggered if not installed (noisy but skipable by users).

I think the option 3 will be useless. Users will continue to have a slowly (and in many cases not working at all) version without notice. Most people will not be aware at all of the alternative way.

Option 4 is a good, but it is not my voice here :)

I can think of a 5th option: vendoring. PyPi is doing that and it seems to work pretty well. Issues and patches should be opened upstream and changes will automatically by available with the next Pillow release. The only drawback is that you can't have an up-to-date MSS version depending of the release process of Pillow. Using the option 4 will allow user to simple have the latest MSS version more quickly.

BTW thanks for compliments :)

**Comment by redstoneleo** [comment]
As I 've tested , PyScreenshot is not slow on Linux , instead I felt it is really fast, so any consideration on incorporating the Linux part of PyScreenshot into this project ?

**Comment by shish** [comment]
What is "fast" for you? PyScreenshot's own benchmarks in the README say that the fastest backend is ~340ms to take a screenshot, compared to ~5ms using native functions like mss does...

(But still, having imagegrab work on Linux would be nice for a lot of people, even if it doesn't work for real-time needs :P )
