### ISSUE TITLE
Basic building questions

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2165]
While I'm developing Pillow for a while, I still don't understand some basics.

### How I can build C code for sure?

There is a separate `build_ext` command:

```
$ python ./setup.py build_ext
```

But like `install` and `develop` command, it doesn't build the extension if no files are modified since the last build. And if I do the following:

```
$ python ./setup.py build_ext --disable-zlib develop
```

Pillow reports two times (one for build_ext, one for develop) that "ZLIB (PNG/ZIP) support not available". But if I simply run `selftest.py`, it reports that "ZLIB (PNG/ZIP) support ok".

### Preventing from compile two times

That is why I always using `touch ./libImaging/Resample.c` before compiling:

```
$ touch ./libImaging/Resample.c && python ./setup.py build_ext --disable-zlib develop
```

But in this case, extension always compiled twice! And which is more terrible — some of the `build_ext` options are ignored. For example, if I pass:

```
$ touch ./libImaging/Resample.c && python ./setup.py build_ext --include-dirs ./inc develop
```

I see `-I./inc` arguments only on the first compilation.

Am I doing something wrong?

**Comment by wiredfool** [comment]
I don't like the develop option. I think it's reasonable for smaller, simple code bases, but it leads to confusing behavior in more complicated setups like we have. (this from memory, it's been more than a year since I've really dealt with it)

* As far as I know, develop is like install, but it links the current directory/package into the current python environment. I believe that this is a one time operation, so that once you've done `python setup.py develop`, then any changes and builds that you do are reflected. 

* Develop fails if you use a different python from the one that you built with, because the libraries that we make are not tagged for the python version that we're using. 

My current setup, on whichever platform that I'm using, is a set of virtualenvs: 2.6-3.5, pypyx2, and 2.7-dbg if available. Once one of them is activated, my usual sequence is `make install && make test`, or `make clean && make install && make test`.

Unfortunately, if there are more complicated bits for the build, like build flags or the debug option, they _have_ to be applied to the build_ext phase. (or possibly as a global option to setuptools, I think there's something about setuptools that allows that. I know it's been requested to be added to the docs, but...)   Once the extension is built, the install command will install it without building it again. This asymmetry with develop is one of the reasons that I don't like develop.

**Comment by homm** [comment]
> Once the extension is built, the install command will install it without building it again.

Hmm, I thought that except linking develop and install acts the same. In truth, "install" doesn't lead to second compilation. Personally, I prefer "develop" because I always work in one environment at a time and it allows do not reinstall on every python code change (only on C code). So, I can use at least when I need build_ext flags. Thanks!

Maybe we can bypass the timestamp check when we are сalling build_ext directly?

**Comment by wiredfool** [comment]
I think that would be more appropriate in a private fork of setuptools than in pillow, unless it's some sort of existing configuration flag.
