### ISSUE TITLE
Error when save a particular image

### ISSUE THREAD

**Issue by Lucuz91** [python-pillow/Pillow#2272]
Hi all,
I try to simply resize one image with Pillow (3.1.1, and i try on last 3.4.2 with same result) and the save function return an error.

The image is in this link 
https://drive.google.com/file/d/0BxZoHLj1LrNeNU5vSHpnSjFNNFE/view?usp=sharing

This is the code i use
```python
from PIL import Image

img = Image.open('path/to/image')
img.thumbnail((500, 500))
img.save("path/to/save", format="JPEG", quality=90, progressive=True)
```

And this is the error returned
```
Traceback (most recent call last):
  File "path/my/script.py", line 6, in <module>
    img.save("path/to/save", format="JPEG", quality=90, progressive=True)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1675, in save
    save_handler(self, fp, filename)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 708, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 486, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

This error don't appear with resize (900, 900) or quality 80.
The colorspace of image is CMYK, and if convert image in RGB before i save image all is right.
But why this error appear?

**Comment by wiredfool** [comment]
It appears from quality=90 to quality=94. 

You're hitting this region of the code: https://github.com/python-pillow/Pillow/blob/master/PIL/JpegImagePlugin.py#L720

There's a heuristic there to make the buffer large enough to get the entire image at one shot, and from quality=90 to quality=94, the compressed image size is too large for the buffer.  In this case, the buffer size is 133000 bytes when quality < 95. The size of the image at quality=89 is 126029, at 95 is 185252. 

It's probably larger by 4/3 in CMYK vs RGB.  (actually, testing it I'm seeing 44k in RGB vs 126k in CMYK.) So that's why it fails in CMYK and not RGB.
