### ISSUE TITLE
Invalid string escapes

### ISSUE THREAD

**Issue by nascheme** [python-pillow/Pillow#2280]
There are a couple of invalid string/byte escapes left in the code (Python 3.6 warn about them)::

./PIL/GimpPaletteFile.py:44: bad string escape 'if re.match(b"\\w+:|#", s):'
./PIL/PngImagePlugin.py:51: bad string escape 'is_cid = re.compile(b"\\w\\w\\w\\w").match'
./PIL/XbmImagePlugin.py:29: bad string escape 'b"\\s*#define[ \\t]+.*_width[ \\t]+(?P<width>[0-9]+)[\\r\\n]+"'
./winbuild/build_dep.py:111: bad string escape '""" + "\\n".join(\'set %s=%%BUILD%%\\%s\' % (k.upper(), v[\'dir\'])'
./winbuild/build.py:19: bad string escape 'ret.append("%s%s%s\\Scripts\\pip.exe install nose" %'
./winbuild/build.py:22: bad string escape 'ret.append("%s%s%s\\Scripts\\pip.exe install unittest2" %'

**Comment by hugovk** [comment]
@nascheme What do you run on Python 3.6 to get these warnings?

**Comment by nascheme** [comment]
It is a little script I wrote:
http://python.ca/nas/python/find_bad_escapes.py
I think ideally we would have a 2to3 like tool that just fixed the source code in-place.

**Comment by hugovk** [comment]
Looks like the PIL/ trio were fixed in PR https://github.com/python-pillow/Pillow/pull/2186, and the build.py:22 one was removed by PR https://github.com/python-pillow/Pillow/pull/2243, leaving:

./winbuild/build_dep.py:111: bad string escape '""" + "\n".join('set %s=%%BUILD%%\%s' % (k.upper(), v['dir'])'
./winbuild/build.py:19: bad string escape 'ret.append("%s%s%s\Scripts\pip.exe install nose" %'

**Comment by aclark4life** [comment]
Is this one fixed then?

**Comment by nascheme** [comment]
Just the winbuild scripts are left to fix.  This patch (untested) should fix them.

[pillow-escape.txt](https://github.com/python-pillow/Pillow/files/702451/pillow-escape.txt)

**Comment by hugovk** [comment]
PR: #2352.
