### ISSUE TITLE
PyPI shows Pillow 4.0.0 and 1.7.8

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#2337]
### What did you do?
1. Go to https://pypi.python.org/pypi/Pillow/

### What did you expect to happen?

Shows latest release.

### What actually happened?

Shows latest release and Pillow 1.7.8.

![image](https://cloud.githubusercontent.com/assets/1324225/21611373/3e011e0e-d1d5-11e6-8a1d-ab14ffe8bbf7.png)

Can Pillow 1.7.8 be hidden?

**Comment by wiredfool** [comment]
That's the last pillow that retains full compatibility with PIL. We've been leaving that in, but I'm not sure how useful it is at this point.

**Comment by aclark4life** [comment]
Yeah we do that on purpose. If you look at the [2.0.0 release](https://pypi.python.org/pypi/Pillow/2.0.0) you'll see this message:

```
Pillow >= 2.0.0 supports Python versions: 2.6, 2.7, 3.2, 3.3; 
Pillow < 2.0.0 supports Python versions: 2.4, 2.5, 2.6, 2.7.
```

I know I've used 1.7.8 recently when building old Plones running on 2.4, but I believe I can still do that regardless of the appearance of the version on PyPI… actually now that I think about it, maybe we should show the last of each series for whatever it's worth? E.g.

<img width="592" alt="screenshot 2017-01-03 10 45 46" src="https://cloud.githubusercontent.com/assets/72164/21613108/d186a786-d1a1-11e6-933c-611be811b2ae.png">

And no need to show 2.9.0 since it was followed by 3.0.0 which was "just the number after 2" if I recall correctly.

The point is: we can help PyPI give some visual clues about significant old releases with their show/hide feature.

**Comment by aclark4life** [comment]
@hugovk Satisfied with this for now?

**Comment by hugovk** [comment]
All good, thanks!
