### ISSUE TITLE
Image mode 'L' broken / Incorrect vertical offset of text

### ISSUE THREAD

**Issue by Polarnix** [python-pillow/Pillow#2358]
I'm stumped with some issues that suddenly occurred using Pillow and was wondering if anyone can explain this.

I encountered 2 issues simultaneously on a Ubuntu 14.04 computer where no new package updates have been applied between the instances of the script running OK and then failing.  I am using Python 2.7.6, Pillow 2.3.0 and FreeType 2.5.2.

A extract from my script with the relevant lines is as follows::

```python
#!/usr/bin/python

from PIL import Image, ImageFont, ImageDraw

bigfont = ImageFont.truetype("/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf",500)
labeltxt = 'Forecast'
img_txt = Image.new('L', bigfont.getsize(labeltxt), (255,255,255))
draw_txt = ImageDraw.Draw(img_txt)
draw_txt.text( (0,0), labeltxt, (0,0,0), font=font4 )
img_txt.save('forecast.png','PNG')
```

This then started failing with the message:

Traceback (most recent call last):
  File "test_pillow.py", line 7, in <module>
    img_txt = Image.new('L', font4.getsize(labeltxt), (255,255,255))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1790, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: an integer is required

However, changing the image mode from L to RGBA worked, but then I got a large vertical text offset as shown:

![forecast_bad](https://cloud.githubusercontent.com/assets/10920240/22018740/abfd1da0-dcb0-11e6-8694-f03ed5fdbe75.png)

I have ended up having to change my code to:

```python
#!/usr/bin/python

from PIL import Image, ImageFont, ImageDraw

bigfont = ImageFont.truetype("/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf",500)
labeltxt = 'Forecast'
img_txt = Image.new('RGBA', bigfont.getsize(labeltxt), (255,255,255,255))
draw_txt = ImageDraw.Draw(img_txt)
draw_txt.text( (0,-100), labeltxt, (0,0,0,255), font=font4 )
img_txt.save('forecast.png','PNG')
```

This now produces the correct result.

![forecast_good](https://cloud.githubusercontent.com/assets/10920240/22018744/b30d4610-dcb0-11e6-9600-45b396bfbe63.png)

Other script modules where text is rendered, but at smaller font sizes, are working fine with mode L and no offset.

Can anyone replicate this and explain what's happening here?  As the original code was OK and no new package updates have been applied I'm at a loss to understand what is going on.

**Comment by wiredfool** [comment]
The TypeError was a bug in getcolor that was fixed a ways back. I'm not sure about the offset. There have been some changes to the font metrics, but unless you've upgraded, you're not going to hit them. 

However, I'd recommend that you upgrade, as there's been several security issues since the 2.3.0 era.

**Comment by aclark4life** [comment]
@Polarnix I'm marking this as a bug but assuming it's already been fixed. Can you verify and close and/or do you mind if I close? Thanks

**Comment by nawagers** [comment]
This doesn't seem like a bug at all. It is expected behavior. Fonts generally do not draw all the way to the maximum of their ascent. Each glyph has its own height. You don't want the top of the rendered text to the top of the minimal bounding box either. Then if you drew '.....' and 'A' next to each other, they would not have the same baseline. I recommend you close it @aclark4life
