### ISSUE TITLE
Image.getcolors() return none 

### ISSUE THREAD

**Issue by tesseslol** [python-pillow/Pillow#2453]
### What did you do?
Function Image.getcolors()
### What did you expect to happen?
get a list
### What actually happened?
Image.getcolors() return none
### What versions of Pillow and Python are you using?
- Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
- Pillow (4.0.0)
```python
>>> from PIL import ImageChops
>>> image1 = Image.open("image/" + "test_f073e251-2aa1-4a1d-9e87-537c24994761__0x0__quality=90&cropw=252&croph=197&cropx=358&cropy=0&cropmode=pixel.jpg")
>>> image1
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=252x197 at 0x1E4BE48E470>
>>> image1.getcolors()
```

**Comment by wiredfool** [comment]
From: http://pillow.readthedocs.io/en/4.0.x/reference/Image.html#PIL.Image.Image.getcolors

> Returns a list of colors used in this image.

Parameters:	maxcolors – Maximum number of colors. If this number is exceeded, this method returns None. The default limit is 256 colors.
Returns:	An unsorted list of (count, pixel) values.

It should probably be called out in the returns clause rather than the parameters, but this is consistent with the documentation.
