### ISSUE TITLE
Request DDSImagePlugin

### ISSUE THREAD

**Issue by Metallicow** [python-pillow/Pillow#252]
I would like to request the .dds(direct draw surface) format be decoded and added as an image plugin. I guess this is the right place for requests...?

I found this as a start. It doesn't do all dxt formats but some basic ones.
http://nullege.com/codes/show/src%40p%40i%40pilgrim-HEAD%40pilgrim%40codecs%40__init__.py/9/dds.DDS/python

**Comment by dessant** [comment]
@aclark4life, could you reopen this feature request?

**Comment by dessant** [comment]
Thanks. ;)

**Comment by jleclanche** [comment]
That dds code's mine actually, from an [experimental PIL fork before Pillow existed](https://github.com/jleclanche/pilgrim).

A dds plugin would be really nice, eg. right now I need to load DXT1 / DXT5 data into Pillow so I have to write my own decoder again =\

**Comment by aclark4life** [comment]
@jleclanche Great! So no issue incorporating your dds code into Pillow? I see you are right, pilgrim was born almost a full year before Pillow (2009-11-26 vs  2010-07-31). Interesting.

**Comment by jleclanche** [comment]
@aclark4life I'm writing an updated version right now which I'm testing against files from .unity3d packing. What license do you want it under?

**Comment by aclark4life** [comment]
@jleclanche Great & good question. We use the same license is PIL, in case that helps you decide: https://github.com/python-pillow/Pillow/blob/master/LICENSE

**Comment by jleclanche** [comment]
@aclark4life ok I'll re-release the decoders as CC0 to make things simpler.

Are you in the #pil channel? I might need some help with writing the plugin.

**Comment by aclark4life** [comment]
@jleclanche Yes but you may need @wiredfool or other members of the @python-pillow/pillow-team to weigh in on "real" programming questions. For the @python-pillow/pillow-team , here's some IRC discussion about this issue: http://chat-logs.dcpython.org/day/pil/2016-01-04

**Comment by jleclanche** [comment]
https://github.com/HearthSim/python-unitypack/blob/79d583d2a031bfc8dbbc392258a511514240982e/unitypack/dds.py

Here's a dxt1 decoder, licensed CC0. It's pretty slow and will need to be rewritten in C but it's usable.
dxt3 / dxt5 are very straightforward to do from there (I'll be doing them soon-ish if no one else does)

DDS is a container format for s3tc and all the defines are in that file. [This](https://github.com/jleclanche/pilgrim/blob/master/pilgrim/codecs/dds.py) is a very old loader for dds (please don't use it), which should give an idea of how to write one.

**Comment by jleclanche** [comment]
I won't be filing a PR or anything, unfortunately I don't have time for that; I licensed it so that anyone may use it without having to worry about the license itself :)

By the way in that old project I also have an ftex (IW2 format) decoder lying around.. wouldn't mind making that CC0 as well if someone wants to push it to pillow.
https://github.com/jleclanche/pilgrim/blob/master/pilgrim/codecs/ftex.py

**Comment by jleclanche** [comment]
Updated link with a DXT5 decoder too:
https://github.com/HearthSim/python-unitypack/blob/a44c30486246df4aafc0a41adf122b5697e5cdd6/unitypack/dds.py

**Comment by jleclanche** [comment]
OK this is actually crazy. I try to write a simple read-only DDS plugin, looks like the API has changed since PIL - fair enough.

I spend four hours trying to figure out the API. I still haven't figured it out as I write this. And none of this is properly documented.

I'm in `DDSImageFile.load()` and keep getting the very helpful `_imaging.c:208: bad argument to internal function` when trying to save my image as a png. It looks like this stems from a check on `self.im`. Can't tell exactly what's wrong with it because **every single image plugin is written differently** and half of them don't even work. I tried referencing the GbrImagePlugin which was one of the simpler ones but it turns out it uses functions which don't even exist anymore.
So I look at IcnsImagePlugin and it creates an image through self.icns.getimage, which creates it through channels.get(...).copy(), which creates it through dataforsize), which creates it from a bunch of custom readers **argh**.
Jpeg2KImagePlugin does it with a custom decoder. Of course none of these are listed anywhere I can find, I have to dig in decode.c and figure them out manually.
It would look like the proper way to implement this is to write the dxt* decoder separate, but *I don't want to fork Pillow just to be able to read a custom image format*, that completely defeats the point.

Please *please* find some time to work on proper documentation on how to write an image plugin for a custom format and to clean up the image plugins.

**Comment by aclark4life** [comment]
@jleclanche I doubt much has changed since PIL, but if it has: you don't need to fork Pillow to fix it you can just fix it (send a PR). Rather than folks maintaining separate forks, we maintain one then release results to PyPI.

**Comment by jleclanche** [comment]
@aclark4life I fixed it eventually with @wiredfool's help. I'll send a PR.

Honestly there really needs to be a new plugin API, this was very painful.
