### ISSUE TITLE
Unexpected results when opening and saving images

### ISSUE THREAD

**Issue by Stophface** [python-pillow/Pillow#2536]
### What did you do?
I edited several images in `GIMP` and exported them as `.jpg`. I want to save all of them into another format (`.png`). I installed `Pillow` with `pip install Pillow`, started `Python` and tried this very simple line: 
`Image.open("edited-gimp.JPG").save("modified.png")`

### What did you expect to happen?
I expected to `.jpg` to be properly converted into `.png` and written onto my hard drive.

### What actually happened?
The outcome is wrong. It seems like it messes around with the order of the pixels. I additionally tried this
`Image.open("edited-gimp.JPG").save("modified.jpg")` which resulted in completely wrong colors and artefacts. I also tried to convert the original `.jpg` (not the one I edited in `GIMP`) which gave me wrong colors and artefacts. However, they are different than the ones which I get when working with the `GIMP` edited image. 

### What versions of Pillow and Python are you using?
Python 2.7
Pillow 4.1.1

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```
Image.open("edited-gimp.JPG").save("modified.png")
```

I uploaded the images here:
https://ufile.io/tiv7a

**Comment by wiredfool** [comment]
I can't reproduce the issue here. The saved images look like you're getting a JPEG decompression glitch but the originals work fine in Pillow here, as well as imagemagick. 

As an aside, that is the most annoying image hosting I've seen. Doesn't work with wget and it's as slow as molasses.

For reference, the original and corrupted images are:

![edited-gimp](https://cloud.githubusercontent.com/assets/19792/26350260/7958be24-3faa-11e7-9873-0343b278e497.jpg)


![modified](https://cloud.githubusercontent.com/assets/19792/26350281/89b86b52-3faa-11e7-82c8-21d63067851d.jpg)
