### ISSUE TITLE
Grayscale PNG image incorrectly converted to RGB

### ISSUE THREAD

**Issue by nomarek** [python-pillow/Pillow#2574]
I have a PNG image which incorrectly converts to RGB mode. This is a grayscale 16-bit image, presumably created in Photoshop. When I open it with Pillow, mode of an image is described as `"I"`. I tried to convert it by calling:
```python
from PIL import Image
Image.open('original.png').convert('RGB').save('result.png')
```
All I received was a white image with only black pixels rgb(0, 0, 0) copied from the original. I am using newest version of Pillow (4.1.1), problem appears both in Python 2.7 & 3.6.
I am attaching 2 files:
- original.png - original image used to reproduce this problem
![original](https://user-images.githubusercontent.com/3820109/27035237-e30f73ea-4f80-11e7-957a-364cc714b1db.png)
- result.png - result of the conversion
![result](https://user-images.githubusercontent.com/3820109/27035238-e313b996-4f80-11e7-897a-d5e54f4e8854.png)

**Comment by wiredfool** [comment]
So what's happening here is that the convert from 'I' to 'L' loses information, and the conversion isn't done is a particularly useful fashion. It's clamping the range of the 16bit image to 0-255, rather than (auto)scaling it. 

Unfortunately, I don't see a quick way to autorange the image so that it fits into the destination image format, but there's a workaround with imagemath. (any of the embedded functions that rely on histogram or lookup tables aren't going to work)

```
>>> from PIL import ImageMath
>>> im2 = ImageMath.eval('im/256', {'im':im}).convert('L')
```

**Comment by aclark4life** [comment]
I'm going to call this "documented workaround" and close.

**Comment by keck-in-space** [comment]
This should be re-opened and fixed IMO. Or at least better documented. Digging into closed issues isn't intuitive. It took quite a while to find this fix.
