### ISSUE TITLE
Saving multiple crops from a big image won't work properly

### ISSUE THREAD

**Issue by mratmartinez** [python-pillow/Pillow#2696]
I specified it in this [StackOverflow question](https://stackoverflow.com/questions/45891849/pillow-is-not-properly-saving-images).  
After replacing Pillow with an alternative, and using the same algorithm, it worked.

What I was trying to do is cut a really big image in as many 32x32 px as possible.

It did a good job with less than a 10% of the images, but saved the rest of the results as blank images.

This happened using Pillow 4.2.1 in Python 3.5.3

I'll attach a .tar.gz with the script and the image that gave me this little problem.
[PillowBug.tar.gz](https://github.com/python-pillow/Pillow/files/1253483/PillowBug.tar.gz)

**Comment by hugovk** [comment]
You're mixing up your Xs and Ys.

Your code:
```python
#!/usr/bin/python3
import os
from PIL import Image

folder = './Results/'
resource = Image.open('Tiles0.bmp')
h, w = resource.size
PX = 32

for i in range(0, h, PX):
    for j in range(0, w, PX):
        box = (i, j, i + PX, j + PX)
        try:
            resource.crop(box).save(folder + str(i) + str(j) + ".png", "png")
        except:
            print("NISMAN!")
```

First problem is `h, w = resource.size`. [`Image.size`](https://pillow.readthedocs.io/en/4.2.x/reference/Image.html#PIL.Image.size) returns width, height. So that line should be `w, h = resource.size`.

Similarly, `resource.crop(box)` where `box = (i, j, i + PX, j + PX)`. [`Image.crop`](https://pillow.readthedocs.io/en/4.2.x/reference/Image.html#PIL.Image.Image.crop
) takes a (left, upper, right, lower)-tuple. After fixing problem one, it's giving it (upper, left, lower, right). I think it's clearer to use `i` for `w` and `j` for `h`.

The fixed code:
```python
#!/usr/bin/python3
from PIL import Image

folder = './Results/'
resource = Image.open('Tiles0.bmp')
w, h = resource.size # FIXED
PX = 32

for i in range(0, w, PX): # FIXED
    for j in range(0, h, PX): # FIXED
        box = (i, j, i + PX, j + PX) # FIXED
        resource.crop(box).save(folder + str(i) + str(j) + ".png", "png")
```

To verify, we can rebuild an image from the crops using this:
```python
from PIL import Image

folder = './Results/'
resource = Image.open('Tiles0.bmp')
w, h = resource.size
PX = 32

rebuilt = Image.new("RGB", (w, h), "black")

for i in range(0, w, PX):
    for j in range(0, h, PX):
        box = (i, j, i + PX, j + PX)
        im = Image.open(folder + str(i) + str(j) + ".png")
        rebuilt.paste(im, box)

rebuilt.save("rebuilt.png")
```
Putting Tiles0.bmp and rebuilt.png next to each other (and downsizing):
![image](https://user-images.githubusercontent.com/1324225/29741281-1c7a0e34-8a72-11e7-81d7-079861f46ce8.png)

**Comment by mratmartinez** [comment]
Thanks @hugovk  
I changed those things so many times that of course none of the results was the right one.

Sorry for the inconveniences.

**Comment by hugovk** [comment]
You're welcome. 

Some libraries do use (y, x) coordinates, like OpenCV, but not Pillow.
