### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'load'

### ISSUE THREAD

**Issue by oscar-rt** [python-pillow/Pillow#2720]
### What did you do?
I called this function:
`def compare():
    PIL.ImageChops.difference(image1, image2).getbbox() is None`

### What did you expect to happen?
I expected it to compare the two images and return a true or false

### What actually happened?
I got this error: 

> **Traceback (most recent call last):
>   File "D:/Projects/Python/Fproject.py/src/main.py", line 20, in <module>
>     PIL.ImageChops.difference(hspointer, currents).getbbox() is None
>   File "C:\Users\User\AppData\Roaming\Python\Python36\site-packages\PIL\ImageChops.py", line 101, in difference
>     image2.load()
> AttributeError: module 'PIL.Image' has no attribute 'load'**
> 

### What versions of Pillow and Python are you using?
I'm using Pillow 4.2.1 and Python 3.6.2

CODE BELOW:

```
import PIL.Image
import PIL.ImageGrab
import PIL.ImageChops

import math, operator

running = True

boxhs = (828, 0, 1920, 90)
hspointer = PIL.Image.open("homescreen.png")
currents = PIL.Image

def takeShot():
    currents = PIL.ImageGrab.grab(boxhs).save("screen_capture.png", "PNG")
takeShot()

hstry = hspointer.crop(boxhs)
hstry.save("try.png", "PNG")

def compare(image1, image2):
    PIL.ImageChops.difference(image1, image2).getbbox() is None

def mainloop():
    while(running):
        takeShot()
        if(compare(hspointer, currents)):
            break

mainloop()


```

Also I am using PyCharm Community Edition 2017.2.2 as my IDE

**Comment by wiredfool** [comment]
Your function has several issues:

1) it's not actually returning anything. It's doing an operation, and then since there's no return, it's returning None. However, that operation could be just equality, as Images implement a __eq__ method. i.e.:
```
if hspointer == currents:
  break
```

2) You've got confusion between global state and local variables. Try to avoid mutating global state (`currents`) from within a function. Return a value instead. Also note, the Image.save() method does not return anything, so assigning it to `currents` is probably not what you want to do. 

3) Hspointer is a `PIL.Image.Image` instance. Currents starts out as the `PIL.Image` module, which is not an image and does not have a load method.

**Comment by oscar-rt** [comment]
I see, thanks for the help! Hopefully this will help other noobies if they get the issue.
