### ISSUE TITLE
Affine transformation fill parameter seems to do nothing

### ISSUE THREAD

**Issue by Erotemic** [python-pillow/Pillow#2837]
I would like to use PIL to perform an affine warp on an image, but I want to specify a custom fill value for undefined pixels. The `transform` function seems to have a `fill=1` argument, but it is undocumented and looking further in the code it seems to be unused. 

Is there any way to get a custom fill value in an affine transform?

**Comment by sharkovsky** [comment]
I am also interested in this!

**Comment by wiredfool** [comment]
Internally, in `_imaging.c`, the `fill` parameter is passed in, but subsequent calls into the core transform routines set it to 1. In those routines, the fill parameter is a flag for `memset(0)` on the non-affected locations.  In theory, it should be possible to set this fill to some pixel value. 

I've got a test implementation in https://github.com/wiredfool/Pillow/tree/issue_2837

It extends the interface rather than repurposing the fill parameter, in case someone is using the fill parameter on an ImagingTransformHandler.
