### ISSUE TITLE
Image.fromarray silently fails with floating-point input

### ISSUE THREAD

**Issue by jakevdp** [python-pillow/Pillow#2856]
When passing a floating-point array to ``Image.fromarray``, the output does not match the input:

```python
from PIL import Image
import numpy as np
x = np.ones((100, 100), dtype='float64')
x[40:60, 40:60] = 0.0
Image.fromarray(x, mode='L')
```
![download](https://user-images.githubusercontent.com/781659/32795726-7287ef38-c921-11e7-9da8-15736ebd2d83.png)

This happens is because when ``mode`` is specified,  the array's bytes are passed directly to ``frombuffer`` without any type check: https://github.com/python-pillow/Pillow/blob/c82f9fe1bb963ab07f995282a097757bde8f2e0f/PIL/Image.py#L2394-L2438

It would be helpful for users if the dtype of the input were checked, and an appropriate warning or error raised.

I'm using Python 3.6.1 and PIL v4.2.1

**Comment by wiredfool** [comment]
My impression of this parameter (which, tbh, is not well documented) is that it's for overriding the mode that's detected from the dtype. Raising an error where it doesn't match is going to be problematical for the intended use case.  On the other hand, since it's assigned directly to the rawmode as well as the mode, there are only a handful of valid modes that will work, generally the ones where the mode and rawmode match in the unpackers table in `libImaging/Unpack.c`

**Comment by radarhere** [comment]
#4887 encountered this as well.
```python
import numpy as np
from PIL import Image

array = np.full((32,32,3),255)
Image.fromarray(array, "RGB")
```

**Comment by radarhere** [comment]
If you remove the `mode` parameter from the original post's `fromarray` call,
```python
from PIL import Image
import numpy as np
x = np.ones((100, 100), dtype='float64')
x[40:60, 40:60] = 0.0
im =Image.fromarray(x)
im.save("out.tiff")
```
then you get the expected result - [out.tiff.zip](https://github.com/python-pillow/Pillow/files/7587016/out.tiff.zip) 
(Here is it converted to PNG since GitHub won't allow TIFFs)
![out](https://user-images.githubusercontent.com/3112309/143002138-bd670fed-3a0b-4908-a49c-09f71af0c20d.png)

I'm going to suggest resolving this by just improving the documentation in #5849

**Comment by maoshi7** [comment]
```
from PIL import Image
import numpy as np

a = np.zeros((200,200))
a[0:2,0:2] = 1 
a[99:101,99:101] = 1
img = Image.fromarray(a,mode='L')
img1 = np.array(img)
```

I find that a is a matrix with lots of zeros and 8 ones at the right position, but img1 is a wrong matrix. Wrong numbers 240 and 63 appears at strange positions:
![image](https://github.com/user-attachments/assets/34ce219e-9fcb-42bf-afb1-e94cbd883301)
There is no warning, I didn`t understand why this change happened until I see this issue.
I would like to know What data types and ranges are required for the different modes of Image.fromarray? I don't see this in the official documentation of pillow, can someone tell me? Did I mislocate the official documentation? 
[https://pillow-docs-cn.readthedocs.io/zh-cn/latest/reference/Image.html#PIL.Image.fromarray](url)
Thanks!

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray is the official documentation.

The 'mode' parameter is optional. If you do not wish to tell Pillow to treat the data as a different mode, then you can just omit it.

You might also be interested in https://github.com/python-pillow/Pillow/blob/d66c51a35663247357bf6b625ef093df7ea12a45/src/PIL/Image.py#L3356-L3380

**Comment by maoshi7** [comment]
Thank you ! Do you mean that if I use img = Image.fromarray(a) instead of img = Image.fromarray(a,mode='L') , I will get correct results?

**Comment by radarhere** [comment]
I can't really say that without knowing the value of `a`, but I highly expect so, yes.

**Comment by maoshi7** [comment]
Thank you very very much. Although Python's documentation isn't as comprehensive as MATLAB's and bugs do occur from time to time, I believe it's the presence of enthusiastic individuals like you – who actively help others by answering questions and solving problems – that keeps Python thriving with such vibrant vitality!
