### ISSUE TITLE
Image thumbnail() after copy() performance

### ISSUE THREAD

**Issue by luigy-cz** [python-pillow/Pillow#2904]
Hi, I've noticed a huge performance difference when creating a thumbnail from a copied image:
`Image.open().copy().thumbnail()`
is many times slower than:
`Image.open().thumbnail()`
Tested on Python 3.4 & Pillow 4.3.0; Python 2.7 & Pillow 2.6.1

Example code:
```
from PIL import Image
import time

img = Image.open("test.jpg")
t = time.time()
img.thumbnail((200, 200), Image.ANTIALIAS)
print("%.3f sec" % (time.time()-t,))
img.save("thumb1.jpg")

img = Image.open("test.jpg").copy()
t = time.time()
img.thumbnail((200, 200), Image.ANTIALIAS)
print("%.3f sec" % (time.time()-t,))
img.save("thumb2.jpg")
```

With Python 3.4 & Pillow 4.3.0 the output is something like:
```
0.040 sec
0.167 sec
```
Python 2.7 & Pillow 2.6.1:
```
0.036 sec
0.719 sec
```
That's a huge performance difference. The result images looks the same even though they have little bit different byte size.
What is going on here?

**Comment by wiredfool** [comment]
Well, to put it simply, thumbnail cheats.  Primarily with jpgs.

Jpeg files are organized so that there are effectively lower res versions of the image early in the file, and later points in the file refine the details. If you're dramatically reducing the size of the image, you can only read and handle the first few K of the image, rather than the whole thing. 

Images that have been copied are fully in memory, so you're processing the entire image, and doing a fullsize-> thumbnail resize.

**Comment by luigy-cz** [comment]
Thank you for very prompt answer. I see your point. I would very much appreciate if there was a note somewhere in the documentation about this behavior. It could save someone a lot of computing time. My photo-processing app is now 5 times faster than before :)

**Comment by homm** [comment]
I believe this should be mentioned [there](https://pillow.readthedocs.io/en/4.3.x/reference/Image.html#PIL.Image.Image.copy). Something like this:

> The image will be fully decoded while copying.

**Comment by homm** [comment]
> That's a huge performance difference.

@luigy-cz If you really care about performance, probably you should look at [Pillow-SIMD](https://github.com/uploadcare/pillow-simd#pillow-simd).

**Comment by luigy-cz** [comment]
@homm Good point about Pillow-SIMD unfortunately I'm running on ARM (Raspberry Pi)
