### ISSUE TITLE
Feature Request: Change quality without save.

### ISSUE THREAD

**Issue by Hyperclaw79** [python-pillow/Pillow#2960]
There needs to be an option to change the quality of an image **before saving it**. Consider my use case:
`Compress the quality of a GIF.` 
What I can do is `save` the frame as `lower quality JPEG`s and again make a GIF out of them using `append_images`. 
However this involves costly `(IO operation * 2 * frames)`. 
What I would like to do is change the quality of each frame and store the frames as list elements which I can immediately use for `append_images`.

**Comment by wiredfool** [comment]
What is the ultimate objective you're tying to achieve here?

**Comment by Hyperclaw79** [comment]
@wiredfool since JPEG is a good compression for images, I'm trying to split a gif into frames, convert each frame to JPEG and recombine them.

Also, I tried this out and it turned out the absolute opposite. A 30MB file became 2GB.

**Comment by wiredfool** [comment]
I was wondering just how bad it would be, but I didn't expect quite that bad. 

Crunching a GIF is an interesting problem, there are likely many ways to do it but Pillow isn't going to be the best choice because it doesn't support the internal lossless GIF compression. (I don't know why, but I bet it dates to the LZW patent fight). 

Within the gif format, you can do things like crunch the palette to 64 colors or less. (and use compression). If you're not stuck to that format, you can go with something like MJPEG (which has iffy browser support) or one of the actual supported browser video formats.
