### ISSUE TITLE
5.1.1 release

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#3089]
* Build osx wheels with xcode 6.4, supporting older OSX versions. (https://github.com/python-pillow/Pillow/issues/3068) 
* Include #3067 ?
* ~Wheels for 3.7, if we can convince the pillow-wheels repo to do that easily? (https://github.com/python-pillow/Pillow/issues/3074)~

**Comment by wiredfool** [comment]
I'd appreciate any help on this.

**Comment by matthew-brett** [comment]
I believe it's dangerous to build 3.7 wheels before the official release, as the binary API may change.

**Comment by homm** [comment]
> Include #3067 ?

I'm for it. Compilation problems are that can be fixed in minor updates

**Comment by paregorios** [comment]
Respectfully, from the user gallery: I'd prefer to see Pillow 5.1.1 not get held up for Python 3.7 official release, which is iirc still a couple months away. Because #3068. Thanks.

**Comment by wiredfool** [comment]
Ok, #3067 and xcode6.4 wheels.

**Comment by hugovk** [comment]
I've done the first steps of https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#point-release on https://github.com/python-pillow/Pillow/tree/5.1.x:

---

## Point Release

Released as needed for security, installation or critical bug fixes.

* [x] Make necessary changes in ``master`` branch.
* [x] Update `CHANGES.rst`.
* [x] Cherry pick individual commits from ``master`` branch to release branch e.g. ``2.9.x``.
* [x] Check [Travis CI](https://travis-ci.org/python-pillow/Pillow) to confirm passing tests in release branch e.g. ``2.9.x``.
* [x] Checkout release branch e.g.:
```
    git checkout -t remotes/origin/2.9.x
```
* [x] In compliance with https://www.python.org/dev/peps/pep-0440/, update version identifier in `src/PIL/_version.py`
* [x] Run pre-release check via `make release-test`.
* [ ] Create tag for release e.g.:
```
    $ git tag 2.9.1
    $ git push --tags
```
* [ ] Create source distributions e.g.:
```
    $ make sdist
```
* [ ] Create [binary distributions](#binary-distributions)

---

Plus release notes. 

In https://github.com/python-pillow/Pillow/blob/5.1.x/docs/releasenotes/5.1.1.rst I put "... Xcode 6.4 to support at least 10.10 Yosemite" because it's not quite clear to me if 10.9 Mavericks is supported by Xcode 6.4, but we can change that if think it is.

---

Next up, resolve https://github.com/python-pillow/pillow-wheels/pull/84.

**Comment by homm** [comment]
Any plans for this?

**Comment by wiredfool** [comment]
yeah. go for it.

**Comment by hugovk** [comment]
https://github.com/python-pillow/pillow-wheels/pull/84 merged.

https://github.com/python-pillow/pillow-wheels has had three changes since last time: 
* (https://github.com/python-pillow/pillow-wheels/pull/84) Use Xcode 6.2 - needed
* (https://github.com/python-pillow/pillow-wheels/pull/85) Update multibuild - probably needed
* (https://github.com/python-pillow/pillow-wheels/pull/85) Update libwebp to 1.0.0

Is that last one a problem? libwep 1.0.0 has been updated in python-pillow/Pillow in master (https://github.com/python-pillow/Pillow/pull/3108) after 5.1.0. Should it also go into the 5.1.x branch?

**Comment by wiredfool** [comment]
I'd rather not push a new version of webp in a point release given that it's not a current issue we're fixing and we've got 0 experience with it so far.

**Comment by hugovk** [comment]
https://github.com/python-pillow/pillow-wheels/tree/5.1.x is the 5.1.0 release commit with just Xcode 6.4 and multibuild cherry-picked.

Building now, green so far: https://travis-ci.org/python-pillow/pillow-wheels/builds/371046996

I've done these next steps:

---

* [x] Create tag for release e.g.:
```
    $ git tag 2.9.1
    $ git push --tags
```
* [x] Create source distributions e.g.:
```
    $ make sdist
```
* [ ] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#binary-distributions)

---

I don't have upload rights for the last steps, @wiredfool please could you finish off?

**Comment by yarikoptic** [comment]
this release being released would be much appreciated so Pillow is usable again on elderly OSX releases.

**Comment by hugovk** [comment]
With 5.2.0 due out in two weeks (https://github.com/python-pillow/Pillow/issues/3154), TODO if 5.1.1 is not released:

* [ ] Delete [5.1.1 tag](https://github.com/python-pillow/Pillow/releases/tag/5.1.1)
* [ ] Roll back [5.1.x branch](https://github.com/python-pillow/Pillow/commits/5.1.x) to state of 5.1.0 release

**Comment by hugovk** [comment]
Let's release these in 5.2.0 (#3154) instead.
