### ISSUE TITLE
5.1.0 Checksum

### ISSUE THREAD

**Issue by jrood-nrel** [python-pillow/Pillow#3199]
Hello. I'm just curious if the checksum for 5.1.0 changed intentionally recently? I noticed this in our package manager project, Spack https://github.com/spack/spack/pull/8547 .

**Comment by wiredfool** [comment]
No, there’s been no updated release.

1) pypi will not allow a reupload of the same file name, so once it’s up, it’s immutable. 
2) it does not appear that there’s been a change to the pypi files since the upload. They publish a sha256 hash of the artifact.

I’d suggest that you check that hash, and the hash of the .tgz release on github for consistency against your original and new downloaded archives,

**Comment by hugovk** [comment]
The SHA256 of Pillow-5.1.0.tar.gz on https://pypi.org/project/Pillow/ is

`cee9bc75bff455d317b6947081df0824a8f118de2786dc3d74a3503fd631f4ef`

**Comment by jrood-nrel** [comment]
Great, thanks for the help! I'm getting `cee9bc75bff455d317b6947081df0824a8f118de2786dc3d74a3503fd631f4ef` for the archive we are set to download for pillow. I think that should be sufficient.

**Comment by adamjstewart** [comment]
Mystery solved. The checksum that was in the package is the checksum from the GitHub tarball, not the PyPI tarball.

**Comment by wiredfool** [comment]
Right, that tarball is created using sdist , not a tarball of the whole project.
