### ISSUE TITLE
Some error when writing to .tga

### ISSUE THREAD

**Issue by VarusEx** [python-pillow/Pillow#3257]
### What did you do?
Catch QGraphicsView and save this to .tga
### What did you expect to happen?
I expect save this image to .tga
### What actually happened?
I have error msg : 
`Traceback (most recent call last):
  line 396, in save
    image.save(qtimage, 'image.tga' )`

  `line 1939, in save <-- Pil file Image.py
    save_handler = SAVE[format.upper()]
KeyError: 'IMAGE.TGA'`
### What versions of Pillow and Python are you using?
Python 3.6 and Pillow 5.2.0 and PyQt5 version 5.10.1
Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
grab = self.graphicsView.grab() # Catch GraphicsView and return pixmap
pixmap = QPixmap.toImage(grab) # Change pixmap to QImage
            image = Image.fromqimage(pixmap) # Change QImage on Image
            qtimage = ImageQt(image) # Load ImageQT
            image.save(qtimage, 'image.tga' ) # Save file and crash
```

**Comment by radarhere** [comment]
If you look at the Image save method - https://pillow.readthedocs.io/en/5.2.x/reference/Image.html#PIL.Image.Image.save - `Image.save(fp, format=None, **params)` - the first argument is the filename, and the second is the format. So the KeyError would be because 'image.tga' is not an image format, it's a filename.

So I would change `image.save(qtimage, 'image.tga')` to `image.save('image.tga')`

**Comment by VarusEx** [comment]
That's stupid mistake issue to close :)
