### ISSUE TITLE
rgb2cmyk always sets K component to 0

### ISSUE THREAD

**Issue by czerwinskilukasz1** [python-pillow/Pillow#3258]
As can be seen at: https://github.com/python-pillow/Pillow/blob/ad36932ebbfa4f3a02a56fc15bf5079ede0abe7c/src/libImaging/Convert.c#L529
K component is always set to zero. 
While this results in a "correct" 4-dimensional result, this is not how the components should be computed, instead it should be:
R' = R/255
G' = G/255
B' = B/255

K = 255 * (1-max(R', G', B'))
C = 255 * ((1-R'-K) / (1-K))
M = 255 * ((1-G'-K) / (1-K))
Y = 255 * ((1-B'-K) / (1-K))
(based on https://www.rapidtables.com/convert/color/rgb-to-cmyk.html )

**Comment by radarhere** [comment]
K being set to zero is what is meant by the comment a few lines earlier, ['no undercolour removal'](https://github.com/python-pillow/Pillow/blob/ad36932ebbfa4f3a02a56fc15bf5079ede0abe7c/src/libImaging/Convert.c#L525) - https://www.reddit.com/r/photoshop/comments/6kr8m3/how_do_you_turn_off_undercolor_removal_when/djonlwu/

This has been the case since PIL.

https://en.wikipedia.org/wiki/CMYK_color_model#Conversion

> Since RGB and CMYK spaces are both device-dependent spaces, there is no simple or general conversion formula that converts between them.

So I don't think this is simply 'wrong' - it's a different way of performing the task. If someone thinks that this choice is not a good one, feel free to say.

It also looks like [`ImageCms.profileToProfile`](https://pillow.readthedocs.io/en/stable/reference/ImageCms.html) would allow you more control over this process.
