### ISSUE TITLE
yuv image tobytes still return rgb data

### ISSUE THREAD

**Issue by notedit** [python-pillow/Pillow#3268]
### What did you do?

i want to do a  rgb to yuv convert user PIL

### What did you expect to happen?

```
main_image = Image.open('640x480.jpg')
print(main_image.format,main_image.mode,len(main_image.tobytes()))
 
main_yuv_image = main_image.convert('YCbCr')
print(main_yuv_image.format, main_yuv_image.mode,len(main_image.tobytes()))

```

### What actually happened?

it just print 

```
JPEG RGB 921600
None YCbCr 921600
```
it seems that  yuv image still print  rgb data.

### What versions of Pillow and Python are you using?

```python
main_image = Image.open('640x480.jpg')
print(main_image.format,main_image.mode,len(main_image.tobytes()))
 
main_yuv_image = main_image.convert('YCbCr')
print(main_yuv_image.format, main_yuv_image.mode,len(main_image.tobytes()))

```

**Comment by radarhere** [comment]
Hi. For anyone else reading this, in your code, `main_image.tobytes()` is on the second line and the fourth line. As in, you presumably meant to have `main_image.tobytes()` on the second line and `main_yuv_image.tobytes()` on the fourth line. However, correcting that problem does not resolve this issue.

When you say that it still prints rgb data, are you just presuming this is the case because the bytes length is the same? If I use pixel access - https://pillow.readthedocs.io/en/5.2.x/reference/PixelAccess.html - to inspect the pixel values, I find -

```
px = main_image.load()
print(px[0, 0])
>>> (208, 232, 224)
 
main_yuv_image = main_image.convert('YCbCr')
px = main_yuv_image.load()
print(px[0, 0])
>>> (223, 128, 116)
```

So it looks like the values have changed to me. If you run this code and do not find that they are different, could you upload the image that you are converting?

**Comment by notedit** [comment]
yes, it's my typo,  the forth line is  `main_yuv_image.tobytes()`

i just print the pixel data,  they really changed.   but why  `tobytes()`  length  return the same length.

**Comment by radarhere** [comment]
Looking at https://github.com/python-pillow/Pillow/blob/master/src/libImaging/ConvertYCbCr.c#L338, the conversion just maps three unsigned 8-bit ints to three new unsigned 8-bit ints - R, G, B to Y, Cb, Cr. The values are different, but there is no need for more or less information to be stored at the end of the process.

**Comment by notedit** [comment]
yes,  i see,  but many other yuv lib do not like this form of yuv data.
