### ISSUE TITLE
Request: EPS file processing without ghostscript popup

### ISSUE THREAD

**Issue by spaceguns** [python-pillow/Pillow#3371]
Feature request if possible. Sorry if I am overlooking a solution to this.
Option to "silent mode" or suppress ghostscript command window for eps processing. If possible this should likely be the default behavior.

This code works correctly but causes a command window to pop up then quickly close for ghostscript. Makes my system a bit unusable for a while when it is processing lots of files.

```python
from PIL import Image
epsfile = 'file.eps'
img_obj=Image.open(epsfile)
img_obj.save('temp_test_output.jpg')
```

* OS: Windows 10
* Python: 3.6.0
* Pillow: 5.2.0
* Ghostscript: 9.25 (behavior also happened with 9.23)

**Comment by hugovk** [comment]
Please can you try out PR #3373?

Thanks.

**Comment by spaceguns** [comment]
That unfortunately did not work. However, I think I found a solution. I am really new to this and don't know my way around pulls/github. Could you check and see if this looks right/could be considered for adding input EpsImagePlugin.py?

Starting at line 143
`
        with open(os.devnull, 'w+b') as devnull:
            startupinfo = subprocess.STARTUPINFO()
            startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            subprocess.check_call(command, startupinfo=startupinfo, stdin=devnull, stdout=devnull)
`

**Comment by hugovk** [comment]
@spaceguns Here's a PR based on that: https://github.com/python-pillow/Pillow/pull/3378. Please could you give it a whirl?

**Comment by radarhere** [comment]
Just a note.

[The documentation on STARTF_USESHOWWINDOW](https://docs.python.org/2/library/subprocess.html#subprocess.STARTF_USESHOWWINDOW) reads 'Specifies that the STARTUPINFO.wShowWindow attribute contains additional information.'

This was initially surprising, since we're not providing `wShowWindow`. However, ['this attribute can be any of the values that can be specified in the nCmdShow parameter for the ShowWindow function'](https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO.wShowWindow), and [SW_HIDE is zero](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showwindow). So I guess we're using default behaviour.

**Comment by spaceguns** [comment]
> @spaceguns Here's a PR based on that: #3378. Please could you give it a whirl?

It works. No command window shows and processes as expected on windows.

**Comment by user2589** [comment]
@spaceguns,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/python-pillow/Pillow/issues/3371)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!
