### ISSUE TITLE
Incorrect output when converting greyscale to bilevel

### ISSUE THREAD

**Issue by Raptoer** [python-pillow/Pillow#3394]
### What did you do?
converted test image to bilevel
### What did you expect to happen?
Most of the image should be black, only the very bottom should be white
### What actually happened?
half is black, half is white
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]
* Pillow: 5.3.0

Documentation states 
If dither is NONE, all non-zero values are set to 255 (white)

included image and code show that this is not the case, instead any value under 128 becomes white while any value over 128 becomes black.
Considering the behavior of other programs, it is likely that the documentation is wrong rather than the behavior.

[graydient.zip](https://github.com/python-pillow/Pillow/files/2441111/graydient.zip)

Files have been zipped due to github not accepting bmp images.

```python
Image.open("input.bmp").convert("1", dither=Image.NONE).save("output.bmp")
```

**Comment by hugovk** [comment]
The [docs](https://pillow.readthedocs.io/en/5.3.x/reference/Image.html?highlight=convert#PIL.Image.Image.convert) say:

> The default method of `convert`ing a greyscale (“L”) or “RGB” image into a bilevel (mode “1”) image uses Floyd-Steinberg dither to approximate the original image luminosity levels. If dither is NONE, all non-zero values are set to 255 (white). 

Looks like the conversion is done in `tobilevel` which indeed has a cutoff at 128:

https://github.com/python-pillow/Pillow/blob/3437d5fcb4880f622f72f313ecc764e140f13dfb/src/libImaging/Convert.c#L1203-L1285

This hasn't really changed since the PIL->Pillow fork:

https://github.com/python-pillow/Pillow/blame/master/src/libImaging/Convert.c#L1203-L1285

Those docs were last edited in https://github.com/python-pillow/Pillow/issues/407 to correct the bit about FLOYDSTEINBERG being used by default, but didn't adjust this bit.

Please could you send a PR to correct the docs? It's from the docstring:

https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L856
