### ISSUE TITLE
Some missing mime types

### ISSUE THREAD

**Issue by pirate486743186** [python-pillow/Pillow#3531]
for bmp:
image/x-bmp
image/x-ms-bmp

for ico:
image/icon
image/x-ico
image/ico
text/ico
application/ico
image/x-win-bitmap
image/vnd.microsoft.icon

for pcx:
image/vnd.zbrush.pcx

for ppm:
image/x‑portable‑bitmap
image/x‑portable‑graymap
image/x-portable-pixmap
image/x-portable-anymap

for tga:
image/x-targa

reference:
https://en.wikipedia.org/wiki/BMP_file_format
https://en.wikipedia.org/wiki/ICO_(file_format)
https://en.wikipedia.org/wiki/Pcx
https://en.wikipedia.org/wiki/Netpbm_format
https://en.wikipedia.org/wiki/.tga

there's also "image/x-ms-bmp"
they are results for it in search engines

**Comment by radarhere** [comment]
BMP already has a mime type.
ICO, PCX and TGA are given one each in #3520
I've created PR #3688 for the PPM mime types.

The remainder of this issue is about adding mimetypes that are synonymous to the existing ones - for example, I don't think there is any difference between 'image/bmp' and 'image/x-bmp'. Multiple synonymous mimetypes is not something that can be done with the existing API of Pillow. `Image.MIME` is a dictionary, and returns one mimetype for each format. `ImageFile.get_format_mimetype()` also only returns one mimetype for an image. What I'm saying that I don't think we need to add these additional mimetypes out of any sense of completeness, because we would have to add a new function to list the possible mime types of an image, or a format, or both. Are you requesting that?

**Comment by pirate486743186** [comment]
No, that's ok, no need to do anything that complicated.

**Comment by radarhere** [comment]
Both of those PRs have now been merged.
