### ISSUE TITLE
Suspicious expression in C code

### ISSUE THREAD

**Issue by cgohlke** [python-pillow/Pillow#3546]
Is the expression [`if (h->keyDestroyFunc || h->keyDestroyFunc) {`](https://github.com/python-pillow/Pillow/blob/master/src/libImaging/QuantHash.c#L317) in `QuantHash.c` correct? Should it be `if (h->keyDestroyFunc || h->valDestroyFunc) {`?

**Comment by hugovk** [comment]
Well it's been there since at least [PIL 1.1.1](https://github.com/hugovk/PIL/blame/master/libImaging/QuantHash.c#L345) (released in 2000)!


Sounds reasonable, it calls `_hashtable_destroy`:

https://github.com/python-pillow/Pillow/blob/7447b44edfe152a8c6857f417f85219a3c450625/src/libImaging/QuantHash.c#L317-L319

Which calls both `h->keyDestroyFunc` and `h->valDestroyFunc`, if they exist:

https://github.com/python-pillow/Pillow/blob/7447b44edfe152a8c6857f417f85219a3c450625/src/libImaging/QuantHash.c#L65-L72

**Comment by hugovk** [comment]
See PR #3550 to fix it.

Or PR #3551 to remove it and some other functions, as they're never called, and aren't exposed to the Python layer.
