### ISSUE TITLE
PyInstaller 'ValueError: unknown file extension: .jpg'

### ISSUE THREAD

**Issue by zaingithub** [python-pillow/Pillow#3675]
Hello, i am trying to make executable (.exe) using pyinstaller and include the Pillow in it.

When i am on development (not running the exe yet), i can save image in JPEG format, but when it already in exe (using pyinstaller), it always throw and exception : 

```
Traceback (most recent call last):
  File "site-packages\PIL\Image.py", line 1974, in save
KeyError: '.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "library\__uploader_class.py", line 43, in add_image_watermark
  File "site-packages\PIL\Image.py", line 1976, in save
ValueError: unknown file extension: .jpg
```

Why there is no JPEG format on SAVE.keys when the Pillow in exe ?

I Try on : 
* OS: Windows 10
* Python: 3.6 version
* Pillow: 5.4.1

**Comment by radarhere** [comment]
Are you able to create an example of this situation out of your code? Not uploading your entire program, but just a small self-contained script that can show the error.

Or, if you could try running the following code when in development and when compiled into an executable, and let us know what happens -
```python
from PIL import Image
print(Image.core.jpeglib_version)
```

**Comment by radarhere** [comment]
Also, lines 1974-1976 in Pillow 5.4.1 are

https://github.com/python-pillow/Pillow/blob/f38f01bbe3a0a9f49ce592c86ff20c01c9655133/src/PIL/Image.py#L1974-L1976

So this is not actually to do with the `SAVE` dictionary, but instead the `EXTENSION` dictionary.

The issue likely has little to do with your code that calls Pillow, and is more likely due to just the script that calls pyinstaller. Are you able to provide that?

**Comment by radarhere** [comment]
I was able to get pyinstaller working and saving a JPG file on macOS. I'm now inclined to think that this is something specific to your installation. How did you install Pillow?

**Comment by radarhere** [comment]
I wonder if this is related to #3381

**Comment by yarin177** [comment]
same problem It worked fine once but now it started to throw exceptions every time..

**Comment by radarhere** [comment]
I also wonder if this is at all related to #5034 - which concluded that zlib was missing. Are there any missing dependencies here?

**Comment by radarhere** [comment]
I'm able to successfully [use a PyInstaller executable to save a JPEG file on Windows](https://github.com/radarhere/Pillow/commit/bfcacef611ecc9b1fc6e23c6001ab8d73d55b80f) - https://github.com/radarhere/Pillow/runs/1951069289

Due to lack of response, closing. Feel free to comment with more information and this can be re-opened.
