### ISSUE TITLE
python setup.py tries to resolve always to Pillow 6.0 although not necessary

### ISSUE THREAD

**Issue by andrematzke** [python-pillow/Pillow#3792]
### What did you do?
tried to install via pip3 or python setup.py a python-program with dependencies to pillow
`Searching for pillow>=3.3.0
Reading https://pypi.python.org/simple/pillow/
Downloading
https://files.pythonhosted.org/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046efaf8/Pillow-6.0.0.tar.gz#sha256=809c0a2ce9032cbcd7b5313f71af4bdc5c8c771cb86eb7559afd954cab82ebb5
Best match: Pillow 6.0.0`

### What did you expect to happen?
that it is fine with my via pacman installed python3-pillow 5.0.0.1 and links against this.

### What actually happened?
`Best match: Pillow 6.0.0`
Due to this conclusion of python-setuptools, which I do not know why I it chooses to ignore my version, it downloads the 6.0.0 and tries to compile it. 
It soon fails with dependencies to a missing library called jpeg, so it says.
100,000 of webpages found via google are describing the same problem.. So I am not alone, why I hope you acknowledge that maybe the user experience with installing your great word can still be improved. 
But most of them, which had the same problem, are able to fix the problem by themselves with for instance an install via `apt-get libjpeg-dev` package or similar within their Ubuntus, Suses, Redhat-Fedoras. 
Such or similar package pacman does not provide. Via pacman the libjpeg library is in the package libjpeg-turbo 1.5.2.1. 
So why your configure-make process is of the opinion, that the library or its devel ingredients are missing ?
homebrew people (like me on my Mac) have the same issue with zlib, since homebrew repos does not provide a zlib package anymore. Almost all other can handle with the lzlib package, only pillow does not.
For both your documentation supposedly claim, I can switch them "off" (Obviously there is a first step in recognizing a problem). But this "global option" parameters (--global-option='disable-jpeg', --global-option='disable-zlib') are not recognized by the pip-egg. And left users behind with questions due to a lot of websites and forums.

### What are your OS, Python and Pillow versions?
msys2 20180531, python3.6.3, python3-pillow 5.0.01

Best Regards,
Andre

**Comment by radarhere** [comment]
I'm going to break this down into four different problems -
1. pip is not recognising that pacman installed python3-pillow 5.0.0.1 satisfies 'pillow>=3.3.0'
2. You can't install libjpeg with pacman. and are then asking why libjpeg-turbo is not accepted by Pillow as a substitute for libjpeg
3. You are asking why lzlib is not accepted by Pillow as a substitute for zlib on macOS
4. You've having problems applying the disable options through pip

So here are some starting comments -
- 1 - To be clear, there is no Pillow 5.0.0.1. You're presumably talking about 5.0.0-1, just as the Pillow 6.0.0 is currently listed as 6.0.0-1 - https://www.archlinux.org/packages/community/x86_64/python-pillow/.
- 2 - We use pacman on msys2 in one of our AppVeyor builds, and we install mingw-w64-i686-libjpeg-turbo to match the libjpeg requirement - https://github.com/python-pillow/Pillow/blob/3d2c52f8c6e3d7ced79add730adadbf5f3e64f0e/winbuild/appveyor_install_msys2_deps.sh - so in theory, this should be working
- 4 - It would be good if you could provide some links to where you have found this problem reported, so that we could get a better understanding of the problem.

**Comment by radarhere** [comment]
@andrematzke do you have further thoughts on this issue based on my reply?

**Comment by radarhere** [comment]
Closing, due to lack of a response. Feel free to comment again, and this can be re-opened.
