### ISSUE TITLE
Reading MakerNotes EXIF data in Panasonic Lumix images

### ISSUE THREAD

**Issue by CodeDrome** [python-pillow/Pillow#3852]
### What did you do?

```python
exif_data_PIL =  image._getexif()
print(exif_data_PIL[37500]) # 37500 is tag for MakerNotes
```

### What did you expect to happen?
Print "Panasonic\0\0\0"
as per https://www.exiv2.org/makernote.html

### What actually happened?
Expected output plus approx 100000 extra bytes

### What are your OS, Python and Pillow versions?

* OS: Linux Mint 18.1
* Python: 3.7
* Pillow: 6.0.0

Sample image P1000031.jpg here
https://github.com/CodeDrome/image-histograms-python

**Comment by radarhere** [comment]
The link you have provided lists "Panasonic\0\0\0" as the 'Header'. This is the start of the value. As you seen in the 'Format' column, the rest of the tag is IFD, standing for Image File Directory. Elsewhere in that link states that 'makernotes may contain information about the lens used, contrast, saturation and sharpness settings, image quality settings, etc'. So https://www.media.mit.edu/pia/Research/deepview/exif.html#APP1 has an example of Olympus makernote data, starting with 'OLYMP\0' and then the subsequent data.

If there is something specific that you are after, feel free to let us know, but otherwise, this is not a bug.

**Comment by CodeDrome** [comment]
Thank you for your reply. There is nothing human-readable in all that data and it is evidently in a manufacturer-specific format. My first assumption was that the _getexif method was running past some end of field flag.

I wonder how Panasonic finds so much data to record on just one image!
