### ISSUE TITLE
from PIL import Image causes ImportError - only in crontab

### ISSUE THREAD

**Issue by jshumphrey** [python-pillow/Pillow#3891]
### What did you do?
Ran a script in a crontab with the line `from PIL import Image`

### What did you expect to happen?
Successful module import, as happens when I run the script from the command line

### What actually happened?
    Traceback (most recent call last):
        File "submissions.py", line 7, in <module>
            from PIL import Image
        File "/usr/lib/python3/dist-packages/PIL/Image.py", line 53, in <module>
            from PIL import _imaging as core
        ImportError: cannot import name '_imaging'

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 14.04.5 LTS
* Python: 3.5.2
* Pillow: 6.0.0

Pillow was installed with `sudo python3.5 -m pip install pillow`. `python3.5 -m pip freeze` does not report an installation of PIL, nor does `sudo python3.5 -m pip freeze` nor does my package manager.

The script is being run in the crontab with identical syntax to how it's being run in the command line.

Things I've tried: 
- https://stackoverflow.com/questions/25340698/importerror-cannot-import-name-imaging
- https://stackoverflow.com/questions/26505958/why-cant-python-import-image-from-pil/31728305
- Uninstalling and reinstalling Pillow

**Comment by radarhere** [comment]
This is one of those situations that is harder to debug remotely, so bear with me. In my thinking, the difference when running from cron is the user that is running the script, and the environment variables. Here are some ideas for figuring this out a bit more, take from this what you will -
- Figure out what user is cron is being run as, likely root, and then switch to that user's environment, and try the command then. This should at least determine if the problem is cron somehow, or the user's environment.
- Run `python -E` and try importing. This will ignore all PYTHON* environment variables, which might conceivably be the problem.
- Depending on your setup, you might want to install Pillow as the user that is running cron. Maybe this is a permissions issue?
- Run the command `env` as your working user and the cron user, and see if there are any relevant differences in the environment variables.

**Comment by radarhere** [comment]
@jshumphrey did you make any progress with this?

**Comment by jshumphrey** [comment]
The issue seems to be resolved. I'm not sure what caused the resolution,
but I don't see any further issue here.
