### ISSUE TITLE
ImageStat module incompatibility with color channels having range > 256

### ISSUE THREAD

**Issue by vasudevvv** [python-pillow/Pillow#3958]
Recently a user names **Cecilia** asked a [question](https://stackoverflow.com/questions/56843624/why-is-imagestat-returning-incorrect-statistics-for-signed-integer-images-mode) on StackOverflow stating:-

> Why is ImageStat returning incorrect statistics for signed integer images (`mode='I'`)?

I was the one who answered the question, and added a little **PS** in the end, for the OP to follow. But it seems like OP didn't. Anyways.

The question asked, 'why doesn't `ImageStat`of **PIL** give the same results as the `Imagestat` from `Numpy` or `Matlab` (Matplotlib)'. My answer is quite self explanatory, on what I observed in the module.

Let me reiterate what i stated there:-

> Upon doing Source Code Analysis of ImageStat module, i came to know that the module is specifically built to deal with images having 0 ≤ sample space > 256, or images having pixel values in the range (0 ≤ value ≤ 255).

Module `ImageStat` is incompatible, if the single channel value of a pixel exceeds 255 (Like in case of Signed integer color mode). But there doesn't exists any mention of this in the PIL documentation. So, I would request you add this info in the description of `ImageStat` module in the upcoming PIL documentations.

Secondly, the module is error prone, i.e. it doesn't check the mode of the image before doing any processing over it, so if the image mode is a `RGB` or `L` (greyscale) it works fine, but if the image mode is `I` it works, but produces undesirable results (more to this in my answer on StackOverflow). So, I would request to add some detection mechanism inside the module too, so that if a user still tries to pass in a incompatible image, they receive a error message stating the reason (rather then throwing incorrect results, and confusing the user).

**Comment by radarhere** [comment]
The root of the problem is that `im.histogram()` returns 256 bins per channel, even for ``I`` mode images.

Even though there isn't an individual bin for each pixel value, making the results more rough than they could, I think ImageStat could still allow useful analysis to be performed on ``I`` mode images.

I've created PR #6106 to document this in Image.py, and added a note in ImageStat about it.

You might suggest that an alternative strategy could be to raise an error and force the user to manually convert the image to a different mode before trying again, to make crystal clear what is happening. However, Pillow doesn't currently scale values when converting.
```pycon
>>> from PIL import Image
>>> im = Image.new("I", (1, 1), 300)
>>> im.convert("L").load()[0, 0]
255
```
