### ISSUE TITLE
CMYK file draw text cannot set color

### ISSUE THREAD

**Issue by 007gzs** [python-pillow/Pillow#4010]
### What did you do?
draw text to cmyk file with color
### What did you expect to happen?
the text color is same as my fill param
### What actually happened?
the text color has always been black
### What are your OS, Python and Pillow versions?

* OS: window7 
* Python: 2.7.5
* Pillow: 6.1.0

```python
from PIL import Image, ImageDraw
im = Image.open("in.jpg")
draw = ImageDraw.Draw(im)
draw.text((0,0), 'test', fill=(255, 255, 255))
draw.text((0,10), 'test', fill=(0, 0, 0))
draw.text((0,20), 'test', fill=(255, 0, 0))
draw.text((0,30), 'test', fill=(0, 255, 0))
draw.text((0,40), 'test', fill=( 0, 0, 255))
im.save("out.jpg")

```

[file.zip](https://github.com/python-pillow/Pillow/files/3466392/file.zip)

**Comment by radarhere** [comment]
The problem is that you are using RGB values to try and fill a CMYK image. So if instead of red green and blue values, I input cyan, magenta, yellow and key values -

```python
from PIL import Image, ImageDraw
im = Image.open("in.jpg")
draw = ImageDraw.Draw(im)
draw.text((0,0), 'test', fill=(70, 20, 0, 40))
draw.text((0,10), 'test', fill=(70, 40, 70, 40))
draw.text((0,20), 'test', fill=(0, 105, 80, 80))
draw.text((0,30), 'test', fill=(45, 5, 100, 100))
draw.text((0,40), 'test', fill=(0, 0, 80, 20))
im.save("out2.jpg")
```

I get -

![out](https://user-images.githubusercontent.com/3112309/62455279-571f1b80-b7b9-11e9-9352-afed3d3c7cd7.jpg)

Also, while not relevant to your question, be aware that in 2020, Pillow will no longer support Python 2.7.

**Comment by 007gzs** [comment]
thank you
