### ISSUE TITLE
Image.transpose doesn't update exif? Image.rotate deletes exif?

### ISSUE THREAD

**Issue by liavkoren** [python-pillow/Pillow#4124]
### What did you do?

Loaded [this image](https://user-images.githubusercontent.com/5854101/66331688-a05b2b00-e922-11e9-8f66-184d6b67fd30.jpg) [[Originally from flickr](https://live.staticflickr.com/1204/1090235720_1f7e90e951_o_d.jpg)] which contains Exif information, including the orientation tag into an `PIL.Image` and called `image.transpose` as well as `image.rotate`. 

### What did you expect to happen?
I expected the exif orientation tag to be updated with the new orientation.

### What actually happened?

`Image.transpose` doesn't seem to update exif.
`Image.rotate` seems to delete exif.

### What are your OS, Python and Pillow versions?

* OS: OS X 10.16.6
* Python: 2.7.10
* Pillow: 6.0.0

```python
# TEST_FILE_PATH here is the image from flickr on my local file system:
In [90]: image = Image.open(open(TEST_FILE_PATH))  
In [91]: print(image.getexif()[0x0112])
1
In [92]: image = image.transpose(Image.ROTATE_90)
In [93]: print(image.getexif()[0x0112])
1
In [94]: image = image.rotate(90)
In [95]: print(image.getexif()[0x0112])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-95-627080b70c8f> in <module>()
----> 1 print(image.getexif()[0x0112])

/Users/liavkoren/Envs/suicidegirls/lib/python2.7/site-packages/PIL/Image.pyc in __getitem__(self, tag)
   3174
   3175     def __getitem__(self, tag):
-> 3176         return self._data[tag]
   3177
   3178     def __contains__(self, tag):

KeyError: 274

In [96]: image.getexif().items()
Out[96]: []
```

**Comment by radarhere** [comment]
Hi. I need to explain how Pillow uses EXIF orientation.

Pillow does not automatically apply the EXIF orientation tag. So if an image file has upside down image data, but with an EXIF orientation tag of 3 to make it right side up, Pillow reads that as an upside down image. The tag data is also read, but that does not interact with the image data unless the user causes it to.

So in the world of Pillow, rotating or transposing an image changes the image data. The EXIF orientation tag hasn't been applied, so it doesn't quite make sense for it to be given a new value.

You may be interested in `ImageOps.exif_transpose` - https://github.com/python-pillow/Pillow/blob/127b3221947f31e9dc869870cd1ec0fbae5da3b3/src/PIL/ImageOps.py#L527 This is a method that transposes an image according to its EXIF orientation tag. With it, you can open an image, apply the orientation, and then move on.

**Comment by liavkoren** [comment]
Thanks for the fast response, @radarhere. I guess if the intention is to have one or more methods that manipulate the image and the exif tag in synchrony vs methods that don't, that makes sense, altho my intuition about this is that the methods should be symmetrical, or that transpose itself should just take an `update_exif` arg, which if true would then apply the same transform to the exif tag.

Short of that, personally, I would have found mention of the exif issue useful in the docs. I don't know if I have the bandwidth to write a PR updating the code, but if you folks would like a documentation PR to address some of this, I could add a few words on this issue. 

Deleting the exif info completely when you rotate an image seems like a completely different issue. Is *that* intended behavior?

**Comment by radarhere** [comment]
I've created PR #4128 to change `rotate` so that the EXIF data is no longer removed. If the PR is merged, it will be a part of Pillow 7.0.0 when it is released on January 1.

**Comment by radarhere** [comment]
If you would like a workaround until then, you can manually copy the image info -
```python
from PIL import Image
im = Image.open(open(TEST_FILE_PATH))
new_im = im.rotate(90)
new_im = im.info.copy()
```

**Comment by radarhere** [comment]
There is still some confusion here, so please bear with me as I try to speak clearly.

The orientation tag is not a comment on which way the image data happens to be facing. It is an instruction on which way to orient the image data so that it is seen as intended. It is not an absolute measure, it is a relative one - when the image is read, this is the transformation to be applied afterwards.

As far as I can see, one would only ever need to change either the EXIF orientation tag OR the image data itself. They do not need to be changed both at once. If I were to rotate the image data by 90 degrees, and then after that change the EXIF orientation tag to also rotate it 90 degrees, would created a combined effect of 180 degrees.

Since Pillow does not automatically transform the image data according to the orientation tag, `ImageOps.exif_transpose` exists to apply the transformation and then delete the orientation tag afterwards, since the image is now naturally oriented.

If you're interested in changing the EXIF data, you are on the right path with `getexif()`.

If you are interested in changing the image data, `rotate` and `transpose` will do the job.

All of that said, I think that the question of 'Why is Pillow showing the image from my camera the wrong way around?' is a basic one, so I've created #4132 to add a note to the documentation.

**Comment by liavkoren** [comment]
> The orientation tag is not a comment on which way the image data happens to be facing. It is an instruction on which way to orient the image data so that it is seen as intended. It is not an absolute measure, it is a relative one - when the image is read, this is the transformation to be applied afterwards.

What if I apply a transform based on the exif and then write the image to disk?

**Comment by radarhere** [comment]
Using images from the Pillow test suite -
```python
from PIL import Image, ImageOps
im = Image.open("Tests/images/hopper_orientation_3.jpg")
print(im.getexif()[0x0112])  # 3, as the filename implies
im.save("out_withoutexif.jpg")  # Saved as an upside down image, because the EXIF was not applied and the EXIF was not saved

im = Image.open("Tests/images/hopper_orientation_3.jpg")
im = ImageOps.exif_transpose(im)
im.save("out_withexiftranspose.jpg")  # Saved right side up, because the EXIF has been applied

im = Image.open("Tests/images/hopper_orientation_3.jpg")
exif = im.getexif()
im.save("out_withexiftag.jpg", exif=exif)  # Saved as an upside down image, but the EXIF orientation tag has also been saved, meaning that viewers will show this as being right side up

im = Image.open("Tests/images/hopper.jpg")
im.save("out_normal.jpg")  # Just to demonstrate that it is right side up

im = Image.open("Tests/images/hopper.jpg")
im = im.rotate(180)
print(im.getexif().get(0x0112))  # None, because there is no orientation that needs to be applied to the image
im.save("out_normal_rotated.jpg")  # Saved as an upside down image

im = Image.open("Tests/images/hopper.jpg")
exif = im.getexif()
exif[0x0112] = 3
im.save("out_normal_exifrotated.jpg", exif=exif)  # Saved as an upside down image, because although the image data is still upright, the orientation tag tells viewers to turn it upside down afterwards
```

**Comment by liavkoren** [comment]
Okay. Thank you for clarifying. : )

**Comment by mallniya** [comment]
Sorry to unearth this, but whether I deeply misunderstand meaning of this thread or it's broken again.
Following @radarhere last comment I haven't found an actual answer to the topic of an issue, that is:
```
im = Image.open("Tests/images/hopper_orientation_3.jpg")
im = ImageOps.exif_transpose(im)
im.save("out_withexiftranspose.jpg")  # Saved right side up, because the EXIF has been applied
```
when the question was:
> Image.transpose doesn't update exif? Image.rotate deletes exif?

What I mean is that using 9.2.0 now I see the following behavior (continuing code above):
```
im = Image.open("out_withexiftranspose.jpg")
print(im.getexif())
```
resulting in `{}`, which means the answer is "deletes exif". As @liavkoren mentioned, it's useful to at least have something like `update_exif` for `transpose` (meaning deletion of Orientation and saving other exit fields), because I believe, that if your intention was to just rotate an image, then lost of every other exif fields except Orientation is not what you wanted.

So my question is: was this behavior intentional or is it a bug? I have no problem with use of `image.save(...exif=exif)`, but it seems to be a little bit tedious.

**Comment by radarhere** [comment]
Since #4128, `im.rotate` should no longer delete EXIF data.

`im.transpose` does not change the the EXIF data, because it is changing the underlying image data.

> one would only ever need to change either the EXIF orientation tag OR the image data itself. They do not need to be changed both at once. If I were to rotate the image data by 90 degrees, and then after that change the EXIF orientation tag to also rotate it 90 degrees, it would create a combined effect of 180 degrees.

To be clear - `im.transpose` and `ImageOps.exif_transpose` are two different methods.

`ImageOps.exif_transpose` does delete EXIF orientation, intentionally. It is taking the EXIF orientation, and applying it to the image data. `exif_transpose` does not intend to alter the orientation of the image, but only to move the orientation information from the EXIF data and into image data itself.

`ImageOps.exif_transpose` should not delete the rest of the EXIF data. Here is a demonstration with a different test image to show that the rest of the data is still present afterwards.

```python
from PIL import Image, ImageOps

im = Image.open("Tests/images/empty_gps_ifd.jpg")
print(im.getexif())  # {256: 4000, 257: 3000, 34853: 752, 296: 2, 34665: 216, 271: 'Xiaomi', 272: 'Redmi Note 9S', 274: 6, 306: '2020:07:27 14:46:48', 531: 1, 282: 72.0, 283: 72.0}

im = ImageOps.exif_transpose(im)
print(im.getexif())  # {256: 4000, 257: 3000, 34853: 752, 296: 2, 34665: 216, 271: 'Xiaomi', 272: 'Redmi Note 9S', 306: '2020:07:27 14:46:48', 531: 1, 282: 72.0, 283: 72.0}
```

If you are saying that `im.save()` deletes EXIF data, but `im.save(..., exif=exif)` does not, then yes, that is true. Pillow values backwards compatibility, so to change the behaviour of `im.save()` to do otherwise could surprise a lot of users.

**Comment by mallniya** [comment]
Thanks for such elaborated answer.
> Since https://github.com/python-pillow/Pillow/pull/4128, im.rotate should no longer delete EXIF data.

Well, it really does, though I was confused that `im.save()` does not consider this updated EXIF info if not retrieving it first with `im.getexif()` and then manually set `exif=exif` -- and though it's for good sake of compatibility, it's odd at first. It's just that I did check EXIF after saving without set exif for saving.

But there is another thing: if Rotation EXIF field equals 1 -- then it wouldn't get deleted by `exif_transpose()`. This is inconsistent and obscure, docs does contain no info regarding this. Use case for this is to determine if this exactly image was `exif_transpose`d  or not, working only in cases when Rotation is not 1. Manually manipulating EXIF is an acceptable simple option, though I suppose, that `exif_transpose()` was made exactly to not doing such manipulation.

**Comment by radarhere** [comment]
> Well, it really does

That is not what I see. Could you provide an example?

```python
from PIL import Image, ImageOps

im = Image.open("hopper_orientation_3.jpg")

print(im.getexif()) # {274: 3}

im = im.rotate(90)
print(im.getexif()) # {274: 3}
```

> Use case for this is to determine if this exactly image was `exif_transpose`d or not, working only in cases when Rotation is not 1

The image might not have EXIF orientation data to begin with though. So if you're looking at the image afterwards and declaring that it was transposed because it doesn't have orientation data, then that might not be true.

And if you say that you were checking that it had orientation data before passing it to `exif_transpose()`, then couldn't you also check if that orientation was 1 at the same time?

**Comment by radarhere** [comment]
> But there is another thing: if Rotation EXIF field equals 1 -- then it wouldn't get deleted by `exif_transpose()`. This is inconsistent and obscure, docs does contain no info regarding this.

I've created PR #6476 to document the behaviour.

**Comment by mallniya** [comment]
> That is not what I see
oh, this is misunderstanding, what I meant is that `exif_transpose` really does what you have in the example.
> The image might not have EXIF orientation data to begin with though. So if you're looking at the image afterwards and declaring that it was transposed because it doesn't have orientation data, then that might not be true.
Agree.
> And if you say that you were checking that it had orientation data before passing it to exif_transpose(), then couldn't you also check if that orientation was 1 at the same time?
Also True, guess it's just the case when "my defaults" deviate from "we learn that from mass experience default", though with my question I supposed "my defaults" just could have been overlooked and better fit to the mass-case. I perfectly able to check Rotation is 1, no problem with that.

Thanks again)
