### ISSUE TITLE
Converting png from PIL to numpy corrupts RGBA data

### ISSUE THREAD

**Issue by TensorTom** [python-pillow/Pillow#4246]
**Linux
Python 3.8
PIL 1.1.6**

I'm trying to code a captcha system. To do this, I need to load a random png from disk, add some random pixels to it, and then return it via `io.BytesIO()` so that aiohttp can serve it via my route. To that end, I try this:

```python
async def gen_captcha():
    rand_captcha = randint(0, len(captcha_files)-1)
    captcha_file = captcha_files[rand_captcha]['file']
    captcha_name = captcha_files[rand_captcha]['name']
    captcha_path = str(Path().absolute())+'/auth/img_captchas/'+captcha_file
    img = cv2.imread(captcha_path)

    img = np.array(255*img, dtype='uint8')
    h, w = img.shape[:2]
    img = np.dstack((img, np.zeros((h,w),dtype=np.uint8)+255))

    img = random_noise(img, mode='s&p', amount=0.001)
    img = (img*255).astype(np.uint8)
    img = Image.fromarray(img, 'RGBA')

    fp = io.BytesIO()
    img.save(fp, format="png")
    content = fp.getvalue()

    return content
```

I thought maybe I needed uint16 or uint32 to store more color information or something but if I switch to either, the image goes blank. I'm out of my depth in this error as far as these RGBA arrays go.

Related stack question: https://stackoverflow.com/questions/59162727/python-add-noise-to-image-breaks-png

**Comment by radarhere** [comment]
Hi.

The reason that your colors are swapped around is because OpenCV uses BGR, while Pillow uses RGB - for example, see https://towardsdatascience.com/what-library-can-load-image-in-python-and-what-are-their-difference-d1628c6623ad. See also [this comment on the StackOverflow thread](https://stackoverflow.com/questions/59162727/python-add-noise-to-image-breaks-png#comment104578729_59164331) that you linked

The following script produces a working result for me - so I think anything after that is an OpenCV question, rather than a Pillow question.

```python
import io
from PIL import Image
import cv2
import numpy as np

im = Image.open("Tests/images/pil123rgba.png")
print(im.mode)  # RGBA

img = cv2.imread("Tests/images/pil123rgba.png", cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(img, cv2.COLOR_BGRA2RGBA)
img = Image.fromarray(img, 'RGBA')

fp = io.BytesIO()
img.save(fp, format="png")
content = fp.getvalue()

with open("out.png", "wb") as f:
	f.write(content)
```

**Comment by TensorTom** [comment]
That solved it and allowed me to apply the noise with no problem. Thank you
