### ISSUE TITLE
Incorrect upsampling with Image.BOX

### ISSUE THREAD

**Issue by 99991** [python-pillow/Pillow#4258]
### What did you do?

I created a white image and resized it using `Image.BOX` resampling.

### What did you expect to happen?

I expected a white image:

![white](https://user-images.githubusercontent.com/18725165/70423778-759a6980-1a6e-11ea-826c-9c2ce44d9e8e.png)

### What actually happened?

But instead, I got a white image with vertical black lines:

![bug](https://user-images.githubusercontent.com/18725165/70423771-73d0a600-1a6e-11ea-9dd1-d5664c2f4784.png)

### What are your OS, Python and Pillow versions?

* OS: Debian 10
* Python: 3.7.3
* Pillow: 6.2.1

```python
from PIL import Image

# create a white image
image = Image.new('RGB', (8, 100), (255, 255, 255))
# resize image
image = image.resize((100, 100), Image.BOX)
# show white image with black vertical lines
image.show()
```

I think a good starting point to find this bug would be to check if [any of the horizontal filtering coefficients are zero](https://github.com/python-pillow/Pillow/blob/b64d96d4149b084b6224676469d5e51d2ce194f6/src/libImaging/Resample.c#L619).

**Comment by homm** [comment]
I can confirm. The problem is that BOX, unlike other filters, is a discontinuous function. It equals 1 in range (-0.5, 0.5) and equals 0 on the rest range. What is it equal to in -0.5 and 0.5? I don't know exactly, because it should be exactly 1 long, so if it equals 1, it will be a bit longer than 1, and if it will be 0, it will be slightly shorter than 1.

Current implementation defines box filter as 1 on [-0.5, 0.5) range (0.5 is not included).

```c
static inline double box_filter(double x)
{
    if (x >= -0.5 && x < 0.5)
        return 1.0;
    return 0.0;
}
```

I'll try to find the way how to fix this gently.

**Comment by 99991** [comment]
For reference, OpenCV's `INTER_AREA` filter builds the weighting table [like this](https://github.com/opencv/opencv/blob/92b98888370128143a7d9180198a9336c2271a69/modules/imgproc/src/resize.cpp#L3173).

**Comment by homm** [comment]
Oh my god, I believe I found a fix and can mathematically prove it.

The fix is very simple. Instead of defining the BOX filter as 1 on [-0.5, 0.5), define it 1 on (-0.5, 0.5].

```c
static inline double box_filter(double x)
{
    if (x > -0.5 && x <= 0.5)
        return 1.0;
    return 0.0;
}
```

The main question is "<b>how we can be sure that 0.0 is the correct value for `box_filter(-0.5)` while it wasn't for `box_filter(0.5)`?"</b>.

To prove this I'll prove that `x` argument for `box_filter` <b>could never be -0.5</b>. 

I will use the following lines from the code:

```c
    scale = (double) (in1 - in0) / outSize;
    filterscale = max(1.0, scale)
    support = filterp->support * filterscale;
    center = in0 + (xx + 0.5) * scale;
    ss = 1.0 / filterscale;
    xmin = (int) (center - support + 0.5);
    for (x = 0; x < xmax; x++) {
        double w = filterp->filter((x + xmin - center + 0.5) * ss);
        k[x] = w;
        ww += w;
    }
```

## Start

For `x == -0.5` in `box_filter` function, this equation should be true:
`(x + xmin - center + 0.5) * ss == -0.5`

`ss` is `1.0 / filterscale`, where `filterscale` is `max(1.0, scale)`:
`x + xmin - center + 0.5 == -0.5 * max(1.0, scale)`

Now we have two branches, first with `0.0 < scale <= 1.0` and `filterscale == 1.0`, second with 
`scale > 1.0` and `filterscale == scale`

### `0.0 < scale <= 1.0` case

`x + xmin - center + 0.5 == -0.5`

`xmin` is  defined as `int(center - support + 0.5)`:
`x + int(center - support + 0.5) - center + 1 == 0`

`support` is `filterp->support` (which is 0.5 for BOX filter) multiplied by `filterscale`, which is 1.0:
`x + int(center - 0.5 + 0.5) - center + 1 == 0`

Rearrange:
`x + 1 == center - int(center)`

`smth - int(smth)` is a fraction part of `smth`. In the end:
`x + 1 == frac(center)`


### `scale > 1.0` case

`x + xmin - center + 0.5 == -0.5 * scale`

`xmin` is  defined as `int(center - support + 0.5)`:
`x + int(center - support + 0.5) - center + 0.5 == -0.5 * scale`

`support` is `filterp->support` (which is 0.5 for BOX filter) multiplied by `filterscale`, which is `scale`:
`x + int(center - 0.5 * scale + 0.5) - center + 0.5 == -0.5 * scale`

Rearrange:
`x + 1 == center - 0.5 * scale + 0.5 - int(center - 0.5 * scale + 0.5)`

So, we came up to the same equation:
`x + 1 == frac(center - 0.5 * scale + 0.5)`

### Summary

We have two cases:
`x + 1 == frac(center)`
`x + 1 == frac(center - 0.5 * scale + 0.5)`

Since `x` is some positive integer, and a fraction is always in [0.0, 1.0) range, but newer equals 1.0, both equations are impossible.

Therefore `x` could newer be -0.5 in `box_filter` function.
