### ISSUE TITLE
The fill color in Image.transform doesn't work

### ISSUE THREAD

**Issue by bool-dev** [python-pillow/Pillow#428]
Exactly what the issue header says, the `fill` option in `Image.transform()` doesn't seem to work. Here is what i have been trying:

```
transd = img.transform(size, Image.PERSPECTIVE, coeffs,
                                  Image.BICUBIC, fill=255)
# coeffs is a numpy array that was calculated in another function
```

The transform works perfectly, it's only the fill color that doesn't work, no matter what color i try, it always ends up being black.

**Comment by rickyhan** [comment]
So is it possible to set the fill to transparent?

**Comment by rickyhan** [comment]
The default parameter for fill is 1 and setting it to 0 does nothing.

**Comment by rickyhan** [comment]
Here is a workaround:

http://stackoverflow.com/questions/5252170/specify-image-filling-color-when-rotating-in-python-with-pil-and-setting-expand

**Comment by rickyhan** [comment]
Even better:

```python
Image.paste(im, box=(x,y), mask=im)
```

**Comment by Zerphed** [comment]
@rickyhan Hey, I am currently fighting with the same issue. Did you figure out a performant workaround for this? Unfortunately I can't deduce what you did exactly from your last comment :)

**Comment by rickyhan** [comment]
@Zerphed not sure about performance. regarding the above line, `Image` is the one you want to paste `im` onto iirc.

**Comment by Zerphed** [comment]
@rickyhan Ahh, I see. I just realized that since I don't need the alpha channel, and since everything over the image boundaries is memset to 0, I can get a mask of the outside image pixels by adding an alpha channel to my image before the transform and setting alpha for all pixels to 255. This way all the pixels outside the image will get alpha channel values of 0 and I can extract a mask to replace those values with the value of my choosing :). Thanks for the tip though!

**Comment by jdbcode** [comment]
For those finding themselves here wondering about setting fill color, use the `fillcolor` parameter to set fill color on background pixels. It was added in [#2852](https://github.com/python-pillow/Pillow/pull/2852).

```
transd = img.transform(size, Image.PERSPECTIVE, coeffs,
                                  Image.BICUBIC, fillcolor=(150, 10, 30))
```
