### ISSUE TITLE
Python 3.8 can't import PIL

### ISSUE THREAD

**Issue by KimChow** [python-pillow/Pillow#4288]
```
C:\zombie>ipython
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AM
D64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from PIL import Image
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b7f01c2f8cfe> in <module>
----> 1 from PIL import Image

ModuleNotFoundError: No module named 'PIL'

In [2]: quit

C:\zombie>pip install pillow
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: pillow in c:\python38\lib\site-packages (6.2.1)
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
```

Hi, I have install pillow but I can't import it.

**Comment by radarhere** [comment]
Hi. My first thought is that maybe pip is installing Pillow to the wrong Python. Could you try `ipython -m pip install Pillow`?

**Comment by KimChow** [comment]
I have try it but I can run it.

Using python something.py also appears .

**Comment by radarhere** [comment]
Apologies, I'm not following. Are you saying that you have tried my suggestion and it did not work? Could you show the output as you did in your first post?

**Comment by KimChow** [comment]
yes. I tried the method you said, and I still get an error like I did before. As the project rushed to go online, it was temporarily switched to 3.7.6. If need to cooperate with the test again, I will find a machine to install the relevant environment.

**Comment by radarhere** [comment]
This is a fairly straightforward error - your Python version not finding a pip-installed package. While we're able to try and offer suggestions, I would imagine that there isn't a change that needs to be made to Pillow. So if this situation is resolved for you, then this issue can be closed. Are you happy for that to happen, or would you like more advice?

**Comment by KimChow** [comment]
Doesn't pillow the software need to update something to support it? I have used pip to install it and python3.8 still can't find it.It can work if I using the same way install in pyton3.7.

**Comment by radarhere** [comment]
Pillow has provided binary wheels to PyPI for Python 3.8 on Windows. At https://pypi.org/project/Pillow/#files, you can find [Pillow-6.2.1-cp38-cp38-win32.whl](https://files.pythonhosted.org/packages/dc/f3/c4244b8bb4175889a12e483d9d9ab51137dc9d7f1cbdfcf37939d14ba7f9/Pillow-6.2.1-cp38-cp38-win32.whl) and [Pillow-6.2.1-cp38-cp38-win_amd64.whl](https://files.pythonhosted.org/packages/b6/5a/ee223b0503ebba3d6adcf24516cbae85d581058f2bac635fc82e4bd6c2bf/Pillow-6.2.1-cp38-cp38-win_amd64.whl).

It has been mentioned elsewhere that [you need pip >= 19.2 to use the 3.8 wheels on Windows](https://github.com/python-pillow/Pillow/pull/4214#issue-342669176).

However, neither of those things should be the problem, because you have actually installed Pillow. Your Python version just can't find it.

**Comment by KimChow** [comment]
Thanks, I will try it.
