### ISSUE TITLE
No module named PIL in PyCharm

### ISSUE THREAD

**Issue by MK8816** [python-pillow/Pillow#4319]
Im using Pycharm 2019.1.3

![imagen](https://user-images.githubusercontent.com/43162580/71602866-ed712680-2b38-11ea-8517-49dbb6766f4d.png)
![imagen](https://user-images.githubusercontent.com/43162580/71602940-4b9e0980-2b39-11ea-9b54-af021136b383.png)
![imagen](https://user-images.githubusercontent.com/43162580/71602906-2e693b00-2b39-11ea-98bc-1c4b3dc5ba42.png)

What Im doing wrong?

**Comment by radarhere** [comment]
It would be great if you could supply the commands that you're running and their response in text, rather than in screenshot form. That would give more information.

My initial guess is that you have used pip to install Pillow to a different version of Python than the one you are running. To check this, I would recommend adding `print(tkinter)` to your Python script, and running `pip show Pillow` from the command line. I am guessing that the two paths will be rather different.

**Comment by MK8816** [comment]
> It would be great if you could supply the commands that you're running and their response in text, rather than in screenshot form. That would give more information.


What commands? That screenshoot is the entire script. I'm sorry but I didn't get where should i put the "print(tkinter)". And the show pillow gave me this:
![imagen](https://user-images.githubusercontent.com/43162580/71603707-eba96200-2b3c-11ea-9fb9-384fb2ec3a7f.png)

**Comment by MK8816** [comment]
Well I solved it. I had to go to the Project Interpreter and install there the Pillow package. Sorry :(
![imagen](https://user-images.githubusercontent.com/43162580/71604345-24970600-2b40-11ea-9551-e3ade8842aee.png)

**Comment by radarhere** [comment]
Thanks for persisting.

**Comment by nulano** [comment]
It sounds like you already figured this out, but just to make sure:

When you create a new project in PyCharm, by default it creates a new Python virtual environment. This environment inherits your Python version, but not your installed packages, to avoid conflits between your different projects. When you want to install packages to the virtual environment, you have to use the pip from the virtual environment, not your system pip. It is easiest to do this through the PyCharm settings menu in your last screenshot.
