### ISSUE TITLE
RGBA conversion breaks edge detection

### ISSUE THREAD

**Issue by BernardZhao** [python-pillow/Pillow#4321]
### What did you do?

I am having an issue with Pillow's edge detection, specifically after I convert my source image to RGBA. For context, I open a `.jpg` file, and edge detection works fine on the image. However, after conversion the detected edges are all blank. Am I doing something wrong that involves the new alpha channel? See the code below to replicate:

### What did you expect to happen?

I expect the edges of the images to be detected, producing an image like this:

![image](https://user-images.githubusercontent.com/12194331/71617979-73f62a00-2b72-11ea-9a8d-05857f7accd3.png)

### What actually happened?

Instead, a blank image is generated:
![image](https://user-images.githubusercontent.com/12194331/71617985-78bade00-2b72-11ea-959a-bd104da8a45b.png)

### What are your OS, Python and Pillow versions?

* OS: Mac OSX Catalina
* Python: 3.7.5
* Pillow: 6.2.1

```python
from PIL import Image, ImageFilter
image = Image.open("examples/image.jpg")
image.filter(ImageFilter.FIND_EDGES).show()
image = image.convert('RGBA')
image.filter(ImageFilter.FIND_EDGES).show()
```

I have also tried this with other ImageFilters, and they seem to work fine.

**Comment by radarhere** [comment]
My interpretation of what you're seeing is that Pillow is finding the edges of all channels, including the alpha channel. Since your image has a constant value for the alpha channel throughout - opaque - the edges of the alpha channel are the edges of the image - a box.

So if I run the following code on [a test image](https://github.com/python-pillow/Pillow/blob/master/Tests/images/pil123rgba.png) that actually has varying alpha values -

![pil123rgba](https://raw.githubusercontent.com/python-pillow/Pillow/master/Tests/images/pil123rgba.png)

```python
from PIL import Image, ImageFilter
im = Image.open("Tests/images/pil123rgba.png")
im.filter(ImageFilter.FIND_EDGES).save("pil123rgba_edges.png")
```

![pil123rgba_edges](https://user-images.githubusercontent.com/3112309/71619103-e02a6980-2c16-11ea-87f3-ea2544547f18.png)

**Comment by homm** [comment]
> Instead, a blank image is generated:

It's not blank, it's transparent (have zero in the alpha channel). If you want to preserve the alpha channel, you can use `alpha = im.getchannel('A')` and `im.putalpha(alpha)` methods.
