### ISSUE TITLE
Pillow stickers & domain

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4361]
Attention world and @python-pillow/pillow-team,

I have long longed for Pillow stickers, and thanks to the generosity of Tidelift and logistical assistance from @brennaheaps, looks like 2020 will be the year we finally get them. Roughly, my vision is 500 of the following design purchased from StickerMule and 100 shipped to each of the 5 core developers (@homm included, though he recently stepped away from Tidelift payroll):

![pillow-logo](https://user-images.githubusercontent.com/72164/72531822-47176780-3840-11ea-9ec0-4eaefe077208.png)

The deadline for submitting the order will be arbitrarily set to coincide with the next Pillow release, with delivery in the hands of core developers no later than mid-year (at which point they can distribute them at local events, PyCon, etc.)

To accomplish this, we'll need:

- High resolution design
- Current address of each core developer (if different than address on file with Tidelift)
- Drone delivery for @wiredfool who is currently somewhere in Europe, address at time of sticker delivery TBD 😄 
- Whatever else @brennaheaps says we need to make this happen
- Ideas from @python-pillow/pillow-team about how the process and end result should be, assuming not everyone will picture the same thing I do.

Thanks all!! Looking forward delivering awesome Pillow stickers to core developers and subsequently the world.

**Comment by hugovk** [comment]
Sounds good!

**Comment by wiredfool** [comment]
I still hope for one like this one: 

![A94695E0-0E4A-41D9-B0E4-E617AC23B7C9](https://user-images.githubusercontent.com/19792/72560904-461a2080-38a8-11ea-95af-d18217ef8eda.jpeg)

**Comment by Metallicow** [comment]
I never knew imagery on stickers was so important until now lol!
What are we talking about... like something to slap on a laptop or a bumper sticker or at the head of your bed or something....?
What is the intended use for the stickers I mean...

**Comment by hugovk** [comment]
They're commonly used for [laptops](https://www.google.com/search?q=laptop+stickers&source=lnms&tbm=isch), but you can of course stick them anywhere.

[Hexagonal stickers](https://www.google.com/search?q=hexagon+laptop+stickers&source=lnms&tbm=isch) allow for tessellation.

**Comment by Metallicow** [comment]
That is kinda neat. I knew a 1 guy that did that type of sticker graffiti to his fridge.
Other than that usually children get in trouble with them around halloween and you'll find a ton of em plastered everywhere the next day.

In the printshop usually magnets as giveouts was more popular, something for your fridge from the local pizza joint that had a phone number on it, tho they cost more. Usually it is a advertising tax writeoff at the end of the year.
One guy did vinyl for cars and windows and such, tho I never really considered that type of stuff "stickers". 
Usually you will see bands put them on their instrument cases also sometimes. and sometimes in a holiday card isle at the store.

**Comment by wiredfool** [comment]
I’d say its at least as important as the color of the bike shed.  

Sticker covered laptops are a thing at open source conferences, we need to keep up appearances or we’ll have a sticker gap.

**Comment by aclark4life** [comment]
OK so maybe we'll do 50 hexagon + 50 custom * 5 developers.

**Comment by Metallicow** [comment]
I'd ask you to send me a proof, but, I'd guess you already stuck them on your laptop to test :)~

**Comment by wiredfool** [comment]
There needs to be rigorous testing -- we need to ensure compatibility with pre-butterfly keyboard macs.

**Comment by aclark4life** [comment]
OK @brennaheaps is working on some test prints so should be able to paste both designs shortly. Also thanks @brennaheaps & Tidelift for 3 years of python-pillow.org domain renewal!

**Comment by Metallicow** [comment]
Yes, tho the testing comment was a sorta a joke, really a few stickers should be tested on some sort of surface and removed. Preferable recorded. This not only shows the quality of the glue for the sticker, but if someone might need to remove a sticker(or graffiti!) and best method of doing so.

**Comment by Metallicow** [comment]
pip install pillow-sticker

...for example...

**Comment by brennaheaps** [comment]
Hi there @python-pillow/pillow-team! 

The sample stickers are in and a few of each are on their way to @aclark4life for testing. Here's some photos and details: 

### Version 1: logo only
![logo](https://user-images.githubusercontent.com/2515203/73842772-3c227800-47eb-11ea-89c5-d60af03c06f5.jpg)

**Size: 2.97" x 3"**

### Version 2: logo and project name (no drop shadow) 

![IMG_1358](https://user-images.githubusercontent.com/2515203/73843018-c23ebe80-47eb-11ea-9699-b84b7e2080c1.jpg)

**Size: 5" x 1.64"**

### Version 3: logo and project name (drop shadow)

![IMG_1357](https://user-images.githubusercontent.com/2515203/73843084-ea2e2200-47eb-11ea-86b6-f07fdb0c8ed3.jpg)

**Size: 5" x 1.95"**

...and here's a comparison shot:

![IMG_1360](https://user-images.githubusercontent.com/2515203/73843133-0762f080-47ec-11ea-9ed9-926f80f5e2c8.jpg)

**Comment by aclark4life** [comment]
Awesome!! Thanks for that. I’d say put the logo only sticker inside a hexagon to make @wiredfool happy and let me get back to you on the other one (it’s close)

**Comment by aclark4life** [comment]
E.g. 

![](https://user-images.githubusercontent.com/19792/72560904-461a2080-38a8-11ea-95af-d18217ef8eda.jpeg)

**Comment by aclark4life** [comment]
FYI Looks like humans on Twitter prefer Version 2: logo and project name (no drop shadow) https://twitter.com/aclark4life/status/1225560674895585281, so that's a go.

I also kinda like Version 1: logo only but @wiredfool you prefer hexagon right? If we put that logo-only inside a hex shape, maybe we can add text "python-pillow.org" at the bottom (though I wouldn't copy the borders that the Python logos sticker has).

**Comment by aclark4life** [comment]
Also thanks again @al45tair, we're taking your "baby" to print!!

**Comment by wiredfool** [comment]
I think those are quite large compared to other stickers, although measuring them, the other stickers might be bigger than I’d thought. 
![18430A13-E442-4662-A739-B07E58CC7764](https://user-images.githubusercontent.com/19792/74057055-63439a00-49e3-11ea-90af-afc91dd4df69.jpeg)
![C1D42A7F-45A5-484E-B88D-65C78E17A656](https://user-images.githubusercontent.com/19792/74057059-65a5f400-49e3-11ea-94a6-2851263b228d.jpeg)

**Comment by brennaheaps** [comment]
👋 friends! Just want to confirm the following before we move forward: 

### Version 1
* The one edit I see for this version is to add the hexagon shape [like this design](https://github.com/python-pillow/Pillow/issues/4361#issuecomment-582473037). **Any thoughts on hexagon color, or just something that matches the design?** 
* Does the size work, or **any changes there**? 

### Version 2 
* Seems like this is the preferred version of this style, not version 3
* **Any size changes, or is the sizing ok**?

**Comment by aclark4life** [comment]
@brennaheaps I think sizing on both is fine, hexagon could probably white with some appropriate color text that says "pillow" or "python-pillow.org". Thank you!!

**Comment by brennaheaps** [comment]
@aclark4life sounds good! I'll get Version 1 revised and post as soon as it's ready.

**Comment by brennaheaps** [comment]
👋 revisions! I worked with our amazing designer @justinsid and he came up with two options for a revised V1:

![V1](https://user-images.githubusercontent.com/2515203/75200379-808e9d00-5733-11ea-985f-8fd381e517f7.jpeg)

![V2](https://user-images.githubusercontent.com/2515203/75200384-83898d80-5733-11ea-8981-6326c303cfda.jpeg)

Please let us know your thoughts. Thanks!

**Comment by Metallicow** [comment]
I like how the gradient goes along with the images in the first sticker.
I really think the dots in the <> makes both designs look odd.

Also the type seems cramped in both designs.
python
pillow
on 2 lines I think would look better as far as typesetting the font. Ex: python on top and pillow on bottom.

... just my thoughts...

**Comment by Metallicow** [comment]
Actually I guess I'm already part of the sticker clan sorta... lol
I just uncovered my first stickering on a laptop. Nothing special but it sends a message anyway. This laptop only has 1 sticker on it.(lame, I know... I'm a sticker noob)
![320px-I_Voted_Sticker](https://user-images.githubusercontent.com/4668356/75207178-9e60ff80-573d-11ea-9d8f-393efe774031.JPG)
I think we all know where we get these free stickers lol

**Comment by hugovk** [comment]
Looks good! I prefer the gradient too, and I quite like the circles: they're eyes so these are snakes too :)

**Comment by wiredfool** [comment]
I like the gradient in the firt one.

**Comment by brennaheaps** [comment]
Sounds like the gradient version is the winner but may require some font edits. 

@aclark4life any additional feedback before we revise?

**Comment by aclark4life** [comment]
@brennaheaps Gradient looks good to me, and I think we should have text (only) at the bottom and make it look like the text in the other logo e.g. 

![73843133-0762f080-47ec-11ea-9ed9-926f80f5e2c8](https://user-images.githubusercontent.com/72164/75367385-3ec63980-588e-11ea-8d20-9093e202b3b1.jpg)

I'd also be curious about a hexagon with just the logo + text and no side bars, in an attempt to not rip-off the PSF's design too much (copying "hexagon" is fair game, and they've approved our logo design already.)

Lastly, I had wanted to include the domain but not as much as I'd like the design to look really good 😄 

Thanks as always!!

**Comment by justinsid** [comment]
Hello! 👋 I just wanted to introduce myself, I'm a designer working at Tidelift and I was happy that @brennaheaps asked me to help assist with this project. Thank you for all the feedback in regards to the new options above. I removed the side bars and brought in the original text logo. I think it looks simple and clean and lets the color and imagery in the logo mark speak for itself. I hope this is getting closer to what you envision! 

<img width="694" alt="Screen Shot 2020-02-27 at 12 15 26 PM" src="https://user-images.githubusercontent.com/56552566/75473711-4ef81a80-595b-11ea-9b7a-15015fb16cca.png">

**Comment by aclark4life** [comment]
@justinsid Welcome, thank you, and I love it! I suggest maybe another revision with the logo filling more of the hexagon and the text reduced to accommodate. Either that… or it's absolutely perfect as-is, and I'm not sure which yet. 😄

**Comment by hugovk** [comment]
One thing I just noticed, hexagonal laptop stickers tend to have sharp corners, so they tesselate (check a Google Images search).

**Comment by wiredfool** [comment]
Also, to make hexagons tessalate, they need to be the same size.

**Comment by wiredfool** [comment]
I still think #1 here: https://github.com/python-pillow/Pillow/issues/4361#issuecomment-590602074 is the best to be a companion to the python hex sticker.

**Comment by aclark4life** [comment]
I'm OK with sizing in accordance with "standard hex sticker size" (whatever that is, smaller I guess) but I definitely don't want anything but the logo and text now, since if we copy the Python sticker logo design I'd feel obligated to track down the designer to get permission before printing up something so similar it can only be assumed to be a "design rip off". Alternatively if anyone else wants to find that designer and get them to approve our version, go for it.

**Comment by Metallicow** [comment]
I think @justinsid 4 design looks fine also, tho maybe using krita's wraparound mode and tweaking the offset might give a better preview of what a sheet might look like since default wraparound is rectangular...
It appears the ones @brennaheaps posted have a grey border, so not sure if that is supposed to be actually grey or a material layer such as clear material then printed on... Obviously the blue edge is the vector/cnc instruction layer for whatever a sticker company would use for the production cutting machine. I'd guess whatever they use is like a industrial 4 color press and crikut cutter combined into one machine to minimize errors nowadays.

Not sure what the end file format you send off is, but the guy that wrote this open source nesting software is awesome.
https://deepnest.io/
works real well if you have your own cnc machine/table and might for example want to cut something out of a piece of plywood, steel, lazercut plastics, etc. It's a life/material saver for his asking price of a $5+ donation. Just the material waste from most projects pays for itself with this one... !

**Comment by Metallicow** [comment]
I don't think you should worry too much about hex design. Its just some basic offsetting algorithms most any high-school kid should be able to do, tho it takes a bit to work them all together if you want smooth curves for example for more complex stuff like fonts.
This is a basic cad patcher I wrote for SourceCoder. As far as the hex, it is just a circle algorithm. a hex has 6 points so start with that double it in two circles so you have 12 points, then basically calulate the subdivisions further out the smoother to the edge you might want. Calculating the first and last point in the 2 circles is important tho as the [1:-1] will have overlap and whether you are considering tiling or nesting various polygons is a more complicated option.
![spline_polygon](https://user-images.githubusercontent.com/4668356/75491643-dc4b6700-597b-11ea-9d88-07b9607fc3cb.png)
if you dont have for example a tiling design, the last point will want to curve to what the logic would expect is the next shape or starting point of vertices. This might be where it starts to confuse some people, but normally the shop software/worker takes care of that before the file ends up in the machine.
But overall the bits of simple logic combine into what most people would call a splined polygon basically.

**Comment by Metallicow** [comment]
These are probably the most important parts in recent years....
as far as how fast pi is calculated... Some folk have this goal to keep beating each other in the calulation of it all. ... personally I think tau is the answer.....
```python
def CalculatePi_Chudnovsky(maxK=70, precision=1008, disp=1007):  # Parameter defaults chosen to gain 1000+ digits within a few seconds
    """
    https://en.wikipedia.org/wiki/Chudnovsky_algorithm
    """
    getcontext().prec = precision
    K, M, L, X, S = 6, 1, 13591409, 1, 13591409
    for k in range(1, maxK + 1):
        M = (K**3 - 16*K) * M // k**3
        L += 545140134
        X *= -262537412640768000
        S += Decimal(M * L) / X
        K += 12
    pi = 426880 * Decimal(10005).sqrt() / S
    pi = Decimal(str(pi)[:disp])  # Drop few digits of precision for accuracy
    # print("PI(maxK={} iterations, getcontext().prec={}, disp={} digits) =\n{}".format(maxK, precision, disp, pi))
    return pi

def CalculatePi_BBP(precision):
    """
    https://en.wikipedia.org/wiki/Bailey%E2%80%93Borwein%E2%80%93Plouffe_formula
    """
    getcontext().prec = precision
    return sum(1/Decimal(16)**k *
        (Decimal(4)/(8*k+1) -
         Decimal(2)/(8*k+4) -
         Decimal(1)/(8*k+5) -
         Decimal(1)/(8*k+6)) for k in range(precision))
```

These are the 2 competing pi algorithms in today's times.

**Comment by justinsid** [comment]
So taking a look at hex stickers with a simple Google image search I found this resource, [hexb.in](http://hexb.in/sticker.html). I realized that the standard for these stickers listed on that site is to have the hexagon oriented with the vertex positioned at the top.

![dimensions](https://user-images.githubusercontent.com/56552566/75597649-49cec480-5a5c-11ea-88bf-ef5b8ac52923.png)

Looking at my last design and rotating the hexagon (see A) and comparing it side by side  in reference to the [original python hexagon sticker](https://github.com/python-pillow/Pillow/issues/4361#issuecomment-582473037) you posted above I was bothered by the logo not being centered in the hexagon. If I rotate just the hexagon (see B)  and then recenter the text + logo back on the vertical axis I still think the whitespace surrounding isn't as pleasing visually as it was before. 

<img width="1283" alt="Screen Shot 2020-02-28 at 1 06 47 PM" src="https://user-images.githubusercontent.com/56552566/75597735-ce214780-5a5c-11ea-852e-22382f0414bb.png">

So it got me thinking is there a way I could adjust the layout to get the logo + text balanced in a way that's feels more symmetrical? I mean if we're talking about tessellations it only felt right to try a version where the elements were balanced enough so the sticker could be rotated any way and still fit with other hexagonal stickers in a shared space. Sooo exploring a bit more I had one more idea that I thought I'd offer up…

<img width="1124" alt="Screen Shot 2020-02-28 at 7 13 05 PM" src="https://user-images.githubusercontent.com/56552566/75598067-e3977100-5a5e-11ea-9880-59f5fbd55e63.png">

I like the balance this option has to offer and appreciate that rotated on any axis this sticker could work  when placed alongside others. As well I think it looks good next to the python sticker and pays homage to it with out feeling like it was "ripped" from the original artist. Also the gradient colors seemed pretty popular from the first round. I also included a grayscale version as another option, because why not? ;) I'm curious to hear everyone's thoughts!

<img width="1203" alt="Screen Shot 2020-02-28 at 7 20 28 PM" src="https://user-images.githubusercontent.com/56552566/75598215-b7302480-5a5f-11ea-9f9f-fc41e863ad53.png">

**Comment by Metallicow** [comment]
I like the () one in the comparison to the official. Maybe we can customize it a bit and sneak in a easter egg commit if the sticker machine runs python...
```python
>>> from __future__ import pillow_sticker_4_life as sticker
>>> sticker(arg='!=')
'<>'
>>> sticker()
'()'
>>> dict(sticker)
'{}'
>>> list(sticker)
'[]'
>>> print(sticker(walrus))
  File "<stdin>", line 1
    pillow := sticker.image
           ^
ValueError: invalid image class
>>> apply(sticker, laptop)
':)'
```

**Comment by aclark4life** [comment]
@justinsid ooo, OK I got it. Move "pillow" one side to the right and move "python" 3 sides to the left and we're done (I think?) Great job. (i.e. text at bottom but each word aligned to the 2 bottom edges not the x-axis.)

**Comment by aclark4life** [comment]
Also thanks @Metallicow for joining the sticker team and providing valuable feedback!! 😄

**Comment by Metallicow** [comment]
Resource for teachers/students/researchers/etc... https://www.redblobgames.com/grids/hexagons/
This is an excellently written interactive tutorial to teach people how to make their own hex library. 

Most times I see this stuff applied to tabletop games, but in your case, if the stickers come as singles the logic would be a tab bit different because a small offset is added for peeling instead of being a bleed.

**Comment by justinsid** [comment]
@aclark4life I adjusted the text around the hexagon and adjusted gradients around. Does this feel just that much closer to what you were thinking? 

<img width="1330" alt="Screen Shot 2020-03-02 at 10 27 27 AM" src="https://user-images.githubusercontent.com/56552566/75696001-8115bf00-5c70-11ea-8c98-945107d21076.png">

**Comment by aclark4life** [comment]
@justinsid Looks great! Not sure how others feel, but the only thing that doesn't look 100% right to me now is maybe the text should be the same font, and gray gradient color as the other logo e.g. #3A3A35 to #7A7670. (Either that or, since you rounded the text anyway, we could drop the "python" and center the text at the bottom; I like the idea of the two designs having similar design elements.)

**Comment by justinsid** [comment]
@aclark4life It should be the same font but I do have to admit I had to find a free bootleg version of the Flux the font used for the Python logo to make it work. I'm not sure if you or anyone has the official font to send over so I can typeset it in the sticker. But I'd be happy to change it back to the gray gradient color used in the first text mark.

**Comment by al45tair** [comment]
Hi all. It's been a while (for those who don't know, I drew the Pillow logo, which uses a couple of photos I took myself), but I *do* own a copy of the Flux font (which isn't that expensive… you really shouldn't use bootleg copies of fonts, and they'd be a lot cheaper if people weren't quite so keen on pinching them.)

I *think* the version used in the logo was bold, rather than the regular weight, which is probably why it doesn't look quite right.

I've had a go at replicating it, with the bold version of the font and with the text in grey (that's gray, for all you Americans ;-)). I've also used a slightly thicker arc to match the thicker stems on the font.

I don't know what the preferred format is for this. The previous image was a PNG, so that's what I've generated here. I can send a vector version to @justinsid if he'd like.

![Pillow Hex](https://user-images.githubusercontent.com/2750072/75716226-ad5c2a80-5cc6-11ea-8efd-8561fa7a1876.png)

**Comment by al45tair** [comment]
I'll just add that I think @justinsid has done a really nice job here. I like the design; in particular, the arc using the colours from the images is a nice touch.

**Comment by brennaheaps** [comment]
👋 How is everyone feeling about [this latest iteration](https://github.com/python-pillow/Pillow/issues/4361#issuecomment-593617127)? If this looks good I can send it to Sticker Mule for printing.

**Comment by wiredfool** [comment]
Looks good to me.

**Comment by aclark4life** [comment]
@brennaheaps It's a thing of beauty and I'm weeping silent tears … thank you and @al45tair and @justinsid and ship-away!

**Comment by justinsid** [comment]
Awesome! Glad we could make this a reality 👏 I'm happy to prep the file for StickerMule and hand it over to @brennaheaps

**Comment by al45tair** [comment]
@justinsid Here's [a PDF version](https://www.icloud.com/iclouddrive/0yuQWcsURxPDm53CGyycwgNeA#Pillow_Hex), and [an SVG version](https://www.icloud.com/iclouddrive/0fM3kQwQodLpU5-f9Vn42c-5A#Pillow_Hex) if that helps.

Some of it had to be rasterised (I used a conical fill to get the colours on the arc just right), but I don't think it's noticeable even at high zoom.

**Comment by justinsid** [comment]
Thank you @al45tair for the hard work! I was able to put together the final approved design prepped with the 1/8" bleed for StickerMule and I believe @brennaheaps is already making it a reality. 

Thanks again to everyone for their input! I'm happy to have landed on an idea that everyone would be more than happy to adorn their laptops. 😄

**Comment by radarhere** [comment]
Stickers have now been received by @aclark4life - https://twitter.com/aclark4life/status/1242104746737090560

**Comment by hugovk** [comment]
The stickers arrived here today, looking good, thanks!
