### ISSUE TITLE
No module named PIL, pil, Pillow, pillow

### ISSUE THREAD

**Issue by DarkVeneno** [python-pillow/Pillow#4489]
### What did you do?

I wanted to import image from PIL.

### What did you expect to happen?
I expected it to work, like it used to before...
### What actually happened?
...but then it just stopped working.
### What are your OS, Python and Pillow versions?

* OS: Windows 10 Pro 1983 (SO: 18362.720)
* Python: 3.7
* Pillow: 7.0.0

ModuleNotFoundError: No module named 'PIL'
ModuleNotFoundError: No module named 'pil'
ModuleNotFoundError: No module named 'Pillow'
ModuleNotFoundError: No module named 'pillow'

When installing:
Requirement already satisfied: pillow in c:\users\**********\appdata\local\programs\python\python37-32\lib\site-packages (7.0.0)

```python
from PIL import Image
```

**Comment by radarhere** [comment]
To save you trying alternatives at least, it is `PIL` - you can stop trying 'pil', 'Pillow' and 'pillow'.

What is the command that you're running to see that install output? We've recently updated [our docs to suggest](https://pillow.readthedocs.io/en/latest/installation.html) that rather than running `pip install Pillow`, users run `python3 -m pip install --upgrade Pillow`, to try and help ensure that the correct Python version is being used for installation.

**Comment by DarkVeneno** [comment]
It just gives me a blank space, when I try `python3 -m pip install --upgrade Pillow`

**Comment by radarhere** [comment]
What module didn't it find?

**Comment by DarkVeneno** [comment]
PIP. But anyways, I think I found the solution. My pip is installing onto the python 37_32 folder, but python is installed on 37_64, and something to do with visual studio.
