### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by lvntky** [python-pillow/Pillow#4510]
Hello there. I have an issue on Pillow. I'm scraping images from google than scaling them with pillow. at sompoint i got an error ``` OSError: cannot identify image file ``` I try to solve with ``` ImageFile.LOAD_TRUNCATED_IMAGES = True ``` but it didnt fix,

**Comment by hugovk** [comment]
Thank you for reporting an issue.

Follow these guidelines to ensure your issue is handled properly.

If you have a ...

1.  General question: consider asking the question on Stack Overflow
    with the python-imaging-library tag:

    * https://stackoverflow.com/questions/tagged/python-imaging-library

    Do not ask a question in both places.

    If you think you have found a bug or have an unexplained exception
    then file a bug report here.

2.  Bug report: include a self-contained, copy-pastable example that
    generates the issue if possible. Be concise with code posted.
    Guidelines on how to provide a good bug report:

    * https://stackoverflow.com/help/mcve

    Bug reports which follow these guidelines are easier to diagnose,
    and are often handled much more quickly.

3.  Feature request: do a quick search of existing issues
    to make sure this has not been asked before.

We know asking good questions takes effort, and we appreciate your time.
Thank you.

### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as Plone, Django, or Buildout, try to replicate the issue just using Pillow.

```python
code goes here
```

**Comment by lvntky** [comment]
# What did you do?
I have a script that scraping images with related keywords on google and then process them with pillow.

Pillow works properly but when I add more keywords and scrap more images I got an error

# What did you expect to happen? 
Processing all the Images just like worked for images that scraped with one keyword

# What actually happened?

'''
OSError: cannot identify image file
'''

# What are your OS, Python and Pillow versions?

* Arch Linux x86_64  5.5.10-arch1-1 
* Python 3.6.2 :: Continuum Analytics, Inc.
* Pillow:  '4.2.1'

**Comment by lvntky** [comment]
updating Pillow is solved the problem.
