### ISSUE TITLE
OSError: cannot identify image file <_io.BytesIO object at 0x000001C397272518>

### ISSUE THREAD

**Issue by ronakkjain** [python-pillow/Pillow#4520]
```
C:\Users\RONAK JAIN\Anaconda3\lib\site-packages\PIL\Image.py:2685: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
Traceback (most recent call last):
  File "generate_tfrecord.py", line 100, in <module>
    tf.app.run()
  File "C:\Users\RONAK JAIN\Anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\RONAK JAIN\Anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\RONAK JAIN\Anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "generate_tfrecord.py", line 91, in main
    tf_example = create_tf_example(group, path)
  File "generate_tfrecord.py", line 48, in create_tf_example
    image = Image.open(encoded_jpg_io)
  File "C:\Users\RONAK JAIN\Anaconda3\lib\site-packages\PIL\Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x000002A7DC692518>
```

**Comment by ronakkjain** [comment]
This was during building TF-records

**Comment by hugovk** [comment]
Thank you for reporting an issue.

Follow these guidelines to ensure your issue is handled properly.

If you have a ...

1.  General question: consider asking the question on Stack Overflow
    with the python-imaging-library tag:

    * https://stackoverflow.com/questions/tagged/python-imaging-library

    Do not ask a question in both places.

    If you think you have found a bug or have an unexplained exception
    then file a bug report here.

2.  Bug report: include a self-contained, copy-pastable example that
    generates the issue if possible. Be concise with code posted.
    Guidelines on how to provide a good bug report:

    * https://stackoverflow.com/help/mcve

    Bug reports which follow these guidelines are easier to diagnose,
    and are often handled much more quickly.

3.  Feature request: do a quick search of existing issues
    to make sure this has not been asked before.

We know asking good questions takes effort, and we appreciate your time.
Thank you.


### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 


Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as Plone, Django, or Buildout, try to replicate the issue just using Pillow.


```python
code goes here
```

**Comment by radarhere** [comment]
The warning that is printed would seem to be the explanation here - `image file could not be identified because WEBP support not installed`.

https://pillow.readthedocs.io/en/stable/installation.html has some mentions of WebP, or you could look at https://developers.google.com/speed/webp/download if you want.

**Comment by radarhere** [comment]
Closing, as this has a straightforward explanation. If you have any further questions or comments, this issue can be reopened.
