### ISSUE TITLE
Bug with line joints

### ISSUE THREAD

**Issue by LeonLenclos** [python-pillow/Pillow#4579]
### What did you do?

When I use the `joint='curve'` attribute on the line method with a sequence of numeric value, I get an error.

### What did you expect to happen?

[The documentation say](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.line) that you can pass *Sequence of either 2-tuples or numeric values*.

So, this should work:
```pycon
>>> from PIL import Image, ImageDraw
>>> im = Image.new('RGB', (800, 600))
>>> draw = ImageDraw.Draw(im)
>>> draw.line((400, 200, 300, 280, 100, 280), 0, 50, joint='curve')
```

### What actually happened?

 *Sequence of 2-tuples*  and `joint='curve'` works fine :

```pycon
>>> draw.line(((400, 200), (300, 280), (100, 280)), 0, 50, joint='curve')
```

*Sequence of numeric values*, but no `joint='curve'` works fine : 

```pycon
>>> draw.line((400,200,300,280,100,280), 0, 50)
```

*Sequence of numeric values*   and `joint='curve'` doesn't work :
```pycon
>>> draw.line((400,200,300,280,100,280), 0, 50, joint='curve')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leon/virtualenvs/ogn/lib/python3.5/site-packages/PIL/ImageDraw.py", line 165, in line
    for start, end in ((xy[i-1], point), (point, xy[i+1]))
  File "/home/leon/virtualenvs/ogn/lib/python3.5/site-packages/PIL/ImageDraw.py", line 165, in <listcomp>
    for start, end in ((xy[i-1], point), (point, xy[i+1]))
TypeError: 'int' object is not subscriptable
```

### What are your OS, Python and Pillow versions?

* OS: Debian Linux
* Python: 3.5.3
* Pillow: '5.4.1'

**Comment by radarhere** [comment]
Thanks for reporting this bug. I've created PR #4580 to resolve it.

**Comment by hugovk** [comment]
> [The documentation say](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.line) that you can pass _Sequence of either 2-tuples or numeric values_.

Hmm, the docs in full give examples of each:

> * **xy** – Sequence of either 2-tuples like `[(x, y), (x, y), ...]` or numeric values like `[x, y, x, y, ...]`.

The examples are a list of tuples and a list. In https://github.com/python-pillow/Pillow/issues/3738 we decided not to support a list of lists.

All combinations:

```python
[(x, y), (x, y), ...]  # list of tuples ✅
[[x, y], [x, y], ...]  # list of lists ❌
((x, y), (x, y), ...)  # tuple of tuples ❓
([x, y], [x, y], ...)  # tuple of lists ❌
[x, y, x, y, ...]  # list ✅
(x, y, x, y, ...)  # tuple ❓
```

I know it works for tuples (of values) when there's no `joint="curve"`, but I'm wondering if we should explicitly support it? Does it work by design or by accident?

Do we also support them for all other `xy` sequence parameters in ImageDraw? Should we?

**Comment by radarhere** [comment]
The key argument in #3738 for me is https://github.com/python-pillow/Pillow/issues/3738#issuecomment-507126728
> Also, tuples and lists are for slightly different things (immutable/mutable, structure/order). Does that really matter? I think maybe it does: semantically you know a coordinate like (100, 200) can't have a third value; but [100, 200] looks like it could. So I'm tending towards keeping it as is.

This is now the opposite situation. Instead of clarifying that a coordinate is immutable, this is about clarifying that a list of coordinates is mutable. Whereas it's harder to imagine a scenario where a user has a mutable `(x, y)` coordinate, I think it's easier to imagine a user having a list of coordinates that, for the purposes of their code, they would like to be seen as immutable. As in the other issue though, no strong feelings.

Tuples of values seem to work for the other ImageDraw methods.

**Comment by LeonLenclos** [comment]
My opinion isn't worth much. But I tend to think that any iterable (that contains points or tuples of points) should be accepted. (under the principle of duck typing).

**Comment by hugovk** [comment]
Sounds reasonable, thanks both!
