### ISSUE TITLE
Error when C++ uses Python Module

### ISSUE THREAD

**Issue by testmtbf10** [python-pillow/Pillow#4589]
Hi,

**What did you do?**
We have an embedded c++ Python program that runs scripts in a clean Python environment by always creating a fresh environment with Py_Initialize and Py_Finalize. I tried adding some  processing with uiautomator2 but that causes the application to crash on the second run of the script. I print the errors, it shows something wrong with PIL._imaging.

**What did you expect to happen?**
The module should load properly after the Python state has been cleared and re-created.

**What actually happened?**
The module failed when import PIL.Image.

**What versions of Pillow and Python are you using?**
Pillow 7.1.2
Python 3.6.5 64x
Windows 10

Code to reproduce

```c
#include <iostream>
#include <Python.h>
using namespace std;

int main() {
	Py_SetPythonHome((wchar_t*)L"D:\\Python\\Python36");
	Py_InitializeEx(0);
	if(!Py_IsInitialized()){
		cout << "Python initial failed" << endl;
		Py_Finalize();
	}
	
	PyObject* pModule;
	PyObject* pFunc = NULL;
	PyObject* pArg = NULL;

	PyRun_SimpleString("import sys");
	//PyRun_SimpleString("from PIL import Image");
	PyRun_SimpleString("sys.path.append('D:/Data/java/CppPython1')");
	PyRun_SimpleString("print(sys.path)");
	pModule=PyImport_ImportModule("PIL.Image");
	
	//pModule = PyImport_ImportModule("PIL");
	//pModule = PyImport_ImportModule("uiautomator2");
	//pModule = PyImport_Import(moduleName);
	if (!pModule) {
		cout << "import moudle failed"<<pModule << endl;
		PyErr_Print(); 
		return -1;
	}
	//pFunc = PyObject_GetAttrString(pModule, "connect");
	//if (!pFunc) {
	//	cout << "import module failed"  << endl;
	//	return -1;
	//}
	//PyObject_CallFunction(pFunc,"");
}
```

Output:

import module failed
```
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\PIL\Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

**Comment by hugovk** [comment]
Thank you for reporting an issue.

Follow these guidelines to ensure your issue is handled properly.

If you have a ...

1.  General question: consider asking the question on Stack Overflow
    with the python-imaging-library tag:

    * https://stackoverflow.com/questions/tagged/python-imaging-library

    Do not ask a question in both places.

    If you think you have found a bug or have an unexplained exception
    then file a bug report here.

2.  Bug report: include a self-contained, copy-pastable example that
    generates the issue if possible. Be concise with code posted.
    Guidelines on how to provide a good bug report:

    * https://stackoverflow.com/help/mcve

    Bug reports which follow these guidelines are easier to diagnose,
    and are often handled much more quickly.

3.  Feature request: do a quick search of existing issues
    to make sure this has not been asked before.

We know asking good questions takes effort, and we appreciate your time.
Thank you.

### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as Plone, Django, or Buildout, try to replicate the issue just using Pillow.

```python
code goes here
```

**Comment by hugovk** [comment]
How did you install Pillow? Or did you build it yourself?

Can you import from a Python script?

**Comment by radarhere** [comment]
For clarity, the reason you're talking about uiautomator2 is that [Pillow is one of its requirements](https://github.com/openatx/uiautomator2/blob/master/requirements.txt). So I presume that means that you installed Pillow through pip?

**Comment by nulano** [comment]
I can't reproduce this with Win 10 Home (1903), Python 3.7.6, Pillow 7.1.2 from pip.

Using code below I get the string 7.1.2 in every iteration:
```c
int main() {
    Py_SetPythonHome(L"C:\\Program Files\\Python37");
    for (int i = 0; i < 5; i++) {
        Py_InitializeEx(0);
        cout << PyUnicode_AsUTF8(
            PyDict_GetItemString(
                PyImport_ImportModule("PIL.Image"),
                "__version__"
            )
        ) << endl;
        PyErr_Print();
        Py_FinalizeEx();
    }
    return 0;
}
```
