### ISSUE TITLE
exif[11] = "Pillow test" does not pass the tests

### ISSUE THREAD

**Issue by rodrigob** [python-pillow/Pillow#4595]
I found a couple of errors in `Tests/test_imagefile.py`.
Text assignments like `exif[11] = "Pillow test" ` were not properly tested.

When fixing the test (PR #4594), it does not pass.

This is consistent with my trials on separate code.

**Comment by rodrigob** [comment]
@radarhere might be familiar with this piece of code.

**Comment by radarhere** [comment]
Hi. Thanks for noticing this. I've created https://github.com/rodrigob/Pillow/pull/1 to fix the problem. If you merge that in, your corrected tests should pass properly.

The problem is that I did not set the IFD offset to include the initial headers.

https://www.exif.org/Exif2-2.PDF points towards this by describing the offset of the 0th IFD as
> If the TIFF header is followed immediately by the 0th IFD, it is written as 00000008.H.

**Comment by rodrigob** [comment]
Merged the patch. All tests pass now indeed.
PR #4594 seems ready to merge into master.

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/4594 is merged to master, okay to close this?

**Comment by rodrigob** [comment]
Tests now pass.
