### ISSUE TITLE
JPEGs recognised as MPOs

### ISSUE THREAD

**Issue by JamesJGarner** [python-pillow/Pillow#4603]
Unsure why issue #1198 was closed as it is still a bug, learned this the hard way when a user tried to upload a JPEG and Pillow mistook it for a MPO and exploded.

**Comment by radarhere** [comment]
Hi. Could you give us a self-contained example, with an image? I'm interesting in looking at your specific file, to be able to talk about whether it is truly an MPO or not, and It would be good to know exactly what is meant by 'exploded'.

Also, what Pillow version are you using?

**Comment by radarhere** [comment]
Looking at the discussion in #1198, it seems to conclude that the image in question is actually an MPO.

**Comment by JamesJGarner** [comment]
Look at #1138 which is the same issue. This has the image example which is not a MPO

**Comment by radarhere** [comment]
[As per a comment in #1198](https://github.com/python-pillow/Pillow/issues/1198#issuecomment-93996235), if you run exiftool on 'bob 15.jpg', part of the results are

> Number Of Images                : 2
> MP Image Flags                  : Dependent child image
> MP Image Format                 : JPEG
> MP Image Type                   : Large Thumbnail (full HD equivalent)
> MP Image Length                 : 621306
> MP Image Start                  : 4850597

You can read in [the Multi-Picture format documentation](https://web.archive.org/web/20190227081740/http://www.cipa.jp/std/documents/e/DC-007_E.pdf) about the 'Dependent child image' and 'Large Thumbnail' values.

If you feel that it should be a JPEG because the extension is '.jpg', the same documentation states that
> To clarify the compatible range, a file consisting only of a main image and monitor display image (extension .JPG) is a Baseline MP file, while a file including other types (extension .MPO) is an Extended MP file.

Also, as a general rule, Pillow does interpret images according to their file extensions. It reads the data and acts accordingly.

**Comment by radarhere** [comment]
To be clear, when I talk about 'bob 15.jpg', that is the image from #1138

**Comment by radarhere** [comment]
Closing, since all available information says that the relevant image is an MPO, and no argument has been presented otherwise. This can be re-opened if there is a discussion to be had, but at the moment there is nothing to do.
