### ISSUE TITLE
Can't set command used for show()

### ISSUE THREAD

**Issue by avalonv** [python-pillow/Pillow#4643]
I'm trying to change the command used to display the image with show() from `display` to `pqiv` but it seems to just ignore any options I put. 

```python
f = Image.open(img)
upscaled = f.resize((1000,700), resample=Image.BOX)
upscaled.show(command='pqiv')
```

* OS: Void Linux 5.4
* Python: 3.8
* Pillow: 6.2.2

**Comment by avalonv** [comment]
Should probably make a separate issue for this but I'd like to add that as a user with no experience with ImageMagick I find `display` a really unintuitive default, wouldn't be easy to use `xdg-open`?

**Comment by nulano** [comment]
Looking at git history, the `show(command=...)` parameter has been unimplemented at least since the PIL fork:
https://github.com/python-pillow/Pillow/blob/9a640e3157150e35f17354517e8c6304fc428060/PIL/Image.py#L1480-L1483
https://github.com/python-pillow/Pillow/blob/9a640e3157150e35f17354517e8c6304fc428060/PIL/Image.py#L2121-L2127
[ImageShow.py ignores all options](https://github.com/python-pillow/Pillow/blob/9a640e3157150e35f17354517e8c6304fc428060/PIL/ImageShow.py)

The proper way to override the command is to extend one of the `ImageShow.Viewer`s and use their `show` function, or `ImageShow.register` it at the top of the list.

The [docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.show) are therefore wrong, and the parameter should be deprecated and removed.

---

I believe the default viewer was chosen based on system support, but both the default `display` and the fallback `xv` were added all the way back before the PIL fork, with only Ubuntu's `eog` added later (#2864). Perhaps there are now more modern variants widely available and the list can be updated.

You don't mention what OS you are using, other than "Linux". Can you please be more specific (including version)?

**Comment by avalonv** [comment]
I am using Void Linux 5.4.

And yeah I see, I tried digging at the code for the show() method and there seemed to be an option to register your own command but I didn't fully grasp the logic. It is not properly implemented but at the same time, it doesn't actually throw an exception if you use it, it just quietly ignores it, which was confusing when coupled with the outdated documentation. I'm a bit surprised I was the first person to report this.

I agree with the idea, the current defaults are awfully outdated, I think perhaps respecting the user's default application for that mimetype would be better.

**Comment by nulano** [comment]
> ... which was confusing when coupled with the outdated documentation. ...

Fun fact, that documentation has always been wrong! :smiley:

It was added 7 years ago in #280: https://github.com/python-pillow/Pillow/commit/25b6371b756644e2e64f74ad91805209fe658922#diff-3fef5f960d5bd8bdfb9c6fadcf96af22L1479-R1461

**Comment by radarhere** [comment]
I've created PR #4695 as another option, to actually use the `command` argument.

**Comment by radarhere** [comment]
Fyi, xdg-open has been around since 2006, before the most recent version of PIL was released in 2009.

I'm not opposed to the idea of adding it as another viewer, but could someone make an argument why it should be the default?

**Comment by avalonv** [comment]
I suggested it because `xdg-open` respects the default application of the system. You don't have to add complex logic to see if the user has a specific image viewer installed, you just tell it to open the default application for that mimetype.

**Comment by FergusonTG** [comment]
Hi

I had a play with this and managed:

```python

"""Use geeqie as a PIL.Image.show viewer"""

import PIL.ImageShow as show


class GeeqieViewer(show.UnixViewer):
    """Inherit from given class."""
    # pylint: disable=too-few-public-methods,no-self-use,unused-argument

    def get_command_ex(self, file, **options):
        """Define a shell command line"""
        command = "geeqie -t "  # -t launches without toolbar
        executable = "/usr/bin/geeqie"
        return command, executable


if show.shutil.which('geeqie'):
    show.register(GeeqieViewer, -1)
```

Incidentally, there seems to be a bug in ImageShow.register:
```python
    if order > 0:
        _viewers.append(viewer)
    elif order < 0:
        _viewers.insert(0, viewer)
```
which would silently ignore calling with `order=0`, the obvious way of putting your new class at the head of the list. I think the `elif ...:` line should be `else:`

Cheers
Tim

**Comment by radarhere** [comment]
@FergusonTG fair enough. I've created PR #4706 to correct this.

**Comment by FergusonTG** [comment]
:-)

**Comment by radarhere** [comment]
#4646 has been merged, so the `command` argument is now deprecated.

**Comment by hugovk** [comment]
Let's close this: `command` doesn't work, we've now deprecated it (https://github.com/python-pillow/Pillow/pull/4646), fixed a problem with `order` (https://github.com/python-pillow/Pillow/pull/4706), and use a subclass of `ImageShow.Viewer` instead.

Thanks for bringing the issue to light!
