### ISSUE TITLE
pyturbojpeg speed vs Pillow

### ISSUE THREAD

**Issue by austingg** [python-pillow/Pillow#4705]
I have found that Pillow decode large resolution jpeg image much slower than libjpeg-turbo 2.0. Seems pillow decode jpeg image with libjpeg-turbo8. 

for example, when decode 1080p jpeg image: Pillow cost 16ms, while libjpeg-turbo 2.0.4 only cost 8ms. 
CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz

**Comment by radarhere** [comment]
Hi. Pillow's Windows test suite is currently run against libjpeg-turbo 2.0.3, and I've just created PR #4708 to update that to 2.0.4, the latest version. So yes, Pillow can run with libjpeg-turbo 2.0.

What operating system are you using? How have you installed Pillow? I would guess that you have installed it from a wheel, and the solution for you might simply be to compile Pillow from source.

**Comment by austingg** [comment]
@radarhere 
OS: Ubuntu 16.04. 
Installation:  pip install Pillow

so, I should install libjpeg-turbo 2.0.x first， and   build pillow from source without any extra setting?

**Comment by radarhere** [comment]
Yes, provided you don't have regular libjpeg installed that Pillow might detect instead.

**Comment by austingg** [comment]
@radarhere  thanks for you reply.

i have create a conda environment and test pillow on it
```shell
conda uninstall -y --force pillow pil jpeg libtiff libjpeg-turbo
pip   uninstall -y         pillow pil jpeg libtiff libjpeg-turbo
conda install -yc conda-forge libjpeg-turbo
CFLAGS="${CFLAGS} -mavx2" pip install --upgrade --no-cache-dir --force-reinstall --no-binary :all: --compile pillow-simd
```

then I random select 700 image to test the jpeg decode speed between pillow and pyturbojpeg. 

method|speed|
:----:|:----:|
pillow| 110 M Pixels/s
pyturbojpeg | 180M pixels/s

pil's `_imaging.cpython-36m-x86_64-linux-gnu.so` is depend on `libjpeg.so.8` which is installed with libjpeg-turbo

**Comment by radarhere** [comment]
Could I just clarify that you found that Pillow with libjpeg-turbo produced different speed results than Pillow with libjpeg?

Be aware that this is the Pillow repo. pillow-simd is a forked project, over at https://github.com/uploadcare/pillow-simd

So are you asking why Pillow's speed doesn't match pyturbojpeg?

**Comment by austingg** [comment]
the image decode process is the same. pillow-simd speed up for image processing not for image io and I tried 
```
pip install --upgrade --no-cache-dir --force-reinstall --no-binary :all: --compile pillow
```
method|speed|
:----:|:----:|
pillow| 110 M Pixels/s
pillow-simd| 110 M Pixels/s
pyturbojpeg | 180M pixels/s

**Comment by radarhere** [comment]
Could you provide the script that is giving those speed results?

**Comment by radarhere** [comment]
If I run a script loading a 10,000 by 10,000 pixel image 1,000 times in Ubuntu then
- Pillow 7.1.2 (the version at the time of this issue's creation) takes [97 seconds](https://github.com/radarhere/Pillow/runs/4687842207#step:8:18)
- Pillow 9.0.0 takes [39 seconds](https://github.com/radarhere/Pillow/runs/4687840221#step:8:18)

That would seem to be a significant improvement.

However, when I try PyTurboJPEG, I get [414 seconds](https://github.com/radarhere/Pillow/runs/4687889215#step:8:16)... which is slower, rather than faster as this issue would suggest.
If I try the version of PyTurboJPEG at the time of this issue's creation, 1.5, then I get [337 seconds.](https://github.com/radarhere/Pillow/runs/4687913966#step:8:16)

So I don't see a problem to be resolved here, as Pillow seems to be faster than PyTurboJPEG at loading sizeable JPEGs. Closing, unless more information can be provided to demonstrate the issue.
