### ISSUE TITLE
Black Lives Matter

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4738]
A "fork" of DSF's BLM statement
=========================

**From the Pillow "fork" author.**

To Whom It May Concern,

As Python Pillow's creator and project leader, I feel obligated to use my platform to make a statement about the state of affairs in which we (software developers and users of Pillow) find ourselves, particularly in the USA but globally as well since the pandemic is a global issue. This statement is coming from me personally, and not @python-pillow/pillow-team or anyone else, for whatever that is worth.

And that statement is this: **the status quo in the USA with regard to existing frameworks for systemic racism, no matter how pervasive and ingrained in our history, is above-and-beyond-completely-unacceptable in 2020 and must continue to be systematically dismantled with a heightened level of effort beginning in 2020 and lasting until such time as movements like BLM are no longer required to get all humans to behave morally, ethically, respectfully and above all non-violently towards other humans.**

How do we do that? I have no idea, but I assume it starts with consensus regarding the need for change. How do we gain consensus in the open source software community? By openly expressing our beliefs, as passionately as we do when writing open source software (and we all know how heated that can get).

And with that, I'll leave you with a copy of the DSF's statement, which inspired me to write my own. Thank you DSF.

> The Django Software Foundation deeply values the diversity of our developers, users, and community. We are distraught by the suffering, oppression, and systemic racism the Black community faces every day. We can no longer remain silent.

> In silence, we are complicit. To eradicate racism, xenophobia, and all other forms of inequality, we must take action. It is our responsibility and our honor to use our platform to amplify the voices of the oppressed and marginalized.

> We ask today—and always—that the Python Pillow community comes together in support of the Black community. They will be heard.

> #BlackLivesMatter

Sincerely and respectfully yours, in open source for life,

—@aclark4life

**PS: I'll leave this issue "pinned" until the Oct 1 2020 release, then close. Not because the issue will be solved by then, but because the nature of statements is unfortunately "not everyone agrees with them". And while I sincerely hope everyone agrees with my statement (and the DSF's), I want to respect those that do not and so I'm setting a time limit after which this issue will no longer be "pinned". Thank you for respecting and reflecting on this issue at least during this time period.**

**Comment by Correct-Syntax** [comment]
>How do we do that? I have no idea, but I assume it starts with consensus regarding the need for change. How do we gain consensus in the open source software community? 

The real problem is in the *definition* of  things. What *is* love? What *is* hate? 

I am for supporting **ALL** life. What does that mean? It probably means something different to you than to me, right? 

To me, that means that we value the life in the womb as much as we do the black gentleman that was killed by the officer. To me, that means that we value life (**ALL** life) the way our Heavenly Father does:

"I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well." 
-Psa 139:14

The problem is that to many, something like abortion is love, but it's not. It is wrong to murder an inncoent life NOT because *I* said so, but because our Heavenly Father says so. 

The really sad thing is that people think that it is "hate" to even say what I just did. But, I want you to know that **I do love all of you** and more importantly, **our Heavenly Father loves you** -because He created you (read the verse above).

> By openly expressing our beliefs, as passionately as we do when writing open source software (and we all know how heated that can get).

I agree. That's why I felt as though I should write this even though others may disagree with this.

I respect you Alex and others, whether you agree with me or not. :)

**Comment by aclark4life** [comment]
Thank you @Correct-Syntax !! I appreciate your feedback. In particular, the importance of "definitions of things" and religious aspects are absolutely not lost on me. Perhaps a helpful concept to introduce as we wind our way towards closing  this issue on GitHub (but not resolving it in the "real world") is that of **shared goals**.

The controversial "black lives matter" statement and corresponding movement, at their best, are meant to convey a goal that supporters hope to _share and achieve_ amongst, and along with a global population: the tragic outcome of lives being lost to very controversial factors, e.g. "systemic racism", must be systematically eliminated. Say what you will about whether or not "systemic racism" exists, but tragic loss of life certainly does exist, and it almost certainly exists more in some communities than others (as does COVID-19, but I digress).

To the extent that the humans of the world can agree to the **shared goal** of ending tragic and completely unnecessary loss of life, then how you define things or why you are motivated by to pursue this goal matters significantly less than the **achievement of the shared goal**.

That brings me back to "how do we achieve this goal?" I still don't know, but I'm glad I opened this issue if for no other reason than to have this meaningful (to me at least) exchange. Thanks again @Correct-Syntax

**Comment by Correct-Syntax** [comment]
Thank you Alex for taking the time to have this exchange and your kindness and appreciation of my feedback. It seems to me that there should be more of these "controversial" discussions. I am not talking about a "who's-right-and-who's-wrong" argument (as that never solves anything...), but a respectful sharing of our views. Perhaps then we can learn something from each-other even if/when we don't fully agree. :)

**Please just know that I don't mean to condemn anyone, I just want to share my grief about what I see and answer your question about "how do we achieve this goal?".** ( Sorry about the length of this, but I feel that I really do need to share all of this.)

If Martin Luther King Jr. what true to what he said in his famous speech ("I have a dream that my...children will one day live in a nation where **they will not be judged by the color of their skin but by the content of their character.**"), then I have to wonder if he would really approve of the BLM statement and corresponding movement. 

I live in MN and from what I have heard and seen (the violence, the pride, the chaos, the looting, the (unnecessary) rebellion against authority and the tragic loss of life due to the riots -which are supposed to be all about standing up for life??!) I have to ask, *"does this really show good character on their part"*? I think not. It dishonorable and no real character at all.

**Please don't think that I am painting all those people with the same brush** (I am sure there are people within BLM who are sincere, but just don't know better), but this is largely what I see and I am distraught about it (almost to tears sometimes...). 

Hate NEVER overcomes hate. Then again, it's back to the definition of things, because to someone hurting another person could be "love" to them (and it's sad).

Now, my real grief:

When I see that saving lives clearly has nothing to do with the BLM movement and that it actually has a pro-abortion (pro-murder) agenda (along with a host of other un-biblical things), I can't agree with it in the least. 

**An injustice to one is an injustice to ALL.** -That is important to remember! 

How can a person (notably, me for example) join a riot about "black lives mattering" on the town square over the murder of a black gentleman, but not even think about the innocent black babies being murdered in the abortion clinic down one block. Uh, I thought black lives mattered?... 

To me this proves that saving and caring about black lives really has nothing to do with the BLM and it really grieves me... :(

> Say what you will about whether or not "systemic racism" exists, but tragic loss of life certainly does exist, and it almost certainly exists more in some communities than others (as does COVID-19, but I digress).

I agree. Though the "systemic racism" that I see is the Devil and his demons trying to eliminate the race of mankind. 
(We are created in our Heavenly Father's Image.) This is really the battle we fight: a spiritual battle.

But "racism" as we think of it has existed for centuries. Really it is just an extreme failure to love others the way our Heavenly Father says to.

> That brings me back to "how do we achieve this goal?" I still don't know

**Q: What exactly is the answer to racism?**
A: The love of our Heavenly Father, Yahweh and the hatred of sin.  

What do I mean?

*1Jn 3:4 KJV "Whosoever committeth sin transgresseth also the law: for sin is the transgression of the law."*
 
So, sin is breaking Yahweh, our Heavenly Father's commandments found in the Bible (literally "missing the mark"). We sin when we disobey and choose to do what Yahweh tells us not to do or vice versa. Yahweh's teachings (often called "commandments") found in the Bible are ALL righteous, just, holy and good. They show us how to love Him and each other the way that we ought to. Therefore sinning is not love, it's actually kind-of like hate.

Here is an example:

*Lev 19:17 KJV "Thou shalt not hate thy brother in thine heart: thou shalt in any wise rebuke thy neighbour, and not suffer sin upon him."*

 Yahweh commanded us to love our neighbor and not to hate them even in our heart. ("Neighbor" is another way of saying: anyone around you,.)

**Hey, I think that just in this one command, we've eliminated racism all together. HalleluYAH!** That is, if we all kept this teaching/commandment. 

Also notice how it says to rebuke/correct your neighbor when he sins. That's because it IS part of love to CARE enough about someone to show them from Scripture (the Bible) where they error so that they can be restored to the paths of righteousness and love as they ought. This is obviously contrary to the common though where someone correcting you is a bad thing. -it's not bad, it's good.

*Pro 6:23 "For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life"*

Think for a moment what we do on Github: we (often, I hope) gladly accept feedback from others for our open-source projects because we know that feedback makes a project better and/or draws attention to something that needs fixing. It is the same way in our lives -correction from others is a blessing and it shows that they care about you (with some exceptions, of course).

**I am open to correction from Scripture from anyone. I don't claim to have all the truth and if you feel that I am in error according to Scripture (the Bible), please do contact me and let me know. :)**

The problem: we have ALL *failed to walk in love towards our neighbor and our Heavenly Father* by failing to live by the good and righteous teachings and instructions (commandments) found in the Bible. We have all lied, cheated, hated our neighbor in our hearts, etc. and so we deserve the punishment (consequence) for our sin, which is death.

*Rom 3:23 "For all have sinned, and come short of the glory of Yahweh"*

*Rom 6:23  For the wages of sin is death; but the gift of Yahweh is eternal life through Yahushua Messiah [commonly called "Jesus"] our Master.* 

And so although we deserve punishment for not walking in love, Yahweh loved us so much that He gave His Son, Yahushua the Messiah to take our place and die on a tree for our sins. 

And so what can we do?

*Act 2:38  "Then Peter said unto them, Repent, and be baptized every one of you in the name of Yahushua Messiah [commonly called "Jesus"] for the remission of sins, and ye shall receive the gift of the Holy Spirit."* 

*1.* We "repent", which means to turn away from that which is wrong (what is not truly love towards Him and our neighbor) according to His Word, the Bible and turn towards walking in His good and just teachings and instructions (in the Bible) which show us how to truly love each-other and Him.
*2.* We put our faith in Yahushua the Messiah [commonly called "Jesus"] for the forgiveness of sins. He *is* faithful and just to forgive us our sins and cleanse us from ALL unrighteousness. 

I am not sure if you are familiar with the Bible and are a believer, but if you aren't then I would strongly encourage you to make this commitment to walk in true love according to what our Heavenly Father says in the Bible. It is the most important decision you will ever make.

Similar to the apostle Paul who wrote: *Rom 10:1  "Brethren, my heart's desire and prayer to God for Israel is, that they might be saved."* in the Bible, *my* prayer for America (and the world as a whole) is that they might be saved and walk in true love.

**Because then as we learn and grow in our faith in Yahweh, and share (in love) with others, we can know that with Yahweh working through us, we are ending "racism" one heart at a time. ** -Because a heart that is truly yielded to Yahweh will not longer look down on other "races" or individuals as inferior -they will be willing to lay their life down for others just as our Savior so graciously did for us. They will see others as Yahweh sees them: His *wonderful, special creation, sons and daughters whom He loves*. 

And *that* picture is very **beautiful** to me... especially contrasted with the turmoil going on in the world today.

Oh, and we will have the "shared goal" (as I just explained above) you were talking about *with the right motives* too. 

Again I respect you and others working on Pillow, whether you agree or disagree with this.  Blessings to you!

P.S: Thank for for developing Python-Pillow. 👍

**Comment by Almenon** [comment]
> When I see that saving lives clearly has nothing to do with the BLM movement and that it actually has a pro-abortion (pro-murder) agenda (along with a host of other un-biblical things), I can't agree with it in the least.

If you look through https://blacklivesmatter.com/about/ there is no mention of abortion. Nothing is stopping you from attending a BLM rally and a pro-life rally.

**Comment by Correct-Syntax** [comment]
Hello @Almenon, and thank you for your response to my comment. 

I really don't fully understand where you are coming from with your comment. It doesn't make sense, especially in the context the portion of my comment from which you quoted. I am not sure if you read the whole comment (yes, it's a bit long), but I encourage you to do so. If I didn't explain something well enough, please do let me know as I may not have been clear enough, I guess. :)

But as I understand it, I must respectfully disagree with you. 

> Nothing is stopping you from attending a BLM rally and a pro-life rally...

It would be quite hypocritical (and wrong) to do so, as the two oppose each-other. 

Please let me make a distinction: I don't find anything wrong with saying "black lives matter", because they do. **ALL lives matter!!** If you read my full comments above, I sure hope you can see that I tried to drill that point across.

Black lives DO matter, which is the reason I commented in the first place.

**Black lives matter (a lot) to our Heavenly Father and they matter a lot to me.** Some of people who have really encouraged me in my life have a darker skin color than I and I am *very* grateful for them. I don't see a darker (or lighter, for that matter...) skin tone as a bad thing, our differences are just a testament to our Heavenly father, Yahweh's creativity in creating us -which is great! :)

What I take offense to is what the BLM organization stands for and the riots as a whole with their violence and destruction, causing more loss of life (white AND black lives lost, I must mention...sadly) -all to show that black lives matter (?!). 

-That is not showing anyone, especially the people who *are* "racist" (even though they should **NOT** use it as an excuse) anything but violence (since when has burning a building down for no reason show life matters?) and it **doesn't work in the end**. 

**Why?** Man's heart (human nature) in it's fallen nature is drawn towards sin, towards hate for Yahweh our Heavenly Father and his neighbor. Man's *default* is hate and selfishness and so more hate and revenge to try to make things right does not solve it! 

*Jer. 17:9  "The heart is deceitful above all things, and desperately wicked: who can know it?"*

As long as people refuse to repent (turn away from sin) and turn to Yahushua the Messiah [commonly called "Jesus"] for the forgiveness of their sins (see my last comment), racism will *continue* to exist no matter how many human laws you set up or violent riots there are. 

Without a true *heart change* that only Yahweh through Yahushua can provide, man will always hurt one-another, be selfish, murder and hate. We must realize that we are a mess and we can do nothing about it ourselves. The only answer, as much as people like to reject it, is the love that comes only from Yahweh.

And that is really what everyone (including blacks) desire. Deep down inside ALL of us, we want **to be loved and to know that we are cared for**. 

And WE ARE *already* (though we may not realize it, or reject it): we are so valuable to our Heavenly Father that He was willing to give up His Son, a completely innocent man (and you want to talk about justice...), to die for us while we DON'T deserve it. 

*Jer 29:11  For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.*

**Just stop and think about it (even if you have heard this a thousand times).**

*Mat 11:28-30  Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.* 

The potter decides **the value** of the pot He made. Likewise, Yahweh our Heavenly Father *values us* because He made us and it doesn't matter what any human being says your worth is -*His* value for you is ALL that matters. If we are putting our worth and value in what another human being (politician or otherwise) thinks of us, we will be disappointed every time.

That is why I (respectfully) disagree with you, Alex when you wrote that:

> ...how you define things or why you are motivated by to pursue this goal matters significantly less than the achievement of the shared goal.

Two wrongs certainly don't make a right. It *does* matter how we define things and what we are motivated by. How could someone who is motivated by hate and the thirst for revenge END the injustices caused BY hate and revenge?? -(For example only. I am not thinking of anyone specific nor am I saying all BLM supporters are this way, I am just proving the point, I hope).

The things that the BLM promote do indeed show that they are not about life. You may disagree, but BLM does indeed promote sin, and while it may seem as though the "freedom" to do sin (without someone like me speaking out about it) is "freedom", it is actually the **greatest bondage and self-murder there is**. 

*Rom 6:23  For the wages of sin is death...*

But it does not have to be this way, because the full verse is:

*Rom 6:23  For the wages of sin is death; but the gift of Yahweh is eternal life through Yahushua Messiah [commonly called "Jesus"] our Master.*

*The love that you are looking for and the need to be cared for you WILL find only in a true relationship with our Heavenly father.*

*Psa 33:4-19  For the word of Yahweh is right; and all his works are done in truth. He loveth righteousness and judgment: the earth is full of the goodness of Yahweh. *

*By the word of Yahweh were the heavens made; and all the host of them by the breath of his mouth. He gathereth the waters of the sea together as an heap: he layeth up the depth in storehouses. Let all the earth fear Yahweh: let all the inhabitants of the world stand in awe of him. For he spake, and it was done; he commanded, and it stood fast.*

*Yahweh bringeth the counsel of the heathen to nought: he maketh the devices of the people of none effect. The counsel of Yahweh standeth for ever, the thoughts of his heart to all generations.* 

**Blessed is the nation whose Elohim ["God"] is Yahweh; and the people whom he hath chosen for his own inheritance.**

*Yahweh looketh from heaven; he beholdeth all the sons of men. From the place of his habitation he looketh upon all the inhabitants of the earth. He fashioneth their hearts alike; he considereth all their works.*

*There is no king saved by the multitude of an host: a mighty man is not delivered by much strength. An horse is a vain thing for safety: neither shall he deliver any by his great strength. Behold, the eye of Yahweh is upon them that fear him, upon them that hope in his mercy; To deliver their soul from death, and to keep them alive in famine.* 

It IS time that we end "systemic racism" and needless loss of life. But BLM is *not* the way. **Yahushua is the way** and the ONLY way. Nothing else can or will ever compare.

*John 14:6  Yahushua saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.*

Every life unjustly killed deserves justice. But in the cause to make things right, I cannot and will not join a movement such as BLM that has [nearly everything wrong.](https://townhall.com/columnists/ryanbomberger/2020/06/05/top-10-reasons-i-reject-the-blm-n2570105) And neither should you, because it's not the way to end racism. :)

I really do love you all (which is the reason I am taking the time to share this) and respect your views whether you agree or not. Thank you again, Alex. 👍

**Comment by XelaAl** [comment]
I also think that it is important to understand that all lives matter regardless of ethnicity, age, sexual orientation, etc. In most cases, black people are at a disadvantage when it comes to jobs, healthcare, education, and much more. It so happened that I worked on one project and wrote an article on the topic. So what can we do to change the situation? Of course, there have been protests in many countries and there are reparations and police reform. But still, people have to work on themselves to achieve diversity, equality, and inclusion in the workplace, at school, everywhere. I guess, it is better to inculcate better ethical standards in children.
