### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO ...>

### ISSUE THREAD

**Issue by Daddelion** [python-pillow/Pillow#4757]
I believe this could be a bug. When i load bytes from the lmdb database this is what i get back:
`
b'<PIL.PngImagePlugin.PngImageFile image mode=RGB size=500x530 at 0x7FB359CA1310>'
`
Which means that it is a Image object encoded in Bytes right?

But when I try to load it like this: 

`img = txn.get(image_key.encode());`
` img = Image.open(BytesIO(img));`

 
I get this error-message: `PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fbc8fed6680>`

Can someone help me?

**Comment by radarhere** [comment]
`b'<PIL.PngImagePlugin.PngImageFile image mode=RGB size=500x530 at 0x7FB359CA1310>'` - this looks wrong to me.

Here is an example of using Pillow to open a PNG file.

```
>>> from PIL import Image
>>> im = Image.open("Tests/images/hopper.png")
>>> im
<PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x10C0116D0>
```

This is what you have.
```
>>> str(im).encode()
b'<PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x10C0116D0>'
```

What you have is not an image. It is a bytestring describing a Python instance of an image.

If you would like further help, please provide a self-contained example of your code so that we can properly debug the situation.
