### ISSUE TITLE
Load a restricted subset of image formats

### ISSUE THREAD

**Issue by bemoody** [python-pillow/Pillow#4826]
Image parsing libraries are, and always have been, complicated pieces of software, with a requirement to (a) handle complicated input formats with a vast number of edge cases, and (b) operate as quickly and efficiently as possible.

This is a combination that leads to a lot of security bugs.

Pillow is no exception to this rule.

In many cases, when building an application, it makes sense to reduce the possible set of security bugs by only handling the input formats that you actually need to handle.

For example, if I only need to handle JPEG files, there is no reason for me to want to run a PostScript interpreter.  If I can design my program so it is *impossible* for the PostScript interpreter to be invoked, no matter what garbage input my program receives, then there's a huge category of security issues I don't need to worry about.

So, if I know what format the input file uses, is there a supported way to load it using *only* the required plugin?

There doesn't appear to be any documented way of doing this with Pillow.  As far as I can see, the only documented way of reading an image file is to use PIL.Image.open.  And if the input is malformed, then PIL.Image.open will potentially invoke *any* of the available format plugins, and will do so in an unpredictable order (depending on whether PIL.Image.init() or PIL.Image.preinit() is invoked first.)

An *undocumented* way would be to do this:
```python
PIL.Image.init()
image = PIL.Image.OPEN['JPEG'][0](fp, filename)
```
But this is pretty cryptic and I wouldn't assume this will always work with future Pillow versions.  This also skips the _decompression_bomb_check that is performed by PIL.Image.open.

**Comment by radarhere** [comment]
No, there isn't a documented way of doing this at the moment.

Here is my suggestion.
```python
import PIL.Image
PIL.Image.init()
PIL.Image.ID = ['JPEG']
im = PIL.Image.open("Tests/images/hopper.jpg")
```

**Comment by radarhere** [comment]
I've created #4833 as a suggested new API for this functionality.

**Comment by nulano** [comment]
I have created #4837 as an alternative to allow specifying the set of supported formats on a per-file basis.

Since both approaches have their pros and cons, I think there is merit in merging both PRs.

**Comment by hugovk** [comment]
Please could you summarise the pros and cons of each?

@bemoody Which of these approaches would you use? Would you use both?

(Release notes would be good, but we can add those after we merge one or both.)

**Comment by bemoody** [comment]
First, thank you @radarhere and @nulano for the quick responses, and
proposed fixes even. :)

Some advantages of changing the format list globally (#4833):

* If you only need to set the list of formats in one place in your
application, it may make security auditing easier.

* If your application calls into a third-party library that itself
uses Pillow for reading images, you can limit what image formats will
be recognized without having to modify that library.

Some advantages of setting a format list for each image (#4837):

* In a large application, different image formats might be required in
different contexts.  Switching the global format list could be
awkward, and might be infeasible for a multi-threaded program.

* A library itself can specify the set of supported formats, without
interfering with any possible use of Pillow by the calling
application.

So, I can certainly see merit to both, but #4837 seems like the
cleaner and more versatile approach and is probably what I'd prefer to
use.

**Comment by nulano** [comment]
I briefly mentioned it in my PR, but this is probably the better place to discuss it.

Limiting the set of formats in the `Image.init` call affects all `open`s, which leads to more readable code, and there is no chance of forgetting to specify the list in one of many `open` calls.

If there is an LTS version of a library or application that pins a specific version of Pillow to guarantee compatibility, or which runs on a no-longer-supported version of Python, and a CVE is discovered in that version, it would be easier to just disable the given format with a single `init` call instead of going through the entire project hunting down all `open` calls. 

However, this is impractical if the application requires loading different formats with a differing level of trust, e.g. a web server which lets users upload avatars only in PNG, but lets admins upload any image file to embed in the website content. It would be difficult to synchronise the `init` and `open` calls across threads. In this case, it would be more practical to specify `open(formats=["PNG"])` only in the avatar case and use the former approach for all other calls.
