### ISSUE TITLE
Brightness and Contrast Implementation Reversed

### ISSUE THREAD

**Issue by kensuncarestream** [python-pillow/Pillow#4853]
Hi,

I was reading the brightness and contrast source code. I think the implementation of adjusting contrast is actually adjusting brightness and adjusting contrast is actually adjusting brightness. Adjusting brightness is shifting while adjust contrast should be scaling.

I pasted related code below. 

```python
def blend(im1, im2, alpha):
    """
    Creates a new image by interpolating between two input images, using
    a constant alpha.::

        out = image1 * (1.0 - alpha) + image2 * alpha

    :param im1: The first image.
    :param im2: The second image.  Must have the same mode and size as
       the first image.
    :param alpha: The interpolation alpha factor.  If alpha is 0.0, a
       copy of the first image is returned. If alpha is 1.0, a copy of
       the second image is returned. There are no restrictions on the
       alpha value. If necessary, the result is clipped to fit into
       the allowed output range.
    :returns: An :py:class:`~PIL.Image.Image` object.
    """

    im1.load()
    im2.load()
    return im1._new(core.blend(im1.im, im2.im, alpha))


class _Enhance:
    def enhance(self, factor):
        """
        Returns an enhanced image.

        :param factor: A floating point value controlling the enhancement.
                       Factor 1.0 always returns a copy of the original image,
                       lower factors mean less color (brightness, contrast,
                       etc), and higher values more. There are no restrictions
                       on this value.
        :rtype: :py:class:`~PIL.Image.Image`
        """
        return Image.blend(self.degenerate, self.image, factor)


class Contrast(_Enhance):
    """Adjust image contrast.

    This class can be used to control the contrast of an image, similar
    to the contrast control on a TV set. An enhancement factor of 0.0
    gives a solid grey image. A factor of 1.0 gives the original image.
    """
    def __init__(self, image):
        self.image = image
        mean = int(ImageStat.Stat(image.convert("L")).mean[0] + 0.5)
        self.degenerate = Image.new("L", image.size, mean).convert(image.mode)

        if 'A' in image.getbands():
            self.degenerate.putalpha(image.split()[-1])


class Brightness(_Enhance):
    """Adjust image brightness.

    This class can be used to control the brighntess of an image.  An
    enhancement factor of 0.0 gives a black image. A factor of 1.0 gives the
    original image.
    """
    def __init__(self, image):
        self.image = image
        self.degenerate = Image.new(image.mode, image.size, 0)

        if 'A' in image.getbands():
            self.degenerate.putalpha(image.split()[-1])
```

Ken

**Comment by radarhere** [comment]
Hi. If I use one of [our test images](https://github.com/python-pillow/Pillow/blob/master/Tests/images/hopper.jpg),

![hopper](https://user-images.githubusercontent.com/3112309/90003774-e964d400-dcd7-11ea-8587-3cf4ba3a91fb.jpg)

and run the following code,

```python
from PIL import Image, ImageEnhance
im = Image.open("Tests/images/hopper.jpg")
ImageEnhance.Contrast(im).enhance(10).save("contrast.jpg")
ImageEnhance.Brightness(im).enhance(10).save("brightness.jpg")
```

I get contrast.jpg
![contrast](https://user-images.githubusercontent.com/3112309/90003810-f84b8680-dcd7-11ea-9285-aab59fa68cff.jpg)

and brightness.jpg
![brightness](https://user-images.githubusercontent.com/3112309/90003822-fda8d100-dcd7-11ea-9478-4369c3245bd3.jpg)

So in practice at least, i would conclude that Pillow is doing the correct thing.

**Comment by radarhere** [comment]
To explain the code itself, Pillow is creating a second image, `degenerate`.

For brightness, `degenerate` is black.
For contrast, it is a solid color described as `mean`, so it would be the average color taken from the image.

Pillow then `blend`s these with the original image, according to the factor.

You're aware that from the docstring for `Image.blend`, `out = image1 * (1.0 - alpha) + image2 * alpha`.

For values greater than 1, we would be multiplying the original by the value, while negatively multiplying the `degenerate` by almost that amount.

In the case of brightness, `degenerate` is black, zero, so that has no effect - we're simply multiplying the original image, making the pixels greater, or brighter.

In the case of contrast, multiplying the pixel values while subtracting the average has the effect of moving the pixels away from the average, creating more of a contrast.

Could you explain further why you feel this is wrong?
