### ISSUE TITLE
aarch64 ImportError: ELF load command alignment

### ISSUE THREAD

**Issue by sunny0315** [python-pillow/Pillow#4854]
I download the file from https://files.pythonhosted.org/packages/7b/fc/b8a0bbd86e98d4536165ff3b53f668e6bdfcc9d06185733a50fc090b2157/Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl, then install it Successfully: pip install Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl.
when I import it ,an error occurred as follws:
![image](https://user-images.githubusercontent.com/5812332/89990696-51ee8980-dcb5-11ea-8ded-435764994f2d.png)
My system environment is:
python 3.6.8
Linux version 4.18.0-80.7.2.el7.aarch64 (mockbuild@aarch64-01.bsys.centos.org)
centos 7.6
gcc version 7.4.0 (GCC) 

how to solve this problem?

**Comment by radarhere** [comment]
Hi. For the moment, I think I can only recommend that you try compiling Pillow from source.

As for a proper solution, it looks like this is being discussed over at https://github.com/numpy/numpy/issues/16677

**Comment by radarhere** [comment]
Hi. This sound now be fixed in patchelf 0.12, and manylinux has upgraded to that new release. This in turn should mean that it is fixed in the wheels from the next Pillow release.

In the meantime, I've put together [Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl.zip](https://github.com/python-pillow/Pillow/files/5146373/Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl.zip). If you download and install it, does it work for you?

**Comment by sunny0315** [comment]
I have installed the version of 5.2.0 and it works well.

**Comment by hugovk** [comment]
Closing this as fixed in patchelf and manylinux, and we can re-open if needed.
