### ISSUE TITLE
multiline_textsize and textsize functions aren't working

### ISSUE THREAD

**Issue by makisukurisu** [python-pillow/Pillow#4879]
### What did you do?
Basically I just used them.

### What did you expect to happen?
Output *size of string*

### What actually happened?
I got error from python compiler:

> AttributeError: module 'PIL.ImageDraw' has no attribute 'multiline_textsize'

### What are your OS, Python and Pillow versions?

* OS: Windows 10 2003
* Python: 3.8.5
* Pillow: 7.2.0 (installed from PyPl via pip, and it says that 7.2.0 is the last one available)

```python
from PIL import Image, ImageDraw, ImageFont

fnt = ImageFont.truetype(font = "*font_name*.ttf", size = 16, encoding = "unic")

print(ImageDraw.multiline_textsize("OTP_TEST", font=fnt))
```

![image](https://user-images.githubusercontent.com/49622129/90677621-49262680-e266-11ea-9751-f64d1464b477.png)

All other lines are commented that is why error line is number 10

I checked module file and definition of this function appears in it. (I mean on my PC)
P.S. I'm sorry if this is my problem, and not PIL.
P.P.S. multiline_text function works just fine, and it's very confusing for me.

**Comment by hugovk** [comment]
Try something like this:

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new(mode="RGB", size=(300, 100))
draw = ImageDraw.Draw(im)

fnt = ImageFont.truetype(font="Tests/fonts/DejaVuSans.ttf", size=16, encoding="unic")

print(draw.multiline_textsize("OTP_TEST", font=fnt))
```
```
(81, 15)
```

**Comment by radarhere** [comment]
As the previous post shows, [`multiline_textsize`](https://github.com/python-pillow/Pillow/blob/8deaebd5e0f1e00edfa02514a86fa3b52975a4f7/src/PIL/ImageDraw.py#L431) belongs to the class, not the module.

If `multiline_text` works for you, then I'm guessing you're calling it in a different way. If you think not, please post a complete code example showing use of both.

**Comment by nulano** [comment]
The confusion could be caused by the fact that the method `multiline_textsize` is referred to as [`ImageDraw.multiline_textsize` in the docs](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.multiline_text), where `ImageDraw` refers to the class `PIL.ImageDraw.ImageDraw`, but could be easily confused for the module.

For comparison, the module function `Draw` is referred to as [`PIL.ImageDraw.Draw`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.Draw) (with the full name).

I'm not sure if there is a reasonable way to clarify this distinction in the docs.

**Comment by hugovk** [comment]
There's some examples at the top of https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html, we can add more if it'd help, and maybe to https://pillow.readthedocs.io/en/stable/handbook/tutorial.html as well.

**Comment by makisukurisu** [comment]
@nulano , your solution worked, thanks. I'm closing this issue.

But, IMO it would be better for docs to have full name of this function. Or an example that shows, how to use it properly.
