### ISSUE TITLE
Automatically rotates image based on EXIF, unexpected behaviour

### ISSUE THREAD

**Issue by Divjyot** [python-pillow/Pillow#5047]
### What did you do?
**Step 1**
I have an [image](https://raw.githubusercontent.com/Divjyot/funpyprojects/master/IMG_O3.jpg), which I open using PILLOW as following:
 
```python
from PIL import Image
import requests
import io

response = requests.get(path)
img = Image.open(io.BytesIO(response.content))
```
I originally had same image on my local disk, which I opened it similar way as following:

```python
with open(image_name, "rb") as f:
    img_bytes = f.read()
img = Image.open(io.BytesIO(img_bytes))

```
Anyhow, I got the img pillow object from file's bytes either from url or local disk file.

**Note: The following is screenshot of original image - for reproducing the error please download the image from the source mentioned above.**
![image](https://user-images.githubusercontent.com/14040664/99742642-a3fa4300-2b1f-11eb-8f79-e0dd9284915d.png)

**Step 2**
I found that the EXIF data Orientation tag's value is 3 which is correct - i.e. rotated ~180 degrees for a human eye if you try to read the image.
```python
exif=dict((ExifTags.TAGS[k], v) for k, v in img._getexif().items() if k in ExifTags.TAGS)
```
```python
{
'ExifVersion': b'0231',
'Orientation': 3,
....
}
```

### What did you expect to happen?
I expected the pil image printed to be look like as original NOT rotated. That is I expected it to be like:
**Note: The following is screenshot of image - for reproducing the error please download the image from the source mentioned above.**
![image](https://user-images.githubusercontent.com/14040664/99742642-a3fa4300-2b1f-11eb-8f79-e0dd9284915d.png)

### What actually happened?
I printed/display-ed the pillow image in Jupyter Lab and it showed as UNEXPECTED rotated to normal position which was not SAME as original image as following:
```python
display(img)
```
**Note: The following is screenshot of image - for reproducing the error please download the image from the source mentioned above.**
![image](https://user-images.githubusercontent.com/14040664/99742775-ed4a9280-2b1f-11eb-92fb-b1b404930265.png)

### What are your OS, Python and Pillow versions?

* OS: Windows 
* Python: 3.8.6
* Pillow:  8.0.0
* Pip version:  19.3.1
* Jupyter Lab

```python
from PIL import Image
import requests
import io

path = "https://raw.githubusercontent.com/Divjyot/funpyprojects/master/IMG_O3.jpg"
response = requests.get(path)
img = Image.open(io.BytesIO(response.content))
exif=dict((ExifTags.TAGS[k], v) for k, v in img._getexif().items() if k in ExifTags.TAGS)
display(img)
```

### What I tried to resolve the issue?
In order to get pillow to get me the original image (i.e. NOT rotated acc. to EXIF Orientation tag), I ran following:

```python
img = ImageOps.exif_transpose(img)
```

But I DO NOT expected PILLOW to automatically rotate the image based on EXIF information. Wherever I have read, community or git issues, it was mentioned that PILLOW DO NOT rotate image by default, however I found the opposite.  I certainly DO NOT EXPECT ```ImageOps.exif_transpose(img)``` to give me original picture.

Please let me know if there is any other information needed.

**Comment by radarhere** [comment]
I agree with the expectation that Pillow does not rotate the image - so much so that I still think it isn't.

For comparison, take https://github.com/python-pillow/Pillow/blob/master/Tests/images/hopper_orientation_3.jpg.

The macOS application Preview is showing that it has an orientation that rotates it 180 degrees, to be upright. So I can conclude that it should normally be upside down.
![Screen Shot 2020-11-21 at 12 01 23 am](https://user-images.githubusercontent.com/3112309/99802992-c4acb200-2b8c-11eb-9d53-a77d8adf1662.png)
If I load it into https://www.verexif.com/en/, and 'Remove Exif', then I can see that it is indeed upside down.

So if I take your image image and load it into https://www.verexif.com/en/, and 'Remove Exif', then... it is downloaded right side up.

I think that the raw image data is right side up, and that the orientation tag is turning it upside down. This isn't what you expect orientation tags to do as a human, sure, but I don't think there is a problem here - I think your raw image data is right side up.

**Comment by radarhere** [comment]
Let us know if you have any further questions, or disagree with my response - but for the moment at least, I'm closing this, as there seems to a clear answer.

**Comment by wasdee** [comment]
FYI https://stackoverflow.com/a/58116860/3969942
