### ISSUE TITLE
ImageDraw.Draw has incorrect type hint

### ISSUE THREAD

**Issue by david-sen** [python-pillow/Pillow#5095]
`ImageDraw.Draw` returns `None` according to the type hint. The documentation also doesn't mention any return type. However, it  actually returns `ImageDraw.ImageDraw`, unless I'm mistaken.

**Comment by hugovk** [comment]
The docs include examples showing `ImageDraw.Draw()` returning a drawing context:

```python
# get a drawing context
d = ImageDraw.Draw(out)
```

https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#example-draw-multiline-text

The reference:


> `ImageDraw.Draw(im, mode=None)`
> 
> Creates an object that can be used to draw in the given image.
> 
> Note that the image will be modified in place.
> 
> Parameters
> **im** - The image to draw in.
> **mode** - Optional mode to use for color values.  For RGB images, this argument can be RGB or RGBA (to blend the drawing into the image).  For all other modes, this argument must be the same as the image mode.  If omitted, the mode defaults to the mode of the image.

https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.Draw


We can add an explicit `returns` to the docs (in `docs/reference/ImageDraw.rst`).



We don't have type hints in the source, but I see this in PyCharm, which looks about right (the `-> ImageDraw` part):

![image](https://user-images.githubusercontent.com/1324225/102353667-0c6b0180-3fb2-11eb-99ba-a7c3d536a612.png)

Where do you see a `None` hint? Please could you include a screenshot? Thanks!

**Comment by david-sen** [comment]
Ok, my mistake. I was seeing the incorrect return type in VS Code with the Pylance extension. Turns out Pylance actually has some bundled type stubs and they are wrong for `ImageDraw.Draw`, so I'll submit an issue with Pylance. Thanks for your help!

**Comment by davetapley** [comment]
@david-sen did you ever open an issue elsewhere? I'm still seeing this in VS Code 😞 

![image](https://user-images.githubusercontent.com/48232/124685982-27865b80-de87-11eb-9d60-36d99fb8239f.png)

**Comment by masterkain** [comment]
seeing that too

**Comment by radarhere** [comment]
From what I can see, the incorrect return value lived in https://github.com/jakebailey/python-type-stubs (https://github.com/jakebailey/python-type-stubs/blob/bf17774a898461a1632e9779317b5e191eb6da8e/PIL/ImageDraw.pyi#L11), but the stubs have since [migrated](https://github.com/jakebailey/python-type-stubs#upstreamed-libraries) to https://github.com/python/typeshed where it is correct (https://github.com/python/typeshed/blob/571cc6d77ad85c6b3c12f546f8b62c69f37da402/stubs/Pillow/PIL/ImageDraw.pyi#L149)

So perhaps you just need to update some part of your software?
