### ISSUE TITLE
Disable kerning without external dependency

### ISSUE THREAD

**Issue by josephernest** [python-pillow/Pillow#5191]
Hi! It's rather complex to use "no kerning":

    ImageDraw.text(..., features=["-kern"])

when drawing TrueType font text on an image with [`ImageDraw.text`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text).

Indeed, on Windows, we have to:

* use unofficial builds of `libraqm` such as https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow, and it's not mentioned in the documentation

* we can find some info here: https://stackoverflow.com/questions/62939101/how-to-install-pre-built-pillow-wheel-with-libraqm-dlls-on-windows

* putting these two .DLL files in `C:\Python37\DLLs\` doesn't work (shouldn't .DLL files be in this folder? as an example, `sqlite3.dll` is in this folder on a default Python install), we have to put them in `C:\Python37\` along `python.exe` (which is not really great) or in `C:\Windows\System32`.

Since we're just *disabling* a feature (kerning), is it really necessary to import `libraqm`?

**Comment by nulano** [comment]
As I noted in #4724, when using basic layout (i.e. without Raqm installed or with `layout_engine=ImageFont.LAYOUT_BASIC`), kerning is currently non-functional anyway, at least since #2576, when Raqm was added. In the code quoted below, the `PIXEL` macro is dividing all values by 64, but this is then repeated in later functions when reading the result, rounding all values to zero (except for massive font sizes). I meant to open a separate issue for this but forgot... 😕
https://github.com/python-pillow/Pillow/blob/c9745f4b517127bd5090cc381aa1e67c0d780499/src/_imagingft.c#L578-L585

So the answer to "Since we're just disabling a feature (kerning), is it really necessary to import libraqm?" is no :smile:.

---

> use unofficial builds of libraqm such as https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow, and it's not mentioned in the documentation

I agree it's not very user-friendly, but you are welcome to build Raqm yourself... (I'm not saying you should, but you can if you **really** want an "official" version.) If you run the scripts for Windows test builds (`winbuild` directory), you will get a build of `libraqm` in the `winbuild/build/bin` subdirectory.

The Windows documentation could be improved, however...

>we can find some info here: https://stackoverflow.com/questions/62939101/how-to-install-pre-built-pillow-wheel-with-libraqm-dlls-on-windows
>
>Putting these two .DLL files in C:\Python37\DLLs\ doesn't work (it should! it works for Sqlite3.dll for example), we have to put them in C:\Python37\ along python.exe (which is not really great) or in C:\Windows\System32

I think the expectation is that Raqm should be installed in the system (i.e. in a `PATH` directory). The DLL is just loaded with the WinAPI `LoadLibrary` function, which looks in directories as defined [in the Microsoft documentation](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications). From that list, I would conclude that putting it in the `C:\Python37\` is the preferred option for most people. 

I'm not sure how well adding the `C:\Python37\DLLs\` directory would work; no other Python version (that I'm aware of) has it. Therefore it could break support for PyPy, Python on MSYS2/MinGW, Cygwin, ..., not to mention anyone who has been putting it next to python.exe.

PS: I'm not sure what you mean by the sqlite3 example, but I already have `sqlite3.dll` in the DLLs directory and I didn't add it manually.

**Comment by josephernest** [comment]
Thanks a lot for your answer @nulano!

In the meantime I found a solution for what I was looking for. My goal was to draw text with *exactly* the same output than the Windows user interface. As mentioned by @Ned in [this post](https://stackoverflow.com/questions/5748973/why-is-my-truetype-font-of-size-11-rendering-different-than-windows/5749865#5749865):

> Font rendering is a complex and subtle process, and one that has been implemented a number of times. In your case, PIL and Windows look different because they are using completely different font rendering engines. Windows uses its built-in rendering, and PIL is using the Freetype it was compiled with.

so the solution was simply to use WinAPI, with the method detailed in [python: use windows api to render text using a ttf font
](https://stackoverflow.com/questions/5750887/python-use-windows-api-to-render-text-using-a-ttf-font).

PS: if you're curious I wanted to have *exactly* the same font rendering as the Windows user inteface, here is the reason ;): https://github.com/asweigart/pyautogui/issues/521
