### ISSUE TITLE
How to build for only c/c++ ? 

### ISSUE THREAD

**Issue by LightSun** [python-pillow/Pillow#5267]

**Comment by radarhere** [comment]
Hi. This is a Python library, and the intention is not for users to use the underlying C code directly.

See #4532 or #4863 for further discussion of this.

https://github.com/python-pillow/Pillow/issues/4532#issuecomment-618255798)
> Pillow makes a commitment to stable public interfaces, which are defined at the Python layer. The C interfaces are explicitly internal, and no effort is made to keep them stable even between minor releases, and no support or warning is given when they change. (IIRC, there are/were people using the internal interfaces, but they've always been explicitly on their own with that)

**Comment by radarhere** [comment]
Did those issues answer your question, or is there anything else you would like to know?

**Comment by LightSun** [comment]
@radarhere I want to do the PIL image's resize in c++ , Do you have any suggestions?

**Comment by radarhere** [comment]
As far as resizing, I can tell you to start with `ImagingResample` in https://github.com/python-pillow/Pillow/blob/main/src/libImaging/Resample.c.

I don't know how you plan to get the image data into the function, and what you plan to do with it afterwards, but that would also be a challenge. Again, this is a Python library, and the intention is not for users to use the underlying C code directly. This is open source, so you can do it, it's just at your own risk.

I would suggest you consider using OpenCV instead, since that actually does offer a C API - https://learnopencv.com/image-resizing-with-opencv/
