### ISSUE TITLE
Django project unable to recognize Pillow in MacBook M1 Air

### ISSUE THREAD

**Issue by rahul7011** [python-pillow/Pillow#5439]
### What did you do?
I'm trying to run command `python manage.py makemigrations` but every time error pops up 

> Cannot use ImageField because Pillow is not installed.

But Pillow is already installed.
### What did you expect to happen?
To makemigratons
### What actually happened?
error pops up every time whenever I tried to use makemigrations command
### What are your OS, Python and Pillow versions?

* OS: MacOS BigSur Version:11.2.3
* Python: 3.8.2
* Pillow: 8.2.0

command
`python manage.py makemigrations`

```
SystemCheckError: System check identified some issues:

ERRORS:
posts.Post.thumbnail: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
```

Note:
I have already tried re-installing Pillow several times, installing previous Pillow versions but so far nothing worked .

for reference:
`pip show Pillow`

```Name: Pillow
Version: 8.2.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: /Users/rahulmaurya/Documents/Django/basic code/BLOG/env/lib/python3.8/site-packages
Requires: 
Required-by: 
```

`pip show Django`

```
Name: Django
Version: 3.2
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD-3-Clause
Location: /Users/rahulmaurya/Documents/Django/basic code/BLOG/env/lib/python3.8/site-packages
Requires: sqlparse, pytz, asgiref
Required-by: 
```

**Comment by radarhere** [comment]
If you just run `python -c 'import PIL;print(PIL.__version__)'`, does that successfully print out the version? I'm trying to see whether this is a problem with Django recognising Pillow, or whether this is just a problem installing Pillow.

**Comment by rahul7011** [comment]
On running : `python -c 'import PIL;print(PIL.__version__)'` 
error occurs:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PIL
```

**Comment by radarhere** [comment]
Thanks. Ok, instead of running `pip install Pillow`, could you try `python -m pip install Pillow`? If you have multiple versions of Python on your computer, then `pip` may have been using a different one that the Python you were running.

My hope is that when you run the command, you will see Pillow install, and after that, Django will find Pillow.

**Comment by rahul7011** [comment]
After running `python -m pip install Pillow` Django is still showing the same error
> posts.Post.thumbnail: (fields.E210) Cannot use ImageField because Pillow is not installed.

and yes,My computer is having both the versions of python but I am working in a separate environment with python3
<img width="832" alt="Screenshot 2021-04-26 at 10 09 42 AM" src="https://user-images.githubusercontent.com/52202163/116029782-aedd7480-a677-11eb-9e6c-af6f0eb7598a.png">

**Comment by radarhere** [comment]
Wait, so can you run `python -c 'import PIL;print(PIL.__version__)'` without an error now?

**Comment by rahul7011** [comment]
yes Now on running this command it's showing the output 8.2.0

**Comment by radarhere** [comment]
Ok, does `python -c 'from PIL import Image'` show any errors? I ask because [that's what Django is doing.](https://github.com/django/django/blob/4e5bbb6ef2287126badd32842b239f4a8a7394ca/django/db/models/fields/files.py#L386-L397)

**Comment by rahul7011** [comment]
it's showing the following error after running the command

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rahulmaurya/Documents/Django/basic/07. Build a blog with Django/final_code/env/lib/python3.8/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/rahulmaurya/Documents/Django/basic/07. Build a blog with Django/final_code/env/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): Symbol not found: _jpeg_resync_to_restart
  Referenced from: /Users/rahulmaurya/Documents/Django/basic/07. Build a blog with Django/final_code/env/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/rahulmaurya/Documents/Django/basic/07. Build a blog with Django/final_code/env/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so
```

**Comment by radarhere** [comment]
Thanks.

A disclaimer. "[Python 3.8.7 is not yet fully supported on macOS 11 Big Sur.](https://www.python.org/downloads/release/python-387/)" (and you're actually using earlier than that) - so the official Python guideline would be to use Python 3.9 instead, as "[3.9.1 is the first version of Python to support macOS 11 Big Sur.](https://www.python.org/downloads/release/python-391/)"

Because of this, we don't provide prebuilt Python 3.8 wheels to PyPI, and I imagine that isn't helping you. If you do want to use Python 3.8, you could try downloading [Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl.zip](https://github.com/python-pillow/Pillow/files/6377137/Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl.zip), expanding the zip, moving into the directory and then running `python -m pip install Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl`
