### ISSUE TITLE
Error message when drawing a rectangle on a grayscale image

### ISSUE THREAD

**Issue by ivan-marroquin** [python-pillow/Pillow#5523]
### What did you do?
I would like to draw a rectangle on a grayscale image. thanks for your help

### What did you expect to happen?
Drawing a rectangle on a RGB image works as expected but it fails when using a grayscale image

### What actually happened?
I get the following error message:

PIL  (255, 255, 0) <class 'tuple'>   L <class 'str'>
```
Traceback (most recent call last):

  File "<ipython-input-12-e10de1d28bc4>", line 1, in <module>
    draw.rectangle((0,20,0,30), fill=None, outline=(255,255,0))

  File "/home/ivan/python_3.6.5/lib/python3.6/site-packages/PIL/ImageDraw.py", line 192, in rectangle
    ink, fill = self._getink(outline, fill)

  File "/home/ivan/python_3.6.5/lib/python3.6/site-packages/PIL/ImageDraw.py", line 113, in _getink
    ink = self.draw.draw_ink(ink, self.mode)

TypeError: function takes exactly 1 argument (3 given)
```

### What are your OS, Python and Pillow versions?

* OS: Linux/Windows
* Python: 3.6.5
* Pillow: 5.2.0

```python
from PIL import Image, ImageDraw, ImageOps

newimage= Image.new('RGB', (680, 800), color= (255,0,255))
draw= ImageDraw.Draw(newimage)
draw.rectangle((0,20,0,30), fill=None, outline=(255,255,0)) # works as expected

grayimage= ImageOps.grayscale(newimage)
draw= ImageDraw.Draw(grayimage) 
draw.rectangle((0,20,0,30), fill=None, outline=(255,255,0)) # produces error
```

**Comment by radarhere** [comment]
Hi. If an image is in mode L, then it doesn't have red, green and blue colors. Instead, it has just a single grayscale color. So instead of trying to draw `(255, 255, 0)` on your L image, you could either
- use a grayscale color - `draw.rectangle((0,20,0,30), fill=None, outline=255) `
- if you want to draw yellow, convert the image to RGB first and then try again - `grayimage = grayimage.convert("RGB")`

#5504 will be a part of the next Pillow release, changing the error message from "TypeError: function takes exactly 1 argument (3 given)" to a clearer "color must be int or single-element tuple".

**Comment by ivan-marroquin** [comment]
Thanks a lot for the clarification

**Comment by radarhere** [comment]
Shall I close this issue then?

**Comment by ivan-marroquin** [comment]
Thanks for all!
