### ISSUE TITLE
Issue with fontmode = 'L' when drawing text with TrueType font

### ISSUE THREAD

**Issue by sacrelee** [python-pillow/Pillow#5529]
Hi, i am writing a program to process the mono bitmap, when i try to draw text on the image, i found "black text white background" is not good as "white text black background":

![图片](https://user-images.githubusercontent.com/4127567/121205193-093e3780-c8aa-11eb-9882-ca6b6e3e38b2.png)

here is my code:
```python
        base_img = Image.new(mode='1', size=(300, 800))
        draw = ImageDraw.Draw(im=base_img, mode='1')
        draw.fontmode = 'L'
        draw.text(......)
``` 
i found the issue is from "fontmode = 'L'", i have tried "fontmode = '1'", but that's not what i want, please tell me what's wrong with my code. 

sorry for my english, thanks very much.

**Comment by nulano** [comment]
Hi. You are creating an image in 1bit format (`mode='1'`) but drawing text in 8bit format (`draw.fontmode='L'`).

This works by first creating an internal bitmap for the text in 8bit format `L` and then converting it into 1bit format `1` when drawing it onto your image. This conversion is done by converting every non-black pixel (including gray) of the text to white.

Therefore:

* When drawing black text on white background, only the fully opaque pixels of the text are drawn as black, the rest remains white.
* When drawing white text on black background, all non-fully-transparent pixels of the text are drawn as white, the rest remains black.

For drawing text on a 1bit image you should be using `fontmode='1'` for best results. If you would like the text to be thicker, it is probably best to use a bold font (e.g. `arialbd.ttf` instead of `arial.ttf`).

You can also create an 8bit grayscale image using `Image.new("L", (300, 800))` instead, which works with `fontmode="L"` as expected.

**Comment by sacrelee** [comment]
@nulano thanks.
