### ISSUE TITLE
Symbol not found: _clock_gettime error on OS X 10.11

### ISSUE THREAD

**Issue by drfraser** [python-pillow/Pillow#5604]
### What did you do?

I set up a new environment to test dask/scikit-learn, so Pillow (8.3.1) and bokeh (2.3.3) got installed as well. I did not give any thought to the version numbers.

### What did you expect to happen?

No problems running my Dask code, e.g. able to access the dashboard at 127.0.0.1

### What actually happened?

Dask complained about bokeh not being installed. So I looked at the code and their logic infers bokeh isn't installed if the "import distributed.dashboard.scheduler" line fails. I tried that in a Python shell and got this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/distributed/dashboard/scheduler.py", line 11, in <module>
    from .components.nvml import gpu_doc  # noqa: 1708
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/distributed/dashboard/components/__init__.py", line 7, in <module>
    from bokeh.layouts import column, row
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/bokeh/layouts.py", line 27, in <module>
    from .models.layouts import Box, Column, GridBox, LayoutDOM, Row, Spacer, WidgetBox
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/bokeh/models/__init__.py", line 31, in <module>
    from ..core.property.dataspec import expr, field, value  # Legacy API
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/bokeh/core/property/dataspec.py", line 35, in <module>
    from .visual import DashPattern, FontSize, HatchPatternType, MarkerType
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/bokeh/core/property/visual.py", line 28, in <module>
    import PIL.Image
  File "/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/PIL/Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: dlopen(/Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/PIL/.dylibs/liblzma.5.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/Phil/projects/testing/venv/lib/python3.8/site-packages/PIL/.dylibs/liblzma.5.dylib
```

Looking at the closed issues, it obviously seems like the same as the problem back in 2018 in regards to OS X 10.11.  I have another Dask environment that is using Pillow 8.2.0 without any issues. So when I downgraded to Pillow 8.2.0, things started working. The best solution would be to upgrade OS X, but I can't right now. Is there any scheduled date when 10.11 support will be dropped?

### What are your OS, Python and Pillow versions?

* OS: X 10.11
* Python:  3.8.10
* Pillow: 8.3.1

**Comment by radarhere** [comment]
I have a [theory](https://github.com/matthew-brett/multibuild/pull/406/commits/d451c58f89b270d3c67130cae27939305468e637) about why this is. Does Pillow 8.3.0 work for you?

**Comment by drfraser** [comment]
Yes, 8.3.0 worked; there were no errors.

**Comment by radarhere** [comment]
Thanks for checking.

Oh, no, this isn't about what you have on your system. It's about how we're building the wheels. The link was more of a note for myself. To explain, your error mentions liblzma, related to xz. Between Pillow 8.3.0 and 8.3.1, we inadvertently changed to installing xz through Homebrew instead of building it from source. This meant that our deployment target of 10.10 wasn't respected - the error you're seeing was not intended.

There are no current plans to drop support for 10.11.  I've created https://github.com/python-pillow/pillow-wheels/pull/211 to resolve this. If merged, then the next Pillow release should be fixed.

If you're interested, here is a wheel generated from that PR - [Pillow-8.3.1-cp38-cp38-macosx_10_10_x86_64.whl.zip](https://github.com/python-pillow/Pillow/files/6802074/Pillow-8.3.1-cp38-cp38-macosx_10_10_x86_64.whl.zip). You could test it out by expanding the zip and then running `pip install Pillow-8.3.1-cp38-cp38-macosx_10_10_x86_64.whl`

**Comment by drfraser** [comment]
I finally got a chance to test the wheel - no problems, so I am closing this issue
