### ISSUE TITLE
RGBA resize deletes data

### ISSUE THREAD

**Issue by MichaelDoron** [python-pillow/Pillow#5616]
### What did you do?

I tried to resize an RGBA image.

### What did you expect to happen?

The resize should not delete three dimensions of the data.

### What actually happened?

The resize deleted three dimensions of the data.

### What are your OS, Python and Pillow versions?

* OS: Ubunto 18.04, also reproduced on macOS Big Sur
* Python: 3.7.6
* Pillow: 8.3.1

```python
from PIL import Image
import numpy as np

array = np.ones((10,10,4)).astype(np.uint8)
image = Image.fromarray(array)
resized_image = image.resize((3,3))
resized_4_channels = np.array(resized_image)

assert np.sum(resized_4_channels[:,:,:3]), 'Resizing an RGBA image filled with ones results in the first three dimensions containing only zeros'

```

**Comment by nulano** [comment]
This looks like a duplicate of #4516, with the answer that this is expected behaviour: https://github.com/python-pillow/Pillow/issues/4516#issuecomment-608330507

As for why you get zero and not some other value, note that premultiplying an 8bit 1 value with alpha 1 results in 1*1=1 16bit value, which is zero when converted back to 8bit resolution: 1/256=0.

**Comment by MichaelDoron** [comment]
Got it, thanks!
