### ISSUE TITLE
Slightly different DPI value when saving PIL Image as bytes with different format (PNG, JPEG)

### ISSUE THREAD

**Issue by EucliTs0** [python-pillow/Pillow#5623]
Hello, I have installed Pillow 8.3.1 and I have encountered the following issue:

For instance, I give a custom dpi value to save in the image and after I save this image as bytes, having as
format PNG or JPEG.
When I load the bytes, I have slightly different DPI value depending on the given format
```python
import PIL
import io

img_file = 'img2.png'

img = PIL.Image.open(img_file).convert('RGB')
img.info['dpi'] = (300, 300)

img_byte_arr = io.BytesIO()
img.save(img_byte_arr, format='PNG', dpi=img.info['dpi'])
#img.save(img_byte_arr, format='JPEG', dpi=img.info['dpi'])

img_new = PIL.Image.open(img_byte_arr)
print(img.info['dpi'])
print(img_new.info['dpi'])

# With format='PNG'
# (300, 300)
# (299.9994, 299.9994)

# With format='JPEG'
# (300, 300)
# (300, 300)

```
I would expect, regardless the format type, to have the exactly the same DPI value with the one I save the image.

* OS:  Distributor ID:	Ubuntu
           Description:	Ubuntu 20.04.2 LTS
           Release:	20.04

* Python: 3.8.5
* Pillow: 8.3.1
![img2](https://user-images.githubusercontent.com/11181100/126279458-e7418c1d-11e6-4ab1-8248-667905e87402.png)

**Comment by radarhere** [comment]
For PNG, the pHYs chunk is used to specify the DPI - http://www.libpng.org/pub/png/book/chapter11.html#png.ch11.div.8

If you look at https://www.w3.org/TR/PNG-Chunks.html, you see that the only known unit for this is a metre, and that we have to express that as an integer. It also states that "one inch is equal to exactly 0.0254 meters."

So 300 dots per inch = 300 / 0.0254 = 11811 dots per metre. That's the value that we should save.

However, when it converted back to DPI, 11811 * 0.0254 = 299.9994. The value is not quite the same, because we had to round to an integer number of metres.

Well, what if we increased it by one? 11812 * 0.0254 = 300.0248. Not exactly either.

So hard as you might find it to believe - this isn't a bug. You can't have a PNG with exactly 300 DPI.

**Comment by EucliTs0** [comment]
@radarhere Thank you for the explanation :+1:
