### ISSUE TITLE
Assign mode to fromarray

### ISSUE THREAD

**Issue by Erhie** [python-pillow/Pillow#5707]
### What did you do?
```python
origPil = Image.open( filename )
origPil_mode = origPil.mode
img_array = np.asarray(origPil)

img_to_show = Image.fromarray( img_array , mode = origPil_mode )
from PIL import ImageShow
ImageShow.show(img_to_show)
```

### What did you expect to happen?
that there is **no** warning belonging mode in `Image.fromarray( img_array , mode = origPil_mode )`

### What actually happened?
**Warning:**
```
Argument of type "str" cannot be assigned to parameter 
"mode" of type
"Literal['1', 'CMYK', 'F', 'HSV', 'I', 'l', "LAB', 'P', 'RGB', 'RGBA', 'RGBX', 'YCbCr'] | None"
in function "fromarray"
   Type "str" cannot be assigned to type 
"Literal['1', "CMYK', 'F', 'HSV', 'I', 'L', 'LAB', 'P', 'RGB', 'RGBA', ''RGBX', 'YCbCr'] | None"
```
* OS:  Windows 10
* Python:  Python 3.8
* Pillow: 8.3.2

**Comment by radarhere** [comment]
Hi. I'm not able to replicate the warning, so here are a few questions.
- What version of numpy are you using? `np.__version__`.
- I understand that you haven't shown us the `import` statements and where you are setting `filename`, but that's it? You're able to reproduce this problem with just this code block in it's own file, without other code that you're written?
- Are you running this from Visual Studio or something like that, rather than from the command line? If you run it from the command line outside of Visual Studio, does the warning go away? I'm not trying to dismiss your problem, just wanting to better understand its origin.

**Comment by Erhie** [comment]
I use VS Code with extension Pylance
and with further debugging I see there is a prototype for fromarray
def fromarray(obj, mode: _Mode | None = ...) -> Image: ...
and _Mode is defined as
_Mode = Literal["1", "CMYK", "F", "HSV", "I", "L", "LAB", "P", "RGB", "RGBA", "RGBX", "YCbCr"]

Has  Pylance generated the file Image.pyi itself?

ANd numpy has version 1.20.3

**Comment by radarhere** [comment]
As you've likely gathered, we don't provide typing for `fromarray` - https://github.com/python-pillow/Pillow/blob/e122e8f3a663efe0fcdf604f189b5695ef9bf227/src/PIL/Image.py#L2799

According to https://github.com/microsoft/pylance-release/issues/659, Pylance comes bundled with .pyi files for PIL, and https://github.com/microsoft/pylance-release/issues/994 was an issue where a user reports a typo in a PIL stub.

However, looking at https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md, I see that on July 6,
> The bundled PIL stubs have been removed, as they have been merged into typeshed's Pillow stubs.

So I think that the problem actually lies in https://github.com/python/typeshed - [`def fromarray(obj, mode: _Mode | None = ...) -> Image: ...`](https://github.com/python/typeshed/blob/18d4868fce17ff8f7eb02dde3b95cc2b4a4b7ff3/stubs/Pillow/PIL/Image.pyi#L224)

**Comment by radarhere** [comment]
@Erhie is that enough information for you to take it from here?

**Comment by Erhie** [comment]
Thank You!
 I aked also:
 https://github.com/microsoft/pylance-release/issues/1798
and the next step is to ask 
https://github.com/python/typeshed
