### ISSUE TITLE
Conversion P to L wrong?

### ISSUE THREAD

**Issue by CTPaHHuK-HEbA** [python-pillow/Pillow#5728]
```python
from PIL import Image

img = Image.open('p.png')
print('P->L: ', img.convert('L').getpixel((0, 0)))
print('P->RGB: ', img.convert('RGB').getpixel((0, 0)))
print('P->RGB->L: ', img.convert('RGB').convert('L').getpixel((0, 0)))
```

p.png:  ![p](https://user-images.githubusercontent.com/2735561/134200249-7e3e8e9f-d829-4719-b5b8-8f2cef534094.png)

Old
PIL: 6.2.2
P->L: 175
P->RGB: (177, 175, 175)
P->RGB->L: 175

7.0.0+
After commit [#4320](https://github.com/python-pillow/Pillow/pull/4320)
PIL:  8.3.2
P->L:  **175**
P->RGB:  (177, 175, 175)
P->RGB->L:  **176**

**Comment by radarhere** [comment]
This is because [P->L uses the L macro](https://github.com/python-pillow/Pillow/blob/a3d1e2f85db890c6a1623e3902711863f55cc54e/src/libImaging/Convert.c#L1012-L1016), but [RGB->L uses the L24 macro.](https://github.com/python-pillow/Pillow/blob/a3d1e2f85db890c6a1623e3902711863f55cc54e/src/libImaging/Convert.c#L233-L237)

So this change would make P->L be 176 as well.
```
diff --git a/src/libImaging/Convert.c b/src/libImaging/Convert.c
index 9012cfcd7..cd6e536cb 100644
--- a/src/libImaging/Convert.c
+++ b/src/libImaging/Convert.c
@@ -1013,7 +1013,7 @@ p2l(UINT8 *out, const UINT8 *in, int xsize, const UINT8 *palette) {
     int x;
     /* FIXME: precalculate greyscale palette? */
     for (x = 0; x < xsize; x++) {
-        *out++ = L(&palette[in[x] * 4]) / 1000;
+        *out++ = L24(&palette[in[x] * 4]) >> 16;
     }
 }
```

But I'm by no means certain that that is the correct solution.

**Comment by radarhere** [comment]
I've created #5824 to fix this by applying rounding to palette conversion methods.
