### ISSUE TITLE
`IsClipboardFormatAvailable` could replace `EnumClipboardFormats` loop in `PyImaging_GrabClipboardWin32`?

### ISSUE THREAD

**Issue by NewUserHa** [python-pillow/Pillow#5941]
### What did you do?
improve code 

### What did you expect to happen?
actually, there's a function https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-isclipboardformatavailable
then after improved, pillow needs scan 4 times only, instead of up to 16 times(4 * formats amount(usually >4))

### What actually happened?
https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/display.c#L518
current is a loop though all format in the clipboard, and inside the each single loop, is comparing the value against the predefined values using a nested loop

**Comment by radarhere** [comment]
Hi. If you have a suggestion for how to improve Pillow, you can always create a pull request with the exact changes.

**Comment by NewUserHa** [comment]
thanks. I want to make sure the change is useful at first.
according to https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-operations#paste-operations `EnumClipboardFormats` will obey a priority order. does pillow grab clipboard needs that? since pillow only has `{CF_DIB, CF_DIBV5, CF_HDROP, RegisterClipboardFormatA("PNG")` and pillow return CF_HDROP as a LIST of files, the PNG is a private format. so actually pillow has only 2 format to choose `CF_DIB` and `CF_DIBV5`.

**Comment by nulano** [comment]
> scan 4 times only, instead of up to 16 times

Do you have any reason to believe this is a performance issue? 16 function calls is practically negligible, unless each call takes a long time. Beware of premature optimization: https://softwareengineering.stackexchange.com/a/80092/281817 

The current version, as mentioned in the comment, finds the best format (as set by the clipboard owner):
https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/display.c#L516-L526

If switched to using `IsClipboardFormatAvailable`, you would have to think carefully about which format should be preferred. This is not at all obvious, since different applications offer clipboard data in a different set of formats. For example, one application might give you a file path for a JPG with EXIF metadata (you might care about metadata), then a PNG and BMP. Another might give you a PNG with transparency, a path to a PNG on disk, then a BMP without transparency. In the first case, the path is probably the best format, but in the second, loading the png directly is more convenient for the user. Loading BMP is almost always a last choice, but a third application might give you a BMP first and a path to a disk copy of the BMP second, here you would also likely prefer the bitmap.

**Comment by NewUserHa** [comment]
good explanation.
the advantage of `enumclipboardformats` is to check data by the order that the clipboard owner place.
the disadvantage is some applications sometimes set HDROP as first, and the users need to check to load it if it's a list of files.

from my test, clipboard order for chrome is PNG, DIBv5, HTML, uri, BITMAP(size 0), DIB
for irfanview is DIB, BITMAT(size 0), DIBv5.
for another application is DIB, HDROP, HTML, RICHEDIT, BITMAP(size 0), DIBv5.

for explorer, `ImageGrab.grabclipboard()` will return all files in clipboard without extension check, so the users can decide which file to open.

probably the current implements is already good enough.

**Comment by radarhere** [comment]
Sounds like you're happy for this to be closed.
