### ISSUE TITLE
Frame loss in GIF

### ISSUE THREAD

**Issue by justNice** [python-pillow/Pillow#5949]
### What did you do?
I try to extract frame from a gif
### What did you expect to happen?
I expect to get png or jpg image.
### What actually happened?
I got the same gif but in other mode.
### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: 3.10.1
* Pillow: 9.0.0

```python

```
![image](https://user-images.githubusercontent.com/53212206/148697591-0284d81e-72ea-4202-a909-522401d8a591.png)
![image](https://user-images.githubusercontent.com/53212206/148697607-05e99c15-de60-4efd-ad6b-e6ca0f6466be.png)

**Comment by radarhere** [comment]
Hi.

Since [Pillow 9.0](https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#convert-subsequent-gif-frames-to-rgb-or-rgba) / #5857, once you seek past the first GIF frame, the mode will change to RGB or RGBA, yes. This is because P mode can only handle up to 256 colors, and once you go past the first frame, there may be more colors than that.

The fact that `avatar` is a `GifImageFile` instance reflects the fact that you opened a GIF. I highly doubt that you actually need `avatar` to be a `PngImageFile` or `JpegImageFile` instance to accomplish your goal. If you think otherwise, please provide some more comments and we can discuss this further.

If you would like to create a PNG or JPG from your GIF, you can just run `avatar.save("out.jpg")` or `avatar.save("out.png")`.
