### ISSUE TITLE
Saving images to spreadsheets or as Minecraft pixel art

### ISSUE THREAD

**Issue by Eric-Mendes** [python-pillow/Pillow#5962]
### What did you do?
I've made a package that I think would fit better as an add-on to this project, instead of a standalone kind of thing

### What did you expect to happen?
My package is able to save images as a minecraft pixel art, or a spreadsheet
![shrek](https://user-images.githubusercontent.com/42689328/149664072-f38150ff-ab85-414e-8080-519d10e9bd37.png)

### What actually happened?
The package works. The only reason that I didn't write its code here was purely because I don't have tests for my functions and the contributing guidelines here requires that for any new functionality. I could use some help though, and that's why I'm filing this issue.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.something (not sure)
* Python: 3.9.5
* Pillow: 8.4.0

Here's the package: https://github.com/Eric-Mendes/unexpected-isaves. Do you guys think it fits here or is a bit off scope? Let me know. Thanks.

**Comment by radarhere** [comment]
If I understand correctly, in saving an image as a spreadsheet, you've effectively invented an image format? You didn't invented spreadsheets obviously, but you've found a non-traditional use for them. That seems a bit out of scope to me personally.

While I have minimal Minecraft knowledge myself, that one sounds like people would find it useful though. I'd be interested in refactoring to remove the pandas and numpy dependencies.

**Comment by Eric-Mendes** [comment]
Hi, @radarhere. Sure, suit yourself!
Let ask you this as well: yesterday I made a release with a new function that would probably fit in here even better (if it doesn't exist already) - https://github.com/Eric-Mendes/unexpected-isaves/blob/main/src/unexpected_isaves/image_utilities.py#L11. What do you think? Sorry if I'm making this a bit confusing. I just want to make my first open source contribution :)

**Comment by radarhere** [comment]
`fit_to_palette()` sounds similar to our own [quantize()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize)

![hopper](https://user-images.githubusercontent.com/3112309/150033065-c1fde2bb-2f9c-45bb-8986-e0e8b7267a07.png)
```python
from PIL import Image
im = Image.open("Tests/images/hopper.png")

colors = (
    (255, 0, 0),
    (0, 255, 0),
    (0, 0, 255)
)
one_dimensional_color_sequence = (x for y in colors for x in y)
palette_im = Image.new("P", (0, 0))
palette_im.putpalette(one_dimensional_color_sequence)
im.quantize(palette=palette_im).save("quantized.png")
```
![quantized](https://user-images.githubusercontent.com/3112309/150033132-65a66acb-b0b2-4eb5-afac-cc4cdeb07839.png)

I thought I would also run `fit_to_palette()` for comparison,
```python
im = Image.open("Tests/images/hopper.png")
fit_to_palette(im, [
	RGBColor((255, 0, 0)),
	RGBColor((0, 255, 0)),
	RGBColor((0, 0, 255))
]).save("unexpected.png")
```
...except that gives me a nearly white image.

![unexpected](https://user-images.githubusercontent.com/3112309/150033387-dd8612b1-aa2b-430b-8daf-42d8f5c38db7.png)

> I just want to make my first open source contribution :)

Your code is a public GitHub repository licensed under MIT and on PyPI. Sounds to me like you've already made your first open source contribution!

**Comment by radarhere** [comment]
From https://github.com/Eric-Mendes/unexpected-isaves/pull/21, you've now decided to deprecate `fit_to_palette()`.

**Comment by Eric-Mendes** [comment]
@radarhere thanks for making your first contribution on my repo! 😄 
Let me know if things here go any further. Want me to assign you this issue?

**Comment by radarhere** [comment]
I think no on the assigning - the fact that I don't actually have Minecraft (it seems you can't use data packs without paying?) means that I'd rather not be held as the authority on this subject.

Some questions for you.

1. If I'm following correctly, your code [rotates portrait images into landscape mode](https://github.com/Eric-Mendes/unexpected-isaves/blob/31e1d666449b097d82c068311593c500fa2606c8/src/unexpected_isaves/save_image.py#L439-L455). Is there some downside to images being in portrait mode in Minecraft?
2. From Googling, I gather that "tick" controls any changes over time. It feels unusual that tick.mcfunction is empty though. Are the files actually required? If you remove the "tick.json" and "tick.mcfunction" files, does it still work?
3. Can `/fill` commands cross multiple lines? So instead of
```
fill 0 0 0 4 0 0 minecraft:iron_block
fill 5 0 0 9 0 0 minecraft:redstone_block
fill 0 0 1 4 0 1 minecraft:redstone_block
```
could I write
```
fill 0 0 0 4 0 0 minecraft:iron_block
fill 5 0 0 4 0 1 minecraft:redstone_block
```
?
I've put together examples in a zip - [functions.zip](https://github.com/python-pillow/Pillow/files/8175672/functions.zip). It has a PNG of what it should look like, a mcfunction that crosses multiple lines, and a mcfunction that doesn't. Do both mcfunction files appear the same in Minecraft?
4. I can't think any instance where Pillow creates multiple files for one image. What if the Pillow module created a zip file, and then we left it up to the user to expand it and move the files to the proper destination? Does that sound reasonable?

**Comment by radarhere** [comment]
Closing due to lack of a response. If there isn't interest in this, then there isn't a strong motivation to implement a non-standard format.
