### ISSUE TITLE
Converting I;16B PNG to RGB ruins the image

### ISSUE THREAD

**Issue by clairerity** [python-pillow/Pillow#5991]
Hello! I have a image grayscale image (spectrogram) that looks fine on 32bit (F), but when i try to convert it to RGB, most data is loss, that means the image is almost fully black (majority of the white/gray parts turned to black!), would just like to know how to resolve this. Thank you very much in advance!

**Comment by radarhere** [comment]
Would you mind attaching a copy of your image?

**Comment by clairerity** [comment]
Hello @radarhere ! thank you very much for your reply :) 

This is the original image in F mode (32 bit grayscale aka 1 channel)
![mel](https://user-images.githubusercontent.com/69097467/151280316-58e91105-e4e1-4eae-bcc2-ec47cf3e8204.png)

when i try to convert it using .convert('RGB'), it becomes this
![colored](https://user-images.githubusercontent.com/69097467/151280433-b5a2a719-e91b-43ed-b8fb-7520278cbff5.png)

Almost all parts are lost :(

**Comment by radarhere** [comment]
From looking at the image, I conclude that it's not actually in F mode, but I;16B.

Unfortunately, Pillow does not have very good support for I;16 modes at the moment. Also, when I try to convert to RGB, my image becomes too bright, rather than too dark.

If you are looking for an immediate solution, I did
```python
from PIL import Image
im = Image.open('input.png')
im.point(lambda i: i * (1 / 255)).convert("RGB").save("output.png")
```
but since yours is too dark, I would suggest
```python
from PIL import Image
im = Image.open('input.png')
im.point(lambda i: i * 255).convert("RGB").save("output.png")
```
