### ISSUE TITLE
Incorrect behavior of `text=str.upper()` in ImageDraw.Draw.text

### ISSUE THREAD

**Issue by chiboreache** [python-pillow/Pillow#5993]
i'm using Arch Linux - everything is bleeding edge.

### working

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont


font_path = '/usr/share/fonts/TTF/Code2000.ttf'

m = 4
resolution = (256*m, 64*m)
fontsize = 28*m

image = Image.new('RGB', resolution, 'gray')

ImageDraw.Draw(image).text(
    (resolution[0]/2, resolution[1]/2),
    text='ქართული',
    font=ImageFont.truetype(font_path, fontsize),
    fill=(0, 0, 0),
    anchor="mm"
)

image.save('res.jpg')
```
![2022-01-28x00:46:54](https://user-images.githubusercontent.com/16459251/151449114-4aac037f-58c7-4097-b2e6-f560138e7f44.jpg)

### not working

```python
ImageDraw.Draw(image).text(
    (resolution[0]/2, resolution[1]/2),
    text='ქართული'.upper(),
    font=ImageFont.truetype(font_path, fontsize),
    fill=(0, 0, 0),
    anchor="mm"
)
```

![2022-01-28x00:47:06](https://user-images.githubusercontent.com/16459251/151449126-99450adc-79f7-42aa-869f-584e9f34c01f.jpg)

**Comment by radarhere** [comment]
Hi. What font are you using?

**Comment by chiboreache** [comment]
> Hi. What font are you using?

i found similar behaviour in many fonts Code2000, DejaVuSans, DejaVuSerif, FreeSerif, FreeMonoBold ...

**Comment by radarhere** [comment]
As with #5948, it is important to understand that fonts do not automatically support every character you might try.

Starting with code from https://stackoverflow.com/questions/4458696/finding-out-what-characters-a-given-font-supports and making changes, here is code (using [fonttools](https://pypi.org/project/fonttools/) rather than Pillow) that checks if the characters you are trying to draw are supported by the font.

```python
from itertools import chain
from fontTools.ttLib import TTFont
ttf = TTFont("Code2000.ttf", 0, allowVID=0, ignoreDecompileErrors=True, fontNumber=-1)
chars = []
for x in ttf["cmap"].tables:
    chars += [y[0] for y in x.cmap.items()]
ttf.close()

print("original string")
text = 'ქართული'
for letter in text:
    if ord(letter) in chars:
        print(letter, ord(letter), "is in font")
    else:
        print(letter, ord(letter), "is missing from font", ord(letter))

print()
print("uppercase string")
text = text.upper()
for letter in text:
    if ord(letter) in chars:
        print(letter, ord(letter), "is in font")
    else:
        print(letter, ord(letter), "is missing from font")
```
Running the code, I get
```
original string
ქ 4325 is in font
ა 4304 is in font
რ 4320 is in font
თ 4311 is in font
უ 4323 is in font
ლ 4314 is in font
ი 4312 is in font

uppercase string
Ქ 7333 is missing from font
Ა 7312 is missing from font
Რ 7328 is missing from font
Თ 7319 is missing from font
Უ 7331 is missing from font
Ლ 7322 is missing from font
Ი 7320 is missing from font
```
So I conclude that the font is missing the 'upper' version of your characters.
For example, https://www.compart.com/en/unicode/U+10E5 is supported by Code2000, but https://www.compart.com/en/unicode/U+1CA5 is not.

**Comment by chiboreache** [comment]
it would be nice to have built in char checker, but whatever, thank you @radarhere !
