### ISSUE TITLE
How to set anchor to fit the text at center of image with ImageDraw.Draw.text?

### ISSUE THREAD

**Issue by jason990420** [python-pillow/Pillow#6073]
### What did you do?
Drawn text on an image with Pillow library, tried to fit the text anchored at center of image by option anchor='mm', but it looks not exactly as center of image.

### What did you expect to happen?
![image](https://user-images.githubusercontent.com/55352169/154840005-c2d5004c-8b4c-411c-a0a8-3c8ee3de7abc.png)

### What actually happened?
![image](https://user-images.githubusercontent.com/55352169/154840013-192b2bd4-5c01-45a3-b2d6-8616aabf0753.png)

### What are your OS, Python and Pillow versions?

* OS: WIN10
* Python: 3.9.9
* Pillow: 8.4.0

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGBA", (500, 500), (255, 255, 255, 255))
font = ImageFont.truetype(font='arial.ttf', size=320)
draw = ImageDraw.Draw(im)
draw.text((250, 250), "123", font=font, fill='black', anchor='mm')
im.show()
```

**Comment by nulano** [comment]
It might not look like it, but that is actually centered according to the font. The issue is that the symbol for "1" is thinner than the symbol for "3", so the symbol for "1" is surrounded by more space. You can see this if you compare the gap between "1" and "2" to the gap between "2" and "3".

Adjusting your code to create a slightly larger image (marking the original size with a black rectangle), you can see that the text bounding box (drawn in red) exceeds the image on both sides equally:
```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGBA", (600, 600), (255, 255, 255, 255))
font = ImageFont.truetype(font='arial.ttf', size=320)
draw = ImageDraw.Draw(im)
draw.rectangle((50, 50, 550, 550), outline="black")
draw.rectangle(draw.textbbox((300, 300), "123", font=font, anchor='mm'), outline="red")
draw.text((300, 300), "123", font=font, fill='black', anchor='mm')
im.show()
```

![bbox](https://user-images.githubusercontent.com/3819630/154842755-5059e0d9-e5fc-45c5-8874-4c03cd217c8c.png)

**Comment by jason990420** [comment]
> Centered according to the font
I know what happened now, thank you for your replies and maybe I can find the right way for it.

**Comment by jason990420** [comment]
Yes, I got it now !

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGBA", (500, 500), (255, 255, 255, 255))
font = ImageFont.truetype(font='arial.ttf', size=320)
w, h = size = font.getsize("123")
text_im = Image.new("RGBA", size, (0, 0, 0, 0))
draw = ImageDraw.Draw(text_im)
draw.text((w//2, h//2), "123", font=font, anchor='mm', fill='black')
x1, y1, x2, y2 = box = text_im.getbbox()
width, height = abs(x2-x1), abs(y2-y1)
text_im = text_im.crop(box)
im.paste(text_im, box=((500-width)//2, (500-height)//2), mask=text_im)
im.show()
```
![tmpsdr3b7uh](https://user-images.githubusercontent.com/55352169/154845030-923598e6-9ec1-49f0-bdbd-603fec618a60.PNG)
