### ISSUE TITLE
[Feature Request] Is it possible to support memmap or reading just only a specific window of the image?

### ISSUE THREAD

**Issue by nijkah** [python-pillow/Pillow#6083]
Hello, I try to use Pillow to read only just the specific part of the entire image.
There are some libraries that support this feature.

[gdal](https://gdal.org/python/osgeo.gdal.Dataset-class.html#ReadAsArray). It even supports tiff and png.
[rasterio](https://rasterio.readthedocs.io/en/latest/topics/windowed-rw.html). It supports only tiff or jp2.
[tifffile](https://github.com/cgohlke/tifffile/blob/90805c33065da10d8e604850a840c3166099f91f/tifffile/tifffile.py#L998). It supports only tiff.

What I want to do is that use Pillow to get meta information about its offset, shape, etc and use `np.memmap` to load it.
Ot it is just good to read a specific part of the image without the loading entire image. (`Image.crop`)
Is it already possible with Pillow (I couldn't find it.) or any other alternative way to achieve this?

I think this feature will be helpful for many developers dealing with large size images.

**Comment by nijkah** [comment]
https://github.com/python-pillow/Pillow/issues/5046
I might find that it is already answered in the different aspect.
It is also impossible to use memmap to decode png, am I right?

**Comment by FirefoxMetzger** [comment]
Disclaimer: I'm neither a member nor a super active dev for pillow, so this is just my personal view and you'll have to wait for members to comment for a definite answer.

In theory, it would be nice to have a sliceable interface like that, and in practice, you could hack it into existence for most image formats. Unfortunately you wouldn't get much of a performance boost out of it, because under the hood you'd still have to load large parts of the image and then discard them. I think this would cause much more confusion than benefit in the general case, so I don't think its a wise decision to have something like this in a general-purpose library like pillow.

**TL:DR** Explanation on why this is a bad idea.

The reason is that the vast majority of image formats (especially common ones) use some form of compression to store the data on disk. Because of that, the smallest unit you could possibly load is determined by the chunk size of said compression algorithm, which are gory details of each individual image format, vary A LOT by format, and are nothing you'd want to bother the average downstream users with. For example:

- (as far as I'm aware) PNG compresses lines so you can slice along the height dimension, but slicing along the width doesn't benefit you at all. 
- JPG does compression in various block sizes (multiples of 8, so 8x8, 16x8 or 16x16 are common). This means slicing is a bit more friendly than PNG, but for arbitrary slices you still discard quite a bit of data. 
- TIFF is a different kind of beast. It may store data uncompressed, which makes slicing efficient, but runs into an IO bottleneck. It may also be compressed with one of two modes (of which I've only ever seen one). For that one, compression happens at the granularity of a page (IIRC). This means different things depending on the application that created the TIFF, but usually means that any slicing that happens along width or height will involve loading anything between one plane (channel-first images) or the entire image and discarding everything except the slice. On top of that, TIFF allows differently sized images stored on each page, so slicing multiple planes at once quickly becomes weird. (How would you align those pages for slicing?)
- GIF is pretty much a poor-mans video format, so slicing along any dimension involves loading all frames up to that point and then chunking it down. For some GIFs you might be able to ignore some frames, but that is super specific to the actual GIF, so nothing you want to write general-purpose code for.

It gets weirder as you move towards more esoteric formats (and video), but I think looking at these 4 super common formats is enough to get the point across: Slicing (width/height) looks nice on paper, but isn't very useful in practice. 

---

> What I want to do is that use Pillow to get meta information about its offset, shape, etc and use np.memmap to load it.

Once you've opened an image with pillow you can access width, height, mode, and n_frames without loading any pixel data, so you can get the metadata you need efficiently. However, compression kills the `np.memmap` approach that you are envisioning.

**Comment by nijkah** [comment]
@FirefoxMetzger
Thank you for your kind explanation. I think I hurried to post this feature request issue without enough consideration and investigation. I could understand there are lots of difficulties and practical issues to support this kind of feature.

Your answers may benefit future developers thinking like me. Sincerely thank you.
I'll close this issue in a day.
