### ISSUE TITLE
Inconsistent GIF result after resizing

### ISSUE THREAD

**Issue by Kusefiru** [python-pillow/Pillow#6085]
I am trying to resize a `.gif` file. For that, I open my file with Pillow, then for each frame, resize that frame, and save the resulting frames as a new .gif file.

Here is the sample code:

```python
from PIL import Image

image = Image.open("test.gif")

frames = []
for i in range(image.n_frames):
    image.seek(i)
    frames.append(image.resize((512, 512), resample=Image.BICUBIC))

frames[0].save("result.gif", save_all=True, append_images=frames[1:], duration=100, loop=0)
```

Here is the used `test.gif` file:
![test.gif](https://user-images.githubusercontent.com/19759836/155106468-edcdfc5c-eb80-476c-b8fa-539f65b94386.gif)

As the resize is done using the `Image.BICUBIC` resampling method, I expect the resulting file to have a blurred appearance.

On **Pillow 9.0.1**, the first frame appears pixel crisp:
![result](https://user-images.githubusercontent.com/19759836/155107345-f69a5e7e-efb0-40e9-b2a4-98d9bb1d2367.gif)

On my previous install, **Pillow 8.4.0**, all the frames are pixel crisp:
![result_8 4 0](https://user-images.githubusercontent.com/19759836/155107328-69dd7907-a29e-4f02-8fb9-03f706aa0859.gif)

What could explain such behaviour (is there a missing option in my `save` call)?

**Comment by FirefoxMetzger** [comment]
This is actually unrelated to doing a resize or the save call. Instead, it happens during the loading of the GIF. The lack of crisp-ness, aka, the graininess of each frame is a typical dithering artifact, in this case [Floyd–Steinberg dithering](https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering). It currently happens under the hood once you seek beyond the first frame of a GIF:

https://github.com/python-pillow/Pillow/blob/4638c4fba651025851bf1f41a28583ae11d73c3a/src/PIL/GifImagePlugin.py#L169-L177

I don't think there is much you can do in pillow 9.0.1 considering that the value was hard-coded. It might be possible to expose the dithering method as a kwarg instead of hardcoding it (which could then be set to `None`), but I don't know the internal plugin API well enough to know where such a kwarg would live. `seek` seems natural, but might be the wrong place to do so. We'd have to wait for @radarhere to tell what's feasible.

**Comment by radarhere** [comment]
Hi. Unfortunately, I need to disagree with @FirefoxMetzger. Dithering during loading is not causing a problem here.

```python
from PIL import Image

image = Image.open("test.gif")
image.save("firstframe.png")

image.seek(1)
image.save("secondframe.png")
```
| firstframe.png | secondframe.png |
| --- | --- |
| ![firstframe](https://user-images.githubusercontent.com/3112309/155422964-3a969a82-9a70-4e71-b351-c572e6792771.png) | ![secondframe](https://user-images.githubusercontent.com/3112309/155422977-0d300ed3-8fe1-480b-887e-6eb3147ae89c.png) |

It's hard to tell visually on this page, but if I zoom in on macOS Preview, both display similarly.

```python
from PIL import Image

image = Image.open("test.gif")

print(image.mode)  # P
image.resize((512, 512), resample=Image.BICUBIC).save("firstframe_resized.png")

image.seek(1)
print(image.mode)  # RGB
image.resize((512, 512), resample=Image.BICUBIC).save("secondframe_resized.png")
```

| firstframe_resized.png | secondframe_resized.png |
| --- | --- |
| ![firstframe_resized](https://user-images.githubusercontent.com/3112309/155423342-3669676a-1ecd-4a08-9beb-2976444d30df.png) | ![secondframe_resized](https://user-images.githubusercontent.com/3112309/155423352-e746bab2-d10b-4e11-a9b4-a9fa57b6695d.png) |

The difference is only apparent once you try and resize the images. This would be because the first frame is P, and the second frame is RGB.

> As the resize is done using the `Image.BICUBIC` resampling method, I expect the resulting file to have a blurred appearance.

So your request is that all frames be blurred? If so, this can be achieved by just converting the first frame to RGB.

```python
from PIL import Image

image = Image.open("test.gif")

frames = []
for i in range(image.n_frames):
    image.seek(i)
    frame = image
    if i == 0:
    	frame = frame.convert("RGB")
    frames.append(frame.resize((512, 512), resample=Image.BICUBIC))

frames[0].save("result.gif", save_all=True, append_images=frames[1:], duration=100, loop=0)
```
![result](https://user-images.githubusercontent.com/3112309/155423572-b7de3a20-61f6-4a2f-96a9-5449c111091e.gif)

**Comment by FirefoxMetzger** [comment]
> So your request is that all frames be blurred? If so, this can be achieved by just converting the first frame to RGB.

Ah right; that's another way to read the issue. I understood "all the frames are pixel crisp" as a reference to the dither, not to the fact that the first frame is blurred differently. Sorry if I jumped to conclusions.

---

Interestingly though, automatic dithering *did* get introduced in pillow9. If I run the original code in pillow8.4 I get the following result:

```python
from PIL import Image

image = Image.open("test.gif")

frames = []
for i in range(image.n_frames):
    image.seek(i)
    frame = image
    frames.append(frame.resize((256, 256), resample=Image.BICUBIC))

frames[0].save("result.gif", save_all=True, append_images=frames[1:], duration=100, loop=0)
```

| Pillow8.4| Pillow9|
| --- | --- |
| ![result](https://user-images.githubusercontent.com/4402489/155488098-612c15d6-64d5-4cc0-b923-61b3e0eebf9a.gif) | ![result](https://user-images.githubusercontent.com/4402489/155487700-5452696e-955d-45e2-9c9e-85ecd93d5200.gif) |



However if I add an explicit conversion to RGB (as in your suggestion) then both results look the same and they match the default behavior in pillow9:

```python
from PIL import Image

image = Image.open("test.gif")

frames = []
for i in range(image.n_frames):
    image.seek(i)
    frame = image
    frame = frame.convert("RGB")
    frames.append(frame.resize((256, 256), resample=Image.BICUBIC))

frames[0].save("result.gif", save_all=True, append_images=frames[1:], duration=100, loop=0)
```

| Pillow8.4| Pillow9|
| --- | --- |
| ![result](https://user-images.githubusercontent.com/4402489/155487947-a5e01c7a-123c-4897-9ccf-0d585c7bf75e.gif) | ![result](https://user-images.githubusercontent.com/4402489/155487885-164a5569-8e4f-4731-8074-231c0dd19cd7.gif) |

**Comment by Kusefiru** [comment]
Okay, I understand that the issue comes from the conversion of the first frame being different. I can modify my program as suggested to fix the issue.

But why is it that the first frame is not converted as RGB automatically when the others are ? Is it because of the `seek` method ?

**Comment by radarhere** [comment]
Before Pillow 9, P mode was used for all frames in a non-grayscale GIF. While this worked fine for your image, some images were broken because of this.

https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#convert-subsequent-gif-frames-to-rgb-or-rgba
> Since each frame of a GIF can have up to 256 colors, after the first frame it is possible for there to be too many colors to fit in a P mode image. To allow for this, seeking to any subsequent GIF frame will now convert the image to RGB or RGBA, depending on whether or not the first frame had transparency.

Why was the first frame not changed to RGB as well? I presume there is a contingent of Pillow users who just read the first frame of images, and don't bother seeking past that. This change in Pillow 9 (#5857) had no effect on those users, and so did not disrupt their experience at all.

I think the first image is a P mode image - it has only up to 256 colors. It is represented by a palette in the original GIF.
While your image may happen to also use the same colors for subsequent frames, it is entirely possible for GIFs to have more than 256 colors by the second frame, meaning that RGB is used.

**Comment by radarhere** [comment]
@Kusefiru did that answer your question? Is there anything else we can do for you?

**Comment by Kusefiru** [comment]
Yes I think it's fine for me, thanks.
