### ISSUE TITLE
Image.paste does not work as expected with mask argument

### ISSUE THREAD

**Issue by ma-tongji** [python-pillow/Pillow#6142]
### What did you do?

paste a RGBA image to another RGBA image

### What did you expect to happen?

If pixel in Image 1 is (r1, g1, b1, a1) and pixel in Image 2 is (r2, g2, b2, a2)
paste Image 1 on Image 2 will get pixel: (a1, a2 are already divided by 255)

```
R = r1*a1 + r2*(1-a1)
G = g1*a1 + g2*(1-a1)
B = b1*a1 + b2*(1-a1)
ALPHA = a1+a2-a1*a2
```

### What actually happened?

the result pixel is a little white than calulated, also I compared the result image with what I generated from Photoshop, it's also a little white somehow. So maybe the paste function calculate pixel with different formula?

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6.4
* Pillow: 8.2.0

```python
from PIL import Image

root = Image.new('RGBA', (600, 600), (0, 0, 0, 0))
b = Image.open('tag1.png')
root.paste(b, (0,0), b)
a =Image.open('tag2.png')
root.paste(a, (10,10), a)
root.save('final.png')
```

**Comment by radarhere** [comment]
Hi. Here is some example code I put together.

```python
from PIL import Image
im1 = Image.new("RGBA", (1, 1), (255, 128, 64, 32))
im2 = Image.new("RGBA", (1, 1), (16, 32, 64, 128))
im2.paste(im1, (0, 0), im1)
print(im1.getpixel((0, 0)))
```
that gives `(46, 44, 64, 116)`.

Looking at the code,
https://github.com/python-pillow/Pillow/blob/625d7accd6c0ba29318172ace0e401a3290e50ff/src/libImaging/Paste.c#L177-L180
https://github.com/python-pillow/Pillow/blob/625d7accd6c0ba29318172ace0e401a3290e50ff/src/libImaging/ImagingUtils.h#L17-L24

I see this formula for each channel (R, G, B, A, although not exactly this for A, since you state your A is divided by 255). I'm using X as a placeholder for the channel in question.

```python
y = (X2 * (255 - mask_a * 255) + X1 * mask_a * 255) + 128
z = y + 128
X = ((z >> 8) + z) >> 8
```

If you prefer this as a complete example,

```python
from PIL import Image

def paste(im1, im2, mask):
    result = []
    for i in range(4):
        y = (im2[i] * (255 - mask[3]) + im1[i] * mask[3]) + 128
        z = y + 128
        result.append(((z >> 8) + z) >> 8)
    return result

im1 = Image.new("RGBA", (1, 1), (255, 128, 64, 32))
im2 = Image.new("RGBA", (1, 1), (16, 32, 64, 128))
print(paste(im1.getpixel((0, 0)), im2.getpixel((0, 0)), im1.getpixel((0, 0))))
```
which gives `[46, 45, 65, 116]`. Not exactly the same, but very close.

So to review, I think this actually matches up with your expectation of `r1*a1 + r2*(1-a1)` - not the alpha version, but I don't quite see how you came up with that.
Could you give a specific example where Pillow doesn't match your expectation? While you've provided a code example, I don't know what specific numbers you expected, I don't have copies of tag1.png, tag2.png, and the fact that you've performed two paste operations in your code seems to make the example unnecessarily complex.

**Comment by ma-tongji** [comment]
Hi redarhere,

Thanks for the detailed explanation. I find an exmaple here (https://stackoverflow.com/questions/19561597/pil-image-paste-on-another-image-with-alpha) which has the exactly same problem as me. The anwers there are suggested to use alpha_composite().

1) Is this supposed to be happen when you paste one image on another? There will have some white margin around.
2) alpha_composite() require two Images with same size. I suppose paste() will do the job but actually it doesn't, it looks like paste() behaves different compared to alpha_composite()

**Comment by radarhere** [comment]
The StackOverflow post combines these two images.
![blue](https://user-images.githubusercontent.com/3112309/161541062-4dfe2c79-6aee-4d99-922b-3619b6b50be7.png)
![red](https://user-images.githubusercontent.com/3112309/161541067-b1d87d91-83dc-48ec-ab87-ca65bdff3b2f.png)

```python
from PIL import Image

blue = Image.open("blue.png")
red = Image.open("red.png")
red.paste(blue, (0,0), blue)
red.save("result.png")
```

into

**Comment by radarhere** [comment]
If after that code, I try and get the RGBA value of one of these "white" pixels in the middle,

```python
print(red.getpixel((24, 31)))
```

I get `(125, 17, 128, 193)`. Lots of red and blue, as expected. Not much green. So it isn't white. A lot of alpha.

So if I take that and add a black background to it in Gimp,
![result](https://user-images.githubusercontent.com/3112309/161542955-da90180e-9250-4ca8-80ef-55e944c2d37c.png)

it becomes clear that the pixels in the middle are not white. They only look white when you view the image on a white background. They are translucent.

Looking at the values from the original `blue` and `red` images at `(24, 31)`, I get `(12, 0, 255, 107)` and `(207, 30, 37, 255)` respectively. So `paste()` is combining these two values to come up with a red-blue translucent value.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste
> Intermediate values will mix the two images together, including their alpha channels if they have them.

So this seems expected.

**Comment by radarhere** [comment]
> 2. alpha_composite() require two Images with same size

I'll point out that some detail to this statement. While [`Image.alpha_composite()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.alpha_composite) requires the images to be the same size,
```pycon
>>> from PIL import Image
>>> im1 = Image.new("RGBA", (10, 10))
>>> im2 = Image.new("RGBA", (100, 100))
>>> Image.alpha_composite(im1, im2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 3144, in alpha_composite
    return im1._new(core.alpha_composite(im1.im, im2.im))
ValueError: images do not match
```
[`im.alpha_composite()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.alpha_composite) does not.

```pycon
>>> from PIL import Image
>>> im1 = Image.new("RGBA", (10, 10))
>>> im2 = Image.new("RGBA", (100, 100))
>>> im2.alpha_composite(im1)
>>>
```

**Comment by radarhere** [comment]
@ma-tongji did that answer your question?

**Comment by supergnaw** [comment]
I am not OP, but I believe I may be having the same issue regarding the mask. I have a base layer which has no transparancy, that I am layering things on top of. What appears to be happening is the mask seems to be affecting both the pasted layer and the target layer. See below:

![image](https://user-images.githubusercontent.com/25543199/165009115-445c3839-a33f-45e3-b6db-f229d07fb004.png)

I only noticed this after zooming in very close because the edges looked kind of...off, and even though the base layer is not transparent, the mask appears to be applied to both layers. Along the edge of the white arc on the top right you can see the standard checkerboard background in photoshop, as well as along the edge of the shape on the bottom left. These locations of the image were not transparent prior to the paste.

I am looping through layers to aggregate them into a single file, all source images are png in `RGBA` mode, manipulated to be positioned on a blank new Image and then pasted on the main canvas:

```python
layer = Image.new(mode="RGBA", size=(width, height))
# do layer things
canvas.paste(layer,(0,0),layer)
```

This does NOT happen when drawing text directly to `canvas`, but DOES happen when drawing text on a `layer` instance, and then `paste`ing it onto `canvas`.

**Comment by radarhere** [comment]
@supergnaw congrats on finding the solution to your problem.

I think my comments above should similarly explain your situation. It's hard to be precise without a self-contained example, but https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste states that, for `paste()`,
> Intermediate values will mix the two images together, including their alpha channels if they have them.

So the behaviour seems expected to me. And if `alpha_composite()` is the behaviour that you want, then it makes sense to me that `paste()` does something different, because, well, why have two different methods that do exactly the same thing?

I had a thought that perhaps we need to mention `alpha_composite()` in the `paste()` documentation... except it turns out that's already done - https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste tells users to
> See [alpha_composite()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.alpha_composite) if you want to combine images with respect to their alpha channels.

Let me know if you think there's anything to be done, but otherwise, I think this issue is ready to be closed.

**Comment by supergnaw** [comment]
So I think *my* personal disconnect comes from the choose of method names, `paste` vs `composite`. To me, a paste seems like it would be placed directly over something, whereas composite seems like it would use some form of combination between the two images to merge them. Based on the verbiage alone, I feel the expected results of each respective method are reversed, but this is just me. And I don't think it would be very wise to switch it "back" given how in use this library is. It's just one of those gotchas that we as developers just kinda have to accept.
