### ISSUE TITLE
When I exited my virtual environment it seemed to work

### ISSUE THREAD

**Issue by Aditya-76** [python-pillow/Pillow#6181]
When I exited my virtual environment it seemed to work

_Originally posted by @akackon in https://github.com/python-pillow/Pillow/issues/3851#issuecomment-657049322_

Why is that the case? I want to use pillow within the virtual environment. How do I fix it?

**Comment by hugovk** [comment]
Thank you for reporting an issue.

Follow these guidelines to ensure your issue is handled properly.

If you have a ...

1.  General question: consider asking the question on Stack Overflow
    with the python-imaging-library tag:

    * https://stackoverflow.com/questions/tagged/python-imaging-library

    Do not ask a question in both places.

    If you think you have found a bug or have an unexplained exception
    then file a bug report here.

2.  Bug report: include a self-contained, copy-pastable example that
    generates the issue if possible. Be concise with code posted.
    Guidelines on how to provide a good bug report:

    * https://stackoverflow.com/help/mcve

    Bug reports which follow these guidelines are easier to diagnose,
    and are often handled much more quickly.

3.  Feature request: do a quick search of existing issues
    to make sure this has not been asked before.

We know asking good questions takes effort, and we appreciate your time.
Thank you.

### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a 

```python
code goes here
```

**Comment by radarhere** [comment]
> Why is that the case?

I don't expect that Pillow was broken because the user's environment was virtual. I expect it was just because they had installed Pillow in their normal environment and not in their virtual environment.

**Comment by radarhere** [comment]
If you think you have installed Pillow, but you can't import it, then I suggest you install Pillow in the same way that you run your script.

What does that mean? If you had run
```
pip install Pillow
python3 script.py
```
and then found that `python3` couldn't detect Pillow, it might be because `pip` is connected to a different environment than `python3` is.

So in https://pillow.readthedocs.io/en/stable/installation.html#basic-installation, we recommend
> python3 -m pip install --upgrade pip
> python3 -m pip install --upgrade Pillow

That way, when you run `python3 script.py`, Pillow will be found.

You may not run `python3`. Your command might be `python3.8` or `/usr/local/bin/python3.8`. Whatever it is, try installing Pillow the same way that you run your script. See https://snarky.ca/why-you-should-use-python-m-pip/ for more information about this general idea.

**Comment by radarhere** [comment]
@Aditya-76 did you have any further information for us?
