### ISSUE TITLE
Pasting images not working properly 

### ISSUE THREAD

**Issue by mab-mab** [python-pillow/Pillow#6214]
### What did you do?
Given a square Image I round the corners using a layer mask and then paste it onto another image.

### What did you expect to happen?
The image paste with the rounded corners

### What actually happened?
The original image without the rounded corners appears on the background

### What are your OS, Python and Pillow versions?

* OS: /
* Python:  3.9.1
* Pillow:  9.0.0

```python
from PIL import Image, ImageDraw, ImageOps
size = (85, 85)
mask = Image.new('L', size, 0)
draw = ImageDraw.Draw(mask)
draw.rounded_rectangle((0, 0) + size,25, fill=255)


im = Image.open('test.png')

output = ImageOps.fit(im, mask.size, centering=(0.5, 0.5))
output.putalpha(mask)

output.save('output.png')

board = Image.open("background.png")

board.paste(output,(500,500))

board.show()

board.save("123.png")
```

**Comment by radarhere** [comment]
Hi. When you are pasting `output` onto `board`, you would like only the non-transparent parts of the image to be pasted, not the complete image. This is what the `mask` argument to `paste()` is for.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste
> If a mask is given, this method updates only the regions indicated by the mask.

I expect that `board.paste(output,(500,500),output)` will make your code work.

If it seems surprising that the original corners are still present as information in the image, that's because setting the A values to zero `output` does not get rid of the R, G and B values in the image.

**Comment by mab-mab** [comment]
I found the solution anyways but thanks
