### ISSUE TITLE
Size of the image generated by putalpha is twice as big, how can this be solved?

### ISSUE THREAD

**Issue by zhenzi0322** [python-pillow/Pillow#6287]
Example code：
```python
from PIL import Image

def main():
    file = 'uploads/images/4fcf8e9d4b7d41549ee260428b535f7e.jpg'
    img = Image.open(file)

    alpha = Image.open('uploads/alpha/4fcf8e9d4b7d41549ee260428b535f7e.jpg')
    img.putalpha(alpha=alpha)

    save_args = {'format': 'PNG'}
    save_args['quality'] = 85
    save_args['optimize'] = True
    img.save('demo4.png', **save_args)
```

**Comment by radarhere** [comment]
When you say "twice as big", twice as big as what? If you mean that it is twice as big as the JPEG that you opened, PNG is a lossless image format, while JPEG is a lossy format. It should be no surprise that the the PNG equivalent of a JPEG image is larger.

If you mean something else, please specify, and also kindly upload your test image so that we can replicate your situation more exactly.

**Comment by radarhere** [comment]
I presume you don't mean that it is twice as big as it would be without a call to `putalpha` - if I test your code with a JPEG from our test suite, the resulting PNG is approximately a third larger, not twice as large.
That change seems reasonable, as you would expect it to be adding another channel, moving from RGB to RGBA.

**Comment by zhenzi0322** [comment]
Yes, there is also a problem that the speed is a bit slow, how to solve this kind of

**Comment by radarhere** [comment]
If you are dealing with a large JPEG, that might slow your code down.

Removing `save_args['optimize'] = True` would speed your code up.

**Comment by radarhere** [comment]
We already have #5986 open for PNG speed and #617 for the size of PNG files. So while I can answer specific questions, there are already issues open for the general nature of this problem.
