### ISSUE TITLE
File not found error while using `Image.open` function

### ISSUE THREAD

**Issue by createvi** [python-pillow/Pillow#6332]
### What did you do?
I used `Image.open` function in my code. but it returns an error
### What did you expect to happen?
i wanted to open the file i told it to
### What actually happened?
```py
Traceback (most recent call last):
  File "/home/vishnu/Vortex/Projects/shop.py", line 43, in <module>
    google_pay_qrcode = Image.open("~/Vortex/Projects/Source/rickroll_qr.png")
  File "/home/vishnu/.local/lib/python3.9/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '~/Vortex/Projects/Source/rickroll_qr.png'`
```
But there is rickroll_qr.png in ~/Vortex/Projects/Source
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04 LTS
* Python: 3.9
* Pillow: 9.1.1

**Comment by radarhere** [comment]
The problem is the tilde character - ~

If you replace that with "/home/vishnu", it will work -
```python
from PIL import Image
google_pay_qrcode = Image.open("/home/vishnu/Vortex/Projects/Source/image.png")
```
If you would like to use the tilde character in your path, you can use [`os.path.expanduser`](https://docs.python.org/3/library/os.path.html#os.path.expanduser)
```python
from PIL import Image
import os
google_pay_qrcode = Image.open(os.path.expanduser("~/Vortex/Projects/Source/image.png"))
```

**Comment by createvi** [comment]
right i can't use ~ . Thank you for your help again

**Comment by SalmaG98** [comment]
Hello I am having the same issue on :
Ubuntu 20.04.4 LTS  
python 3.7.9
Pillow 8.0.0

I have a pytorch data loader that constructs a file_path from an annotation file in __getitem__ and uses Image.open(file_path), I sometimes (not for all files) get Errno2 No such file or directory even though the file exists and I can see the image using display in a terminal also I copy the exact same line of code into the debug console (VSCode) and it works perfectly.

**Comment by SalmaG98** [comment]
It returns True.

The file exists since I can do "display file_name" from terminal and see the image, also the line of code doesn't fail from the debug console as I said. The 'Image.open()' line in my dataloader's __getitem__ actually fails randomly (this time it failed for the 840th index) which means 840 images before that were processed normally.

Here is a screen shot with the described behavior:

![Screenshot from 2022-08-26 15-46-13](https://user-images.githubusercontent.com/53817405/186923539-50ef0085-58b4-40ba-b0a3-393051b90afe.png)

**Comment by SalmaG98** [comment]
Sorry I am not working on Ubuntu, I edited my first comment. I am having this issue on a remote server running CentOS Linux 7 (Core).

**Comment by radarhere** [comment]
Oh, you're not actually calling `Image.open` with a file path. You're calling `Image.open` with a file handle. `open(os.path.join(self.images_path, self.image_list[image_id]['file_name']), 'rb')` would be the part of the code that is failing, meaning that this problem doesn't relate to Pillow.

**Comment by SalmaG98** [comment]
No actually the code fails with and without the file handle, even when I use Image.open(file_path) it fails exactly the same way, the screen shot is from when I was trying this suggestion on stack overflow https://stackoverflow.com/a/11895901

So I still think it might be a pillow problem.

**Comment by radarhere** [comment]
If you just try `open(os.path.join(self.images_path, self.image_list[image_id]['file_name']), 'rb')`, does it fail at that line?

**Comment by SalmaG98** [comment]
I didn't try that but as I told you I tried both Image.open(file_path) and Image.open(open(file_path, 'rb')) in the debug console when the code breaks on the error and both work and I see the image. Also I tried putting the line of code in a try except statement and the exception is hit once but the second time I'm able to open the picture however sometimes it fails twice and when I try the third time from the debug console it works. This is a very weird error. I have only one small doubt that would be caused by the file system on which the dataset is stored on the servers but I'm not sure, I'll check this on Monday and let you know in the mean time I feel like this is a pillow error.

**Comment by SalmaG98** [comment]
Hello, 

So from my side I don't know yet if it is a problem from the servers or pillow, do you have any suggestions on how to solve the problem?

**Comment by radarhere** [comment]
I very much expect it not to be a Pillow problem, and that if you try `open(os.path.join(self.images_path, self.image_list[image_id]['file_name']), 'rb')`, you will still get the same `FileNotFound` error.

As for suggestions, there isn't much information here, and without being at your machine, this is difficult to debug. You can see the full path, even though here you've blacked part of it out. Does the full path contains a tilde, or any other strange characters? If you run `os.path.exists(...)` using the printed path in the environment that your code runs, does that return `True`?

**Comment by SalmaG98** [comment]
Sorry, I think we misunderstood each other about what I pointed out here, everything from ```os.path.exists(...)``` to ```display $manually_copied_path_in_error_message``` in a terminal to copying the same failing line of code in debug console perfectly works like I mentioned in my previous comments and the attached screenshot. I masked the paths because of sensitive information that I am not authorized to disclose, but the file I provide is absolute so it starts with a ```/``` and it does not contain a tilde. 

I am sorry about the lack of information but since this is not my personal project nor my personal computer or servers, I cannot disclose much. I will try to get in touch with the IT team and let you know if they think that it is a problem from the file system, if it's not the case then I think it is a Pillow problem. Thank you very much for your help.

**Comment by radarhere** [comment]
You're saying that `os.path.exists` work in the debug console, but you've also said that your original code doesn't show an error in the debug console either. Does `os.path.exists` return true if you add it to your code, run in the same way as the original code is run?

Another idea - Is the file located on a network drive, or on the same machine as the code being run?

**Comment by SalmaG98** [comment]
Yes it does return true. Regarding your second point, yes the dataset is on a different server from the one the code is running on.

**Comment by SalmaG98** [comment]
Hello, 

So I checked with our IT team and it seems to be an issue with the network file system we are using and it has been solved, I've ran the experiment again and the pillow error did not show.

Thank you for your help and sorry for the confusion !
