### ISSUE TITLE
Pixel Font Anti-Aliasing Issue - missing pixels

### ISSUE THREAD

**Issue by edent** [python-pillow/Pillow#6421]
### What did you do?

Using the [GNU Unifont](https://unifoundry.com/unifont/index.html) - a "pixel style" font - pixels are missing when `fontmode = '1'`.

But, without `fontmode = '1'` extra, unwanted, pixels are drawn.

### What did you expect to happen?

Characters to be rendered correctly.

### What actually happened?

With `fontmode = '1'`, pixels are missing from the character `X`, but `DEVANAGARI LETTER CANDRA O` is rendered correctly.

![test no aa large](https://user-images.githubusercontent.com/837136/177589402-c63014d0-7e5f-47b9-9e53-98fce82397d6.png)

Without `fontmode = '1'`, the character `X` is correct but `DEVANAGARI LETTER CANDRA O` is drawn with sub-pixels which aren't necessary.

![test aa large](https://user-images.githubusercontent.com/837136/177589437-dfa5a410-7730-4039-86c2-5b79f13c984a.png)

Minimum Viable Example using [`unifont-14.0.04.ttf`](https://unifoundry.com/pub/unifont/unifont-14.0.04/font-builds/unifont-14.0.04.ttf):

```python
from PIL import Image, ImageDraw, ImageFont

text = "X ऑ"

font = ImageFont.truetype("unifont-14.0.04.ttf", size=16)

image1 = Image.new("RGB", (32, 16), "white")
draw1  = ImageDraw.Draw(image1)
draw1.text( (0 , 0), text, font=font, fill="black")
image1.save("test aa.png")

image2 = Image.new("RGB", (32, 16), "white")
draw2  = ImageDraw.Draw(image2)
draw2.fontmode = '1'
draw2.text( (0 , 0), text, font=font, fill="black")
image2.save("test no aa.png")
```

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.10.4
* Pillow: 9.2.0

How the glyphs are drawn in FontForge:
<img src="https://user-images.githubusercontent.com/837136/177590660-09291459-7321-44b2-954e-3903238e6dc5.png" width="200" /><img src="https://user-images.githubusercontent.com/837136/177590664-4a4704a6-999f-4a32-93fe-ebc6c627e792.png" width="200" />

**Comment by radarhere** [comment]
Hi. Pillow uses FreeType to render fonts. I think this is a question for FreeType, over at https://gitlab.freedesktop.org/freetype/freetype, rather than for Pillow.

Are you interested in creating an issue there instead? I think you're in a better position than I am to discuss why pixels should or should not be present.

<details>
<summary>Expand to see what I would say in such an issue, to outline that the behaviour doesn't come from Pillow itself.</summary>
Hi. Over at https://github.com/python-pillow/Pillow, we've received a <a href="https://github.com/python-pillow/Pillow/issues/6421">question about rendered pixel values.</a>

The user has generated the following two images, the first with FT_LOAD_TARGET_MONO and the second without.

![177589437-dfa5a410-7730-4039-86c2-5b79f13c984a](https://user-images.githubusercontent.com/3112309/178139088-1c6fc6c8-075d-4636-98e6-54a4068cab21.png)
![177589402-c63014d0-7e5f-47b9-9e53-98fce82397d6](https://user-images.githubusercontent.com/3112309/178139091-e6127dab-27fb-4de2-bf80-1a3f3bb6f39e.png)

I think this is a FreeType question rather than a Pillow one. Here is the minimal example that I've put together to show the different pixel values being output. The font being used is https://unifoundry.com/pub/unifont/unifont-14.0.04/font-builds/unifont-14.0.04.ttf.

```
FT_Face face = NULL;
FT_New_Face(library, "unifont-14.0.04.ttf", 0, &face);
FT_Set_Pixel_Sizes(face, 0, 16);

FT_Load_Glyph(face, 91, FT_LOAD_DEFAULT | FT_LOAD_RENDER);
FT_Bitmap glyph_bitmap = face->glyph->bitmap;
unsigned char *glyph_source = (unsigned char *)glyph_bitmap.buffer;
printf("X without TARGET_MONO %u\n", glyph_source[glyph_bitmap.width]);

FT_Load_Glyph(face, FT_Get_Char_Index(face, 91), FT_LOAD_DEFAULT | FT_LOAD_RENDER | FT_LOAD_TARGET_MONO);
glyph_bitmap = face->glyph->bitmap;
glyph_source = (unsigned char *)glyph_bitmap.buffer;
printf("X with TARGET_MONO %u\n", glyph_source[glyph_bitmap.width]);

FT_Load_Glyph(face, FT_Get_Char_Index(face, 2324), FT_LOAD_DEFAULT | FT_LOAD_RENDER);
glyph_bitmap = face->glyph->bitmap;
glyph_source = (unsigned char *)glyph_bitmap.buffer;
printf("CANDRA O without TARGET_MONO %u\n", glyph_source[glyph_bitmap.width * 7]);

FT_Load_Glyph(face, FT_Get_Char_Index(face, 2324), FT_LOAD_DEFAULT | FT_LOAD_RENDER | FT_LOAD_TARGET_MONO);
glyph_bitmap = face->glyph->bitmap;
glyph_source = (unsigned char *)glyph_bitmap.buffer;
printf("CANDRA O with TARGET_MONO %u\n", glyph_source[glyph_bitmap.width * 7]);
```

This generates the following, showing an individual pixel changes value for each character with and without FT_LOAD_TARGET_MONO.
```
X without TARGET_MONO 255
X with TARGET_MONO 0
CANDRA O without TARGET_MONO 127
CANDRA O with TARGET_MONO 0
```

Do you have any thoughts on why the pixels are appearing and disappearing? Feel free to tell me that there is something that my code is missing.
</details>

**Comment by edent** [comment]
I've raised it as https://gitlab.freedesktop.org/freetype/freetype/-/issues/1171

**Comment by radarhere** [comment]
Thanks. Unfortunately, it turns out that is the wrong place for the question.

Are you happy to raise the question with their mailing list instead?

**Comment by edent** [comment]
I think I've exhausted the limits of my abilities. I'm very happy if you want to raise it there.

**Comment by radarhere** [comment]
More information has been posted on the FreeType issue, stating that this is the correct behaviour of the font for the X character.

Apologies that it turns out to have been the wrong place for the question. I've had better luck in the past - https://gitlab.freedesktop.org/freetype/freetype/-/issues/1036 and https://gitlab.freedesktop.org/freetype/freetype/-/issues/1047

They've also suggested the talking to the [maintainer of the font](https://lists.gnu.org/archive/html/info-gnu/2022-03/msg00002.html), https://savannah.gnu.org/users/unifoundry

**Comment by radarhere** [comment]
I sent a message to unifoundry 3 days ago, but have received no response so far.

I tried e-mailing freetype-user@nongnu.org [as suggested](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1171#note_1464757), but received a response of "Address not found".

Looking at https://freetype.org/contact.html, I sent an e-mail to freetype@nongnu.org instead.

**Comment by radarhere** [comment]
Here is the response I got back from the mailing list

> It's not clear what I could add to the comment I gave in [FreeType issue #1171](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1171).  Rendering with hinting & mono is simply broken with this font.  Perhaps you can do mono rendering without hinting as a work-around.

@edent are you happy for this to be closed, as it is not a Pillow issue?

**Comment by radarhere** [comment]
unifoundry responded to me.

> Does the same behavior exist with the OpenType version of Unifont?  I am hoping over the next year to phase out distributing the TrueType version in preference to the OpenType version.

Testing with unifont-15.0.01.otf, I find that the original Python code in this issue produces a consistent result, with or without `fontmode = '1'`!

<img width="480" alt="Screen Shot 2022-10-03 at 11 23 57 am" src="https://user-images.githubusercontent.com/3112309/193483172-336591a5-2c26-40e9-8025-f7cf4f359581.png">
