### ISSUE TITLE
When I convert TIFF to PDF, the PDF size is 10 times that of TIFF

### ISSUE THREAD

**Issue by 344672699** [python-pillow/Pillow#6453]
When I convert TIFF to PDF, the PDF size is 10 times that of TIFF
Why is that?

**Comment by 344672699** [comment]
当我将TIFF转换为PDF时，PDF大小是TIFF的10倍
为什么会这样
#tiff path path='XXX';
image = Image.open(path)
image.save(path, , save_all=True)

**Comment by 344672699** [comment]
image = Image.open('tif\\20220720170924738.TIF')
	image.save('tif\\dst\\20220720170924738.pdf', save_all=True)

source :  20220720170924738.TIF  8.51kb
to Pdf  :  20220720170924738.pdf  180kb

files:  https://github.com/344672699/Pillow/blob/main/20220720170924738.rar

**Comment by 344672699** [comment]
python:  3.8
pillow  :  9.1.1

**Comment by radarhere** [comment]
The compression used in your TIFF image is "group4".

https://en.wikipedia.org/wiki/Group_4_compression
> It is only used for bitonal (black-and-white) images.

When the PDF is saved by Pillow, the "DCTDecode" filter is used.

https://www.gemboxsoftware.com/pdf/docs/GemBox.Pdf.Filters.PdfDCTDecodeFilter.html
> The DCTDecode filter decodes grayscale or color image data that has been encoded in the JPEG baseline format.

For comparison, I tried converting your 9kb TIFF to PDF using ImageMagick. It came out as 12kb, rather than Pillow's 185kb. Looking at that PDF, it used the "CCITTFaxDecode" filter. This looks to also be [using group4 compression](https://shreevatsa.github.io/site/ccitt.html), so that is why it is so similar to your original image size.

Because "group4" compression is dedicated for only black and white images, it doesn't seem surprising that it is smaller. I mentioned that DCTDecode is for JPEG images, and Pillow is converting your image to a JPEG before saving it in the PDF file. If I convert your TIFF image to JPEG images using ImageMagick, they come out as a 63kb and a 113kb image. 63kb + 113kb = 176kb, close to the size of the final PDF.

So the answer to your question is that Pillow is not using the compression method dedicated to black-and-white images, but one that allows for more colours.

**Comment by 344672699** [comment]
感谢你的帮助。讲解的非常详细。谢谢。
不过，我还有个疑问，当我使用pillow时，我可以自定义设置use the "CCITTFaxDecode" filter吗？或者有其他设置方式，使我的PDF减小到像ImageMagick一样的“12kb”吗，或者像ITEXT转换后的PDF一样小也可以。
如果不能，是否意味着，我不能使用pillow了，或者只能接收它转换后的10倍以上大小的PDF？


Thank you for your help. The explanations were very detailed. thank you.

However, I still have a question. When I use pillow, can I customize the "ccittfaxdecode" filter? Or is there any other setting method to reduce my PDF to "12KB" like ImageMagick, or as small as the PDF converted by iText.

If not, does it mean that I can't use pillow, or only receive PDF of more than 10 times its converted size?

**Comment by radarhere** [comment]
At the moment, that option doesn't exist in Pillow, no.

If you would like, this issue can be left open as a request for someone to add the feature.

**Comment by radarhere** [comment]
Alternatively, you may be interested in [img2pdf](https://github.com/josch/img2pdf). The following generates a 10kb file.

```python
import img2pdf

with open("out.pdf", "wb") as f:
    f.write(img2pdf.convert('20220720170924738.tif'))
```

**Comment by radarhere** [comment]
I've created PR #6470 to resolve this.
