### ISSUE TITLE
pyinstaller problems

### ISSUE THREAD

**Issue by pyuysig** [python-pillow/Pillow#6566]
I have two projects here, A and B. B is a program that uses Pillow, and A is a program that calls B through the command line. If you simply start A with a py file to execute B, there will be no error, but when I package it with pyinstaller, there will be problems.

This is my error message:

```
  File "api.py", line 14, in <module>
    from PIL import (
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "PIL/Image.py", line 100, in <module>
ImportError: cannot import name '_imaging' from 'PIL' (/tmp/_MEIx6n0Wt/PIL/__init__.pyc)
```

At first, I thought that there were some errors in the packaging of program B, but it is strange that when I execute program B alone, the program can run normally. Only when A executes program B from the command line, there will be errors such as reporting.

In order to solve this problem, I tried to replace the lower version (8. X) and the version that fits my current Python Version (9.2.0). I even added hiddenimports=['PIL._tkinter_finder'] to the pyinstaller spec file, but these operations did not solve my problem. It is really strange. Can I do anything else?

My environment:
```
Python：        3.9.12
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
```

**Comment by radarhere** [comment]
Hi. I don't suppose you could create a self-contained minimal example? A zip of all of the files necessary to trigger the error?

Otherwise,
1. How does A call B exactly? You said 'through the command line', but what is the exact command?
2. Related to that, at the beginning of B, could you add `import sys;print(sys.executable)`. I would like to know where the Python instance is that is run when it works, and where it is when it doesn't work.
3. Are you sure this isn't a question for https://github.com/pyinstaller/pyinstaller instead?
4. Your copy of PIL is inside /tmp? That seems strange to me.
