### ISSUE TITLE
Trim around transparent pixels around the GIF

### ISSUE THREAD

**Issue by FranckFrost** [python-pillow/Pillow#6600]
### What did you do?
I made a code that would take a gif and trim out the excess of transparent background out of each frame. Sample gif:
![a](https://user-images.githubusercontent.com/101209171/191065265-eb156aba-8e51-4c83-aa4e-bba093335c7d.gif)

### What did you expect to happen?
I expected to replicate the "trim around transparent pixels around the image" crop option of https://ezgif.com/crop :
![ezgif-1-f9e920af95](https://user-images.githubusercontent.com/101209171/191065369-ec9feb8d-f8ae-4abb-8cf8-7aaeb705cb9f.gif)

### What actually happened?
The first frame is trimmed properly but every other frame is cut for some reason.
![b](https://user-images.githubusercontent.com/101209171/191065479-fd2f956f-e83b-44ce-8d8e-c54947a1b3d1.gif)

I tried a few different things but I'm completely stuck. Any help is welcomed.

### What are your OS, Python and Pillow versions?

* OS:  W10
* Python: 3.9.12
* Pillow: 9.1.0

```python
im = Image.open(image)
crops = []

for frame in ImageSequence.Iterator(im):
	crop = frame.crop(frame.getbbox())
	crops.append(crop)
    
crops[0].save("result.gif", format="GIF", append_images=crops[1:],
              save_all=True, duration=1000/60, disposal=2, optimize=False, loop=0)
```

**Comment by radarhere** [comment]
I think the problem is that you are saving frames of different sizes - `getbbox()` returns an area of smaller width when the man is closer to standing position.

But I don't think you want to crop the transparent areas around each individual frame - the man would slide around a bit if so - but instead around all of the frames combined - so my first comment will not be relevant in the end.

Try the following code.
```python
im = Image.open(image)

bbox = None
for frame in ImageSequence.Iterator(im):
    frame_bbox = frame.getbbox()
    if bbox is None:
        bbox = frame_bbox
    else:
        bbox = (
            min(bbox[0], frame_bbox[0]),
            min(bbox[1], frame_bbox[1]),
            max(bbox[2], frame_bbox[2]),
            max(bbox[3], frame_bbox[3])
        )

crops = ImageSequence.all_frames(im, lambda frame: frame.crop(bbox))
crops[0].save("result.gif", format="GIF", append_images=crops[1:],
              save_all=True, duration=1000/60, disposal=2, optimize=False, loop=0)
```
![result](https://user-images.githubusercontent.com/3112309/191136638-202c4f57-bf16-4ba6-ab0b-0ffdd43d7173.gif)
