### ISSUE TITLE
Make `import PIL; PIL.Image` work

### ISSUE THREAD

**Issue by Kodiologist** [python-pillow/Pillow#6614]
With Pillow 9.2.0 and (e.g.) matplotlib 3.5.2:

```console
$ python3 -c 'import PIL; PIL.Image'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'Image'
$ python3 -c 'import matplotlib, PIL; PIL.Image'
# No error.
```

[This behavior is quite strange.](https://stackoverflow.com/a/69125762)

**Comment by hugovk** [comment]
Alternatively, maybe we should only allow the recommended `from PIL import Image`?

https://pillow.readthedocs.io/en/stable/installation.html#warnings

**Comment by Kodiologist** [comment]
Or `import PIL.Image`, or just `import Pillow` to eliminate confusion with https://pypi.org/project/PIL once and for all.

**Comment by aclark4life** [comment]
I don't find this issue that strange, but yes, I guess I would deprecate ``import PIL.Image`` because ... I don't think I've ever typed that in 10+ years of Pillowing. So, if it helps eliminate some confusion, 👍 

Also [we have been given control of PIL on PyPI](https://pypi.org/project/PIL/), but we've not done anything with it. Enabling ``import Pillow`` is probably not an improvement... unless we print a message "You should probably use ``from PIL import Image``."

So,

```
>>> import PIL.Image
Please import Image from PIL.

>>> import PIL
Please import Image from PIL.

>>> import Pillow
Please import Image from PIL.

```

Something like that.

**Comment by radarhere** [comment]
Just to point it out - since the [removal of `PILLOW_VERSION`](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#pillow-version-constant), which I think was the most backwards incompatible change that we've made, [some people are still working around that](https://github.com/python-pillow/Pillow/issues/4130#issuecomment-1201516416) or [downgrading](https://github.com/python-pillow/Pillow/issues/4130#issuecomment-1065461241) (although I don't know why). Even with a deprecation period, if we [break the present version of matplotlib](https://github.com/matplotlib/matplotlib/blob/363713442bdada82b5ce554be6e1da4c4db84184/lib/matplotlib/backends/backend_wx.py#L1106), [torchvision again](https://github.com/pytorch/vision/blob/7046e56fe4370e94339b3e8b6fd011e285294a3a/torchvision/prototype/transforms/functional/_geometry.py#L5), and [presumably other libraries](https://grep.app/search?q=PIL.Image), I expect there will be similar issues, and presumably another issue created like #6537.

I'm not opposed to removing `PIL.Image` for the sake of clarity, I just want to be able to tell users that we did consider what would happen, and this was the choice that was made anyway.

**Comment by Kodiologist** [comment]
I feel you. I maintain [Hy](https://github.com/hylang/hy), which isn't even 1.0 yet, and with every breaking change, however well-motivated, comes the wailing and gnashing of teeth.

**Comment by aclark4life** [comment]
@radarhere I believe the most breaking change ever happened in Pillow 1.0 when ``import Image`` stopped working 😄 

Anyway, again, I don't feel particularly inclined to add support to Pillow such that ``import PIL`` allows access to ``PIL.Image`` because ... wait for it ... ``Image`` is a module, not a package (directory containing other modules).

Correct me if I'm wrong, but to make ``PIL.Image`` available to reference via ``import PIL`` and without ``import PIL.Image`` we'd have to ``mkdir PIL/Image; mv PIL/Image.py PIL/Image/__init__.py`` ?

If so, I definitely don't see that happening. And if not, I'm not sure I see it happening without adding some workaround that would arguably be more confusing than just doing nothing. 🤷

**Comment by radarhere** [comment]
After experimenting, I'm not convinced that it's possible to tell from within Pillow if `import PIL.Image` or `from PIL import Image` was used, without either using traceback, which I expect would be imperfect and negatively impact speed, or restructuring Pillow (at least [by renaming Image.py to _Image.py, filling Image.py with `print("Please import Image from PIL."); from ._Image import *`, adding `from . import _Image as Image` to `__init__.py`](https://github.com/radarhere/Pillow/commit/25e1233714f7f448bd2c0f26d3960a13c0474f5a)), which seems like overkill.

If I'm wrong, feel free to enlighten me.

**Comment by aclark4life** [comment]
OP is asking for ``PIL.Image`` to be in namespace after ``import PIL`` which is not going to happen without:

```
mkdir PIL/Image
mv PIL/Image.py PIL/Image/__init__.py
```

Actually, the above _alone_ doesn't help:

```
➜  Developer  mkdir PIL
➜  Developer  touch PIL/__init__.py
➜  Developer  mkdir PIL/Image
➜  Developer  touch PIL/Image/__init__.py
➜  Developer  python3
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__file__
'/Users/alexclark/Developer/PIL/__init__.py'
>>> PIL.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'Image'
```

However, if ``PIL/Image/__init__.py`` contains ``from . import Image`` then it works:

```
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.Image
<module 'PIL.Image' from '/Users/alexclark/Developer/PIL/Image/__init__.py'>
```

Which means maybe we could support this by adding ``from . import Image`` to ``PIL/__init__.py``:

```
➜  Developer  mkdir PIL
➜  Developer  touch PIL/__init__.py
➜  Developer  touch PIL/Image.py
➜  Developer  vi PIL/__init__.py
➜  Developer  python3              
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.Image
<module 'PIL.Image' from '/Users/alexclark/Developer/PIL/Image.py'>

```

Whether or not we should do this, I don't know. Current PIL ``__init__.py`` looks like this:

```
"""Pillow (Fork of the Python Imaging Library)

Pillow is the friendly PIL fork by Alex Clark and Contributors.
    https://github.com/python-pillow/Pillow/

Pillow is forked from PIL 1.1.7.

PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
Copyright (c) 1999 by Secret Labs AB.

Use PIL.__version__ for this Pillow version.

;-)
"""

from . import _version

# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 9.0.0.
# Use __version__ instead.
__version__ = _version.__version__
del _version


_plugins = [
    "BlpImagePlugin",
    "BmpImagePlugin",
    "BufrStubImagePlugin",
    "CurImagePlugin",
    "DcxImagePlugin",
    "DdsImagePlugin",
    "EpsImagePlugin",
    "FitsImagePlugin",
    "FitsStubImagePlugin",
    "FliImagePlugin",
    "FpxImagePlugin",
    "FtexImagePlugin",
    "GbrImagePlugin",
    "GifImagePlugin",
    "GribStubImagePlugin",
    "Hdf5StubImagePlugin",
    "IcnsImagePlugin",
    "IcoImagePlugin",
    "ImImagePlugin",
    "ImtImagePlugin",
    "IptcImagePlugin",
    "JpegImagePlugin",
    "Jpeg2KImagePlugin",
    "McIdasImagePlugin",
    "MicImagePlugin",
    "MpegImagePlugin",
    "MpoImagePlugin",
    "MspImagePlugin",
    "PalmImagePlugin",
    "PcdImagePlugin",
    "PcxImagePlugin",
    "PdfImagePlugin",
    "PixarImagePlugin",
    "PngImagePlugin",
    "PpmImagePlugin",
    "PsdImagePlugin",
    "SgiImagePlugin",
    "SpiderImagePlugin",
    "SunImagePlugin",
    "TgaImagePlugin",
    "TiffImagePlugin",
    "WebPImagePlugin",
    "WmfImagePlugin",
    "XbmImagePlugin",
    "XpmImagePlugin",
    "XVThumbImagePlugin",
]


class UnidentifiedImageError(OSError):
    """
    Raised in :py:meth:`PIL.Image.open` if an image cannot be opened and identified.
    """

    pass
```

So I would say if adding ``from . import Image`` to ``PIL/__init__.py`` doesn't break any tests or cause any obvious harm, then maybe we do add it. But not in this upcoming release. 😄

**Comment by tacaswell** [comment]
That `import PIL.Image` works is due to how Python's import mechanics work.  I do not understand why you would go through the effort to break it.

If you want to avoid users having to import the sub-module isn't adding `from . import Image` in `__init__.py` (as suggested in https://github.com/python-pillow/Pillow/issues/6614#issuecomment-1270497974) the simplest path? IF you don't want to always pay that import cost, then maybe look at something like https://github.com/scikit-image/scikit-image/pull/5101 to get lazy imports?

**Comment by aclark4life** [comment]
> That `import PIL.Image` works is due to how Python's import mechanics work. I do not understand why you would go through the effort to break it.

Can you please clarify what "go through the effort to break it" means in this case? For example in 2.1.0 we broke ``import _imaging`` for a [specific reason](https://pillow.readthedocs.io/en/latest/deprecations.html#import-imaging). I'm not sure if we went out of our way here to break anything here… yet.

**Comment by tacaswell** [comment]
>  guess I would deprecate import PIL.Image because ... I don't think I've ever typed that in 10+ years of Pillowing. So, if it helps eliminate some confusion, 👍

Which I read as "eventually break `import PIL.Image`"

At the end of the day you have:

```
PIL/
   __init__.py
   Image.py
   ...
   bunch.py
   of.other
   files.py
```

To make `import PIL.Image` _not_ work you are going to have to do something funny which will break down stream users and (in my view) be orders of magnitude _more_ confusing.  Libraries should be consistent with how Python actually works, not an incorrect mental model of confused users....

----


```diff
diff --git a/src/PIL/__init__.py b/src/PIL/__init__.py
index 63a45769b..85b26f25c 100644
--- a/src/PIL/__init__.py
+++ b/src/PIL/__init__.py
@@ -84,3 +84,9 @@ class UnidentifiedImageError(OSError):
     """

     pass
+
+
+try:
+    from . import Image  # noqa, must be last because it uses _plugins
+except ImportError:
+    ...
```

is enough to make the OP's request work.  It has to be at the end (and ignore the QA for "imports at the top" because of `_plugins` and in the try-except is because in setup.py this file gets exec'd before `PIL._imaging` has been built so ignore the import error (which should probably be fixed by not execing as part of the build process)).   I agree with @radarhere that if you do this for `Image` you may get this for what ever other modules so I would either do nothing (other than maybe writing it as `from PIL import Image` in your docs as a convention) or going all-in on lazy import of everything.

**Comment by radarhere** [comment]
So, the code from the original post is about an interaction between matplotlib and Pillow. A matplotlib maintainer has weighed in on this and said that the behaviour is fine. So perhaps we aren't concerned about the way our two libraries relate.

Setting that aside then, my thoughts are
1. Should 'PIL.Image' be deprecated?
Let's not go out of our way to break functionality, since we value backwards compatibility. My hope would be that anyone who is confused about this will visit our documentation and discover that we exclusively refer to `from PIL import Image`.
2. Should 'PIL.Image' be actively supported?
I don't think changing the import structure of our library is minor, and in the absence of a solid reason, I don't think we need to. If `import PIL; PIL.Image` is unreliable, that's ok, as it is not recommended behaviour.

I'm inclined to close this.

**Comment by aclark4life** [comment]
Close-away, however I don't recall why ``import PIL.Image`` works when matplotlib is imported first? And yeah, we shouldn't go out of our way to break ``import PIL.Image`` because it happens to work in some scenario somewhere for some reason. We'd only do it if we felt like we had reason to do it within Pillow for Pillow's sake or for some much more major compatibility issue.

**Comment by radarhere** [comment]
> why import PIL.Image works when matplotlib is imported first?

It's not that `import PIL.Image` works differently, it's that `PIL.Image` works after importing `matplotlib`. It would be because [matplotlib internally runs `import PIL.Image`](https://github.com/matplotlib/matplotlib/pull/27940), so
```python
import matplotlib, PIL; PIL.Image
```
is really
```python
import PIL.Image, PIL; PIL.Image
```

**Comment by nulano** [comment]
```
>>> from PIL import Image
>>> import PIL
>>> PIL.Image
<module 'PIL.Image' from 'C:\\Users\\Nulano\\AppData\\Roaming\\Python\\Python311\\site-packages\\PIL\\Image.py'>
```
