### ISSUE TITLE
GIF export PIL 9.2.0 palette bug

### ISSUE THREAD

**Issue by keesh0** [python-pillow/Pillow#6675]
Hello,
The following code correctly generates a GIF image with a custom color table under Pillow 9.0.1.
However, under Pillow 9.2.0 my first few entries for red,  green, and blue are ignored.
Windows 11, Jupyter notebook, Python 3.8.13 
![image](https://user-images.githubusercontent.com/13039271/197310595-72808c7c-fc5b-44b3-bfef-166f654d6dc4.png)

```python
import numpy as np
import PIL
from PIL import Image
import ctypes
PIL.__version__  # need 9.0.1, if we use 9.2.0 then the palette is **wrong!!!** 

pixels = np.zeros(shape=(256, 512), dtype=np.ubyte)  # rows x cols
for row in range(256):
    for col in range(512):
        if row < 24:
            pixels[row][col] = 1
        if row > 240:
            pixels[row][col] = 3
        if row > 100 and row < 125:
             pixels[row][col] = 2

colorMap = [0, 0, 0]   # PIL palettes must be an integer list or bytearray
for i in range(1, 256):
     colorMap.extend([i, i, i])
colorMap[3:6] = [255, 0, 0]
colorMap[6:9] = [0, 255, 0]
colorMap[9:12] = [0, 0, 255]
print(colorMap)

pilImage = Image.fromarray(pixels, mode="P")
comment = "test color GIF"
pilImage.save("D:\\data\\test.gif", include_color_table=True, palette=colorMap,
              interlace=False,  optimize=False, disposal=1, comment=comment)
```

**Comment by radarhere** [comment]
Testing, I find that this is due to #6283. That PR meant that `Image.fromarray(pixels, mode="P")` now has a populated palette, rather than an empty one. The palette that you are providing in `palette=colorMap` is being written as the global palette in the GIF, but the local palette is still coming from the image.

Possible solutions to your problem.
1) Stop the image from having a palette. Change `Image.fromarray(pixels, mode="P")` to `Image.fromarray(pixels, mode="L")`.
2) Stop instructing GifImagePlugin to include the local palette. Remove `include_color_table=True`.

**Comment by radarhere** [comment]
If neither of those solutions is satisfactory, then allow me to ask this question - why have you included `include_color_table=True`? The documentation states that this is ["Whether or not to include local color table"](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving). I presume you don't want to increase the file size for no reason by including a global palette and a local palette that are the same.

**Comment by keesh0** [comment]
Thanks.
The following works fine under both PIL 9.0.1 and 9.2.0.,
pilImage = Image.fromarray(pixels, mode="L")

Original motivation was to port legacy C++ code line by line (it used gif_lib.h).
Keep the exact same funtionality for regression testing.
Also, there is a black box downstream system which may require a palette as opposed to direct RGB values.
