### ISSUE TITLE
"P" mode image converted to bytes and then read using frombytes returns a black image

### ISSUE THREAD

**Issue by rushabh-wadkar** [python-pillow/Pillow#6788]
### What did you do?
I have an image which is opened using `PIL.Image.open(f)`. Now this returns PIL image in "P" mode. However, when I try getting the original image back using fromBytes & toBytes, it returns a black image.

### What did you expect to happen?
It should return the original image.

### What actually happened?
It returned a black image.

### What are your OS, Python and Pillow versions?

* OS: Mac OS
* Python: 3.8
* Pillow: 9.1.0

```python
import PIL.Image
path = "./assets/test.png"

img = PIL.Image.open(path)
pil_image = PIL.Image.frombytes(data=img.tobytes(), size=img.size, mode=img.mode)
pil_image
```

![BlackImage](https://user-images.githubusercontent.com/6323685/206373187-ddc8443a-8a43-4c7e-bedb-17964ef75c83.png)

**Comment by radarhere** [comment]
The idea of P mode is that there is a palette of up to 256 colors, and each pixel in the image is one of those colors. `tobytes()` is only writing out the indexes of the image pixels, and not the palette. So the image becomes black because when it converts those indexes back to an image, there is no palette to tell it what color each pixel is.

For a simpler example, here is Pillow code that creates a 1x1 red P mode image.

```python
from PIL import Image
im = Image.new("P", (1, 1))
im.putpalette((255, 0, 0))
im.save("out.png")
```
When you run `tobytes()` over this,
```python
print(im.tobytes())
```
you get `b'\x00'`. Zero. There is no way to know that this is supposed to be red. This isn't a bug. It's just not something you should attempt to do with a P mode image.

There are various alternatives.
- You could save the palette separately, and then apply it to the new image at the end.
- You could convert the image from P to RGB, or RGBA.
- You could save the image in a particular image format (PNG for example), and then load the image back from that.

If any of those alternatives sound suitable, and you would like further assistance, I can provide an example.

**Comment by rushabh-wadkar** [comment]
@radarhere Thanks for the quick response but this should happen for all "P" mode images right ? I think it doesn't. Why does this particular image have this black effect then ?

**Comment by radarhere** [comment]
I think it would happen for all P mode images. If you have an image that demonstrates otherwise, please post it.

**Comment by rushabh-wadkar** [comment]
I have three questions - 

1. When we open image using PIL.Image.open(bytes.read( )) -> Does it default to "P" mode ?
2. How to change the by-default opening mode to RGB ?
3. Does image contains the mode in built or PIL enforces it ? `RGB/RGBA/L/P` etc

**Comment by radarhere** [comment]
1. I don't really know what `bytes` is in this question, but if it is the result of `img.tobytes()`, you shouldn't try passing it to `Image.open`. `Image.open` is for opening image file data. As I mentioned, `img.tobytes()` is just writing out the values of individual pixels. That is part of an image, but is not a complete image. It doesn't contain information about the mode or size of that image data.
2. Regarding `Image.open`, there isn't a way to change the mode that the image is opened as (unless you're talking about GIFs). It is opened as whatever mode the image is. If you would like to change the mode of an image afterwards, you can use [`convert()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert).
3. Pillow will open different images in different modes, depending on what the image is.

**Comment by radarhere** [comment]
@rushabh-wadkar did that answer your questions?
