### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#6796]
This image: [countsportsman.zip](https://github.com/python-pillow/Pillow/files/10199885/countsportsman.zip)

Example:
````python
import PIL.Image
with PIL.Image.open('countsportsman.webp') as img:
    frames = []
    durations = []
    for frame in PIL.ImageSequence.Iterator(img):
        img.copy()    # crucial to get duration
        duration = img.info.get( 'duration' )
        assert type(duration) is int
        durations.append( duration )
        frames.append( frame )
    assert len(frames) == len(durations)
    frames[0].save( 'result.webp', format='WebP', save_all=True, append_images=frames[1:], duration=durations, loop=0 )
````

**Comment by radarhere** [comment]
Hi. The problem is that `frame` is not just the image from that particular frame. It is the overall image seeked to that frame. So Pillow sees a list of 63 images, each of which have multiple frames, and tries to save many more than 63 frames.

You could fix this by copying the frame before appending it to the list

```python
frames.append( frame.copy() )
```
or you could use `ImageSequence.all_frames` instead.

```python
for frame in PIL.ImageSequence.all_frames(img):
```

**Comment by doublex** [comment]
@radarhere 
Sorry for the inconvenience
