### ISSUE TITLE
Loading truncated images causes high CPU usage

### ISSUE THREAD

**Issue by eci-aashish** [python-pillow/Pillow#6812]
### What did you do?
Getting "image file is truncated (0 bytes not processed)" error, so after research applied below setting - 
```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

### What did you expect to happen?
I expected that the error will be resolved without any spike in CPU utilization.

### What actually happened?
It did but suddenly CPU usage spiked high. All CPUs were utilizing high memory at the same time, so I removed the LOAD_TRUNCATED_IMAGES then CPU Utilization gets low.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu
* Python: 3.8.10
* Pillow: 8.4.0

```python
img = img.rotate(90, expand=True)
```
The above code reproducing the error.

At above line, I am getting the error and tried above solution then facing high CPU utilization issue.

**Comment by radarhere** [comment]
Are you connected to the user from #6781 in some way? Your issues are similar.

Could you attach a copy of the image?

**Comment by eci-aashish** [comment]
Hello @radarhere 

Somehow we both are connected as we both are facing the same issue.

I don't have the image as our multiple live customers are facing the issue.

Please guide me on this.

**Comment by radarhere** [comment]
Here is one of test images that is truncated.

![truncated_image](https://user-images.githubusercontent.com/3112309/208648051-addad3b9-23b2-469c-9f2f-9118bc383ab0.png)

In your environment, does this code with that image cause a problem?
```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open("truncated_image.png").load()
```

If it does, then the problem is related to your environment in some way. How are you running Python? You say "All CPUs". What is it that you're doing that means that Python isn't just running in a single thread?

If it doesn't, then the problem is related to your images. It is hard to help without having a copy of the image, because we can't figure out why your images are special, and why they're not truncated images that don't cause problems like the one I posted.

> I don't have the image as our multiple live customers are facing the issue.

Are you saying that you can't even replicate the problem? Even if we fixed this, you wouldn't know if it worked?
