### ISSUE TITLE
Use `y*` instead of `y#`

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6975]
#6974 changed https://github.com/python-pillow/Pillow/blob/dbcd7372e554ee420a156b968eb9a609ec66ffd1/src/decode.c#L124 to use `y*` instead of `y#` so that it can accept a `memoryview` object, and notes that `y*` is actually the recommended way to accept binary data. `y#` is used in a few other locations; should these be changed as well?

https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/display.c#L201
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/display.c#L721
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/encode.c#L567
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/encode.c#L1060
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imaging.c#L1644
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imaging.c#L1709
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imaging.c#L2220
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imaging.c#L2544
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imagingcms.c#L124
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imagingft.c#L142
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imagingft.c#L1099
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_imagingft.c#L1145
https://github.com/python-pillow/Pillow/blob/7d8a08b2211abdfc5766e01c0444d3ae81843439/src/_webp.c#L599

**Comment by radarhere** [comment]
I've created PR #6988 for `_frombytes`.

For some of methods, the data is read first. So there isn't a basic situation where the data passed to the C layer will be a `memoryview`.
- `PyImaging_DrawWmf` is only called internally from `Image.core.drawwmf` in https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/PIL/WmfImagePlugin.py#L53
- `cms_profile_fromstring` is only called internally from https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/PIL/ImageCms.py#L187-L191.
- `getfont` is only called internally from https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/PIL/ImageFont.py#L236-L255

For `WebPEncode_wrapper`, it is called from `_webp.WebPEncode` in https://github.com/python-pillow/Pillow/blob/1457d2c14667d9901d7bc2552beed4a1ab81742b/src/PIL/WebPImagePlugin.py#L340-L341
and `im.tobytes()` won't create a `memoryview`.

The other two instances were `PyImaging_JpegEncoderNew` and `PyImaging_ZipEncoderNew`. When I attempted to save a Pillow image to a `memoryview`, I got `AttributeError: 'memoryview' object has no attribute 'write'`, so that isn't appropriate for that scenario.
