### ISSUE TITLE
Unhelpful error message when image is truncated

### ISSUE THREAD

**Issue by gutjuri** [python-pillow/Pillow#7039]
Hello,
A framework I'm using is using Pillow to load a large amount of JPGs into memory. However, some of these images are erroneous, which leads to an error message `OSError: image file is truncated (20 bytes not processed)`, caused by:

https://github.com/python-pillow/Pillow/blob/6df3ad6f2da118062c39fd0a8a5aee06c7d5e63e/src/PIL/ImageFile.py#L261-L266

I'd be great if the raised error's message would include the filename of the file that caused the error, as this would allow me to exclude the file from further processing.
This doesn't seem like a large code change.
I'd be grateful for any response.

Best regards
Juri

**Comment by Yay295** [comment]
Is `image.filename` set for your images?

**Comment by radarhere** [comment]
#566 added the filename to the error message for unidentified images in `Image.open`.

https://github.com/python-pillow/Pillow/blob/bdcc6333b697f82ae12139385f2c02f8e4d8b0fd/src/PIL/Image.py#L3289-L3290

"image file is truncated" is not directly within `image.open`. The user might open an image, and then later load it. So I'm not seeing why "image file is truncated" is special compared to all the other errors that we might raise when loading an image. What you're asking for is not a large change, but if we were to implement it consistently so that every error message included the filename, that is.

I'm not convinced this isn't a request better made to the framework that you are using.

**Comment by radarhere** [comment]
What is the framework that you are using?

**Comment by gutjuri** [comment]
> Is `image.filename` set for your images?

I don't know this, as the framework I'm using hides this from me.

> What is the framework that you are using?

This one: https://github.com/ultralytics/ultralytics 

In particular, I'm using this method with a a list of filenames as argument `source`: https://github.com/ultralytics/ultralytics/blob/ec10002a4ade5a43abb9d5765f77eefddf98904b/ultralytics/yolo/engine/model.py#L198

> I'm not convinced this isn't a request better made to the framework that you are using.

Okay thanks, I'll open an issue there then.

**Comment by radarhere** [comment]
Cool. Be aware too that if you would like to try and workaround the error, you can
```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```
first.
