### ISSUE TITLE
Documentation of `Image` specifies attributes only available to some child classes

### ISSUE THREAD

**Issue by aeisenbarth** [python-pillow/Pillow#7119]
Documentation of the [`Image`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.n_frames) class says it has the attributes `filename`, `is_animated`, `n_frames`, however these are not implemented in the parent class and thus not generally available. Only some child classes implement these, but not for example `JpegImagePlugin`, `WmfImagePlugin`…

This is the cause of https://github.com/imageio/imageio/issues/958.

Either these attributes should be removed from the documentation of the `Image` class or the implementation of the `Image` class should specify these attributes (e.g. as interface with `return NotImplemented`) and require all subclasses to implement it.

**Comment by hugovk** [comment]
Thanks for the report.

The docs for all of these do in fact say they're not available for all image plugins.

`Image.filename` says:

> Only images created with the factory function `open` have a filename attribute.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.filename

`Image.is_animated` says:

> This attribute is only defined by image plugins that support animated images. Plugins may leave this attribute undefined if they don’t support loading animated images, even if the given format supports animated images.
>
> Given that this attribute is not present for all images use `getattr(image, "is_animated", False)` to check if Pillow is aware of multiple frames in an image regardless of its format.

https://docs.python.org/3/library/functions.html#bool

And `Image.n_frames` says:

> This attribute is only defined by image plugins that support animated images. Plugins may leave this attribute undefined if they don’t support loading animated images, even if the given format supports animated images.
>
> Given that this attribute is not present for all images use `getattr(image, "n_frames", 1)` to check the number of frames that Pillow is aware of in an image regardless of its format.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.n_frames

I'm curious how your test case fails by using Pillow documentation as input. Perhaps the test can be modified to be more lenient, or only test for these attributes for the relevant plugins.

**Comment by hugovk** [comment]
> > I'm curious how your test case fails by using Pillow documentation as input. Perhaps the test can be modified to be more lenient, or only test for these attributes for the relevant plugins.
> 
> I'm not sure I understand this. I am just a user who wants imageio to work. I don't believe pillow documentation is used as input to a test case, but it served as input to the developer whoever implemented the imageio pillow plugin. Sorry that I also oversaw that the optional attribute presence is well documented, down in the description text. Apparently, the first sight is very misleading.

Ah, no problem. I misread the first post that documentation needs changing to fix the problem, and was on mobile and didn't check the linked issue.

Anyway, in this case I think the thing to do is for imageio to check if the relevant attributes exist before accessing them. We're careful about backwards compatible, I'd be wary about adding these for all images types in case someone is relying on the absence for detection of certain image types.

That would allow imageio to support all Pillow versions back to their [minumum 8.3.2](https://github.com/imageio/imageio/blob/b4fc9713ab28e935425f2d38e8432e22971ec561/setup.py#L177) (from 2021) and not require 10.0.0+ which would be our next version, which will also drop support for Python 3.7.

**Comment by radarhere** [comment]
> I am just a user who wants imageio to work.

I've created https://github.com/imageio/imageio/pull/984 to fix imageio.

**Comment by radarhere** [comment]
https://github.com/imageio/imageio/pull/984 has now been merged, fixing https://github.com/imageio/imageio/issues/958

**Comment by radarhere** [comment]
@FirefoxMetzger you originally started using Pillow's `n_frames` in imageio in https://github.com/imageio/imageio/pull/739

Did you have any thoughts on this?

**Comment by FirefoxMetzger** [comment]
Regarding https://github.com/imageio/imageio/issues/958, I think this was a bug in ImageIO. Your fix, @radarhere, is now merged (thanks again for your contribution 🚀), released, and part of ImageIO v2.28.1 so updating to that version should fix @aeisenbarth 's problem.

---

As to whether or not the Image base class should have defaults for `n_frames`, `is_animated`, and `filename` so that they exist on all plugins, I think it would be polite but isn't a must-have. 

`n_frames` and friends have the same name and behavior across all implementing children and (from what I understand) it is somewhat expected that a plugin/child representing an animated image sets `is_animated = True`. From a systems perspective, this sounds like the attributes belong to Image's API not to each individual child's API, and making this "official" by defining them on the parent seems natural.

There also seem to exist sensible defaults for plugins/children that don't wish to have custom logic choose these attribute values. I would have expected something like `filename=None`, `is_animated=False`, `n_frames=1`. The latter two are an obvious choice here given the docs already suggest using `getattr(...)` with this default value, and if I have to rely on `filename` while supporting Images that may or may not come from disk `filename is None` would be my uncontested choice of default.

At the same time, I hear @hugovk 's concern about backward compatibility, though I must admit that I don't expect this to be too big a concern. If I want to know about a _specific_ image type I'd check `image.format in expected_formats` or `isinstance(image, expected_plugins)` which are intended to do this, and we should steer users towards these. For categories of image times, e.g., animated/not animated, I would want to rely on `is_animated` and friends. However, not all formats/plugins define them, so I have to `getattr(image, ...)` and choose my own default. Backward compatibility then really boils down to whether or not users would choose a default other than the one recommended in the docs and, if so, why.

So in sum, having these attributes on the parent/base class would (I think) lead to nicer UX and thus be "polite". At the same time, pillow has been very functional with them only being defined on the parent so it isn't a _must-have_, especially if you are very concerned about how it may affect users downstream. I doubt that it will have a big negative impact, but this is pure speculation unless one of you knows a way to get data on how many people test against these attributes using a default other than the ones from the docs or discussed here.

**Comment by radarhere** [comment]
In the absence of a functional benefit, I'm happy to decline the idea of adding `n_frames`, `is_animated`, and certainly `filename` to all images, for the sake of backwards compatibility.

@aeisenbarth's alternate request was for a subclass for image formats that potentially have multiple frames, so that these attributes could be move to that subclass' page in the docs.

I don't mind this in theory - at the very least, we could move `filename` from the `Image` documentation to the `ImageFile` documentation without any code changes.

But this issue is about trying to clarify things for people who have missed something in the documentation. In practice, I think burying possible `Image` attributes further down in the docs isn't going to help. Instead of users asking why `n_frames` is missing from an object in their code, we might have users asking why `n_frames` isn't showing up in the `Image` docs.
