### ISSUE TITLE
Images not showing on specific computers in tkinter

### ISSUE THREAD

**Issue by sderinger** [python-pillow/Pillow#7130]
### What did you do?
I created a program that reads the photos out of a folder, creates a slideshow of those photos, and then displays the images in a GUI with arrows that allow the user to switch through the photos.

### What did you expect to happen?
I expected the program to successfully display the image slideshow.

### What actually happened?
When I ran the program, it displayed the arrows on the screen that can be used to change the image, and I didn't get any error messages. However, no images were displayed and my screen was black. My computer is a Mac. When I tried running the program on someone else's computer, it worked successfully. Their computer is also a Mac, but it has a different OS. I have included example photos in a folder in my program, which can be accessed through the GitHub link below. 

### What are your OS, Python and Pillow versions?

* OS: Ventura 13.3.1 (other computer: Big Sur 11.5.1)
* Python: Pycharm 2022.2.3 (other computer: 2022.2.4)
* Pillow: 9.5.0 (other computer: 9.5.0)

https://github.com/sderinger/slideshow

**Comment by radarhere** [comment]
When I try your code on Ventura without Pycharm (I don't personally use Pycharm), I find that it works.

a) Are you able to try running your code without Pycharm? Just `python3 main.py`?

b) I wonder if your problem is similar to #7055. If you run
```python
import tkinter as tk
from PIL import Image, ImageTk

root = tk.Tk()
root.geometry('400x400')

path = '/Users/sashaderinger/Desktop/slideshow_project/photos/jellybean.jpg' 
image = Image.open(path)
image = image.resize((400, 400)) 
photo = ImageTk.PhotoImage(image)

img_label = tk.Label(root, image=photo)
img_label.pack()

root.mainloop()
```
does that display a single image correctly? It does for me. If nothing else, this is a simpler example than your current code.

If it does not, then does
```python
import tkinter as tk

root = tk.Tk()
root.geometry('400x400')

img_label = tk.Label(root, text="hello")
img_label.pack()

root.mainloop()
```
display "hello"? If it does not, then like that other issue, your problem is with tkinter, not Pillow.
