### ISSUE TITLE
The module name is incorrect

### ISSUE THREAD

**Issue by ezequielsobrino** [python-pillow/Pillow#7153]
I ran a python file, got a message that the PIL module did not exist, tried to install PIL but it didn't exist and had to Google to discover the name 'Pillow'.

log console

```
(venv) E:\repos\promptflow>python run.py
Traceback (most recent call last):
  File "E:\repos\promptflow\run.py", line 1, in <module>
    from promptflow.__main__ import main
  File "E:\repos\promptflow\promptflow\__main__.py", line 3, in <module>
    from promptflow.src.app import App
  File "E:\repos\promptflow\promptflow\src\app.py", line 14, in <module>
    from PIL import Image, ImageTk
ModuleNotFoundError: No module named 'PIL'

(venv) E:\repos\promptflow>pip3 install PIL
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

(venv) E:\repos\promptflow>pip install PIL
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

(venv) E:\repos\promptflow>pip install Pillow
Collecting Pillow
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
Installing collected packages: Pillow
Successfully installed Pillow-9.5.0
```

**Comment by radarhere** [comment]
Hi. Pillow is actually a fork of PIL. You can see them as two distinct packages on PyPI - https://pypi.org/project/PIL/ and https://pypi.org/project/Pillow/ - and Pillow is maintained by a different group of people to those that created PIL.

You can learn more at https://pillow.readthedocs.io/en/stable/about.html and https://pillow.readthedocs.io/en/stable/porting.html. PIL doesn't support Python 3, so that would be why you were unable to install it.

If you just think that `pip install PIL` should work, we already have an issue open for discussion of that - #1535

**Comment by radarhere** [comment]
@ezequielsobrino did that answer your question?
