### ISSUE TITLE
Error when loading images

### ISSUE THREAD

**Issue by robotechnics** [python-pillow/Pillow#7183]
I cannot write custom metadata on a TIFF image. The following error message appears when using PIL 9.5.0 and Python 3.10:
```
File XXXXXXXXlib\site-packages\PIL\ImageFile.py:162 in load
    pixel = Image.Image.load(self)

  File XXXXXX\lib\site-packages\PIL\Image.py:79 in __getattr__
    raise AttributeError(msg)

AttributeError: module '__main__' has no attribute 'load'
```

This is the code snippet that causes the problem:
```python
img_path = 'trial.tif'
image = Image.open(img_path)
image.tag[37510] = 'dummy message'
image.save(img_path, tiffinfo=image.tag)
```

**Comment by radarhere** [comment]
Hi. First of all, I don't think your problem is related to custom TIFF metadata or to saving. If you just try and load an image,
```python
from PIL import Image
im = Image.open("trial.tif")
im.load()
```
I expect you to get the same error. I expect that you would fail to perform most tasks with Pillow on your machine?

Instead, I think there is something strange about your Pillow installation. How did you install Pillow? Could you try uninstalling it and re-installing it?

What is the filename of your script when you run it?

**Comment by robotechnics** [comment]
You are right. I have problems even loading the image. My file is untitle0.py so it does not clash with Image.
I have a custom mamba installation  (equivalent to anaconda). I will uninstall and reinstall again and come back to you in a few days. Thanks for the quick reply

**Comment by robotechnics** [comment]
Confirmed. It was a problem with spyder and not with the pillow library. It was solved by resetting the spyder session. Sorry for the inconvenience I may have caused and thanks for the quick response and support !!!!.
