### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by Rahul-AkaVector** [python-pillow/Pillow#7364]
### What did you do?

I was trying to run detection Function of EasyOCR in my python.

### What did you expect to happen?

i was expecting to make proper detections 

### What actually happened?

Showing error: 
![Screenshot 2023-09-02 120610](https://github.com/python-pillow/Pillow/assets/90543113/47b5938f-9a7e-4d8d-9f32-79f1d4020bf0)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### What are your OS, Python and Pillow versions?

* OS: Windows 11
* Python: Latest 3.11
* Pillow: version 10.0.0

```python
import easyocr
from tensorflow.keras.preprocessing.image import load_img
![Screenshot 2023-09-02 120610](https://github.com/python-pillow/Pillow/assets/90543113/551f6d22-34e0-44c5-938e-c6892b0b640c)

reader = easyocr.Reader(['en'], gpu=False)


img  = np.array(load_img(test))
roi = img[int(ymin):int(ymax),int(xmin):int(xmax)]

roi = img[int(ymin):int(ymax),int(xmin):int(xmax)]

from PIL import Image
rgb_image = Image.fromarray(roi, 'RGB')
rgb_image.save('rgb_image.png')
rgb_image.show()

detections = reader.readtext(roi)

```

**Comment by radarhere** [comment]
Hi. `Image.ANTIALIAS` was [removed in Pillow 10](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants). Instead, you can use `Image.LANCZOS` or `Image.Resampling.LANCZOS`.

This is not all that easy for you to workaround though, since it is EasyOCR's code that is out of date, not yours.

The change has already been made in the master branch of EasyOCR - https://github.com/JaidedAI/EasyOCR/pull/1050 - it's just that they haven't released a new version yet.

If you want, you could install a copy of EasyOCR from their master - https://github.com/JaidedAI/EasyOCR

Alternatively, you could downgrade Pillow to a version earlier than 10.0.0.

**Comment by Rahul-AkaVector** [comment]
Oh i c ...

This worked for me :) 

Just Changed Pillow version from 10.0.0 to 9.5.0 

Thanks mate :)

```python
!pip install Pillow==9.5.0
```
