### ISSUE TITLE
`ImageOps.exif_transpose()` only keeps one frame

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#7474]
I created a test image with ImageMagick and Exiftool:
```cmd
convert -size 64x128 -delay 100 canvas:#FFFF00 canvas:#0000FF xmp_rotated.apng
exiftool -overwrite_original -n -Orientation=6 xmp_rotated.apng
```
Then applied the XMP Orientation and saved the new image:
```python
from PIL import Image, ImageOps
x = Image.open('xmp_rotated.apng')
y = ImageOps.exif_transpose(x)
y.save('y.apng',exif=y.getexif(),save_all=True)
```
The resulting image is rotated correctly, but only has one frame.

I also noticed that `x.n_frames` is 66 when it should be 2.

**Comment by radarhere** [comment]
This not behaviour specific to `ImageOps.exif_transpose()`. It is the pattern established for methods that alter images. Consider `resize()`, `rotate()` or `transform()`. They all work on just the current image.

```python
from PIL import Image, ImageOps, ImageTransform
x = Image.open('xmp_rotated.apng')
print(getattr(x, "n_frames", None))

y = x.rotate(90)
print(getattr(y, "n_frames", None))

y = x.resize((1, 1))
print(getattr(y, "n_frames", None))

transform = ImageTransform.ExtentTransform((0, 0, 0, 0))
y = x.transform((100, 100), transform)
print(getattr(y, "n_frames", None))
```
gives
```
66
None
None
None
```

If you like to perform a transformation to all frames in an image, we have [`ImageSequence.all_frames()`](https://pillow.readthedocs.io/en/stable/reference/ImageSequence.html#PIL.ImageSequence.all_frames).

```python
from PIL import Image, ImageOps, ImageSequence
x = Image.open('xmp_rotated.apng')
print(len(ImageSequence.all_frames(x, ImageOps.exif_transpose)))
```

**Comment by radarhere** [comment]
Regarding `x.n_frames`, exiftool agrees with Pillow that it is 66.
```
$ exiftool xmp_rotated.apng | grep "Animation Frames"
Animation Frames                : 66
```

**Comment by Yay295** [comment]
Is there any way to recombine the transformed frames back into one image without saving it to a file and reopening it?

I tried using the `in_place` parameter:
```python
for frame in ImageSequence.Iterator(x):
    ImageOps.exif_transpose(frame,in_place=True)
```
but got:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File ".../ImageOps.py", line 620, in exif_transpose
    image.load()
  File ".../ImageFile.py", line 241, in load
    decoder.setimage(self.im, extents)
ValueError: tile cannot extend outside image
```

**Comment by radarhere** [comment]
I think `ValueError: tile cannot extend outside image` is happening because the image is trying to load the next frame into the transposed size that it no longer fits inside.

As for generally recombining frames into an image without saving, no, that isn't possible with Pillow's API. As a slight alternative to saving to file, I will say that you don't have to save it to disk, but can instead save it to a `BytesIO()` instance.

As a note for others who might read this in the future - there shouidn't be a strict need to combine frames into an image instance. You should just be able to perform operations on an the array of images and then use [`append_images`](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#pdf-saving) to combine them when outputting your result.

**Comment by Yay295** [comment]
Okay, thanks. I got around the error like this:
```python
orig_size = x.size
for frame in ImageSequence.Iterator(x):
    ImageOps.exif_transpose(frame,in_place=True)
    frame._size = orig_size
```
But that doesn't actually work. After the first frame is transposed, the Orientation tag is removed, so the rest of the frames aren't transposed.

`ImageSequence.all_frames(x,ImageOps.exif_transpose))` copies each frame twice, so I think `[ImageOps.exif_transpose(frame) for frame in ImageSequence.Iterator(x)]` is probably the best way to do this.
