### ISSUE TITLE
May I ask if Pillow 9.3.0 (windows) involves the CVE-2023-45853 vulnerability in zlib?

### ISSUE THREAD

**Issue by hwzjy01** [python-pillow/Pillow#7518]
windows 10
pillow 9.3.0
zlib 1.2.13

https://nvd.nist.gov/vuln/detail/CVE-2023-45853
![image](https://github.com/python-pillow/Pillow/assets/121840033/70916e66-503f-4e8f-ad14-edbc332a0692)
I don’t know if minizip related modules are involved.

**Comment by radarhere** [comment]
Hi. Given that "[MiniZip is not a supported part of the zlib product](https://nvd.nist.gov/vuln/detail/CVE-2023-45853)", and when compiling for Windows, Pillow merely runs "[`win32\Makefile.msc", "zlib.lib`](https://github.com/python-pillow/Pillow/blob/14c539e7873b816cdb4f0f7aeeeed50a094197cf/winbuild/build_prepare.py#L144)", I'm going to say no. It would seem that separate steps are required to involve minizip, which Pillow doesn't take. https://github.com/madler/zlib/issues/868#issuecomment-1783525536 states that "This is not a zlib vulnerability."

As an aside, if you are concerned about security, I would recommend upgrading from Pillow 9.3.0. We have fixed various security problems since then.
- https://pillow.readthedocs.io/en/stable/releasenotes/9.4.0.html#security
- https://pillow.readthedocs.io/en/stable/releasenotes/9.5.0.html#security
- https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#security
- https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html#security

**Comment by hwzjy01** [comment]
Thank you for your reply, I understand

**Comment by hwzjy01** [comment]
Thank you for your reply. After investigation, this vulnerability is not involved.
