### ISSUE TITLE
Missing frames in saved GIF

### ISSUE THREAD

**Issue by BastienCagna** [python-pillow/Pillow#7613]
### What did you do?
Generate a new GIF from a list of Image (n copies of the same image)

### What did you expect to happen?
Getting several frame with the same image.

### What actually happened?
Only one frame.

### What are your OS, Python and Pillow versions?

* OS: Linux, Mint
* Python: 3.10.6
* Pillow: 10.1.0

When executing the followings line, img2 contains only 1 frame instead of 8 (if I've well understood the docs):
```python
frames = []
img = Image.open(".local/some_image.png")
for f in range(8):
  frames.append(img.copy())
frames[0].save(".local/text_fade.gif", format="GIF", append_images=frames[1:], save_all=True)


img2 = Image.open(".local/text_fade.gif")
```

**Comment by radarhere** [comment]
This is actually a feature - the identical frames are combined in order to reduce the file size.

If you try again with 8 differing frames, you should find 8 are saved.

**Comment by BastienCagna** [comment]
ok. Then, is there a way to get the same images for more than one frame ?
In my case, I want to do this for example:
<------ 500ms ----------><------------- 1,5s ---------------------><------ 500ms --------------><------------- 1,5s ------------------>
|*** static image ** | ** fade to the new image ** |** new static image **|** fade to the next image**| ....

**Comment by radarhere** [comment]
I don't think you need to have the same image occurring multiple times in a row, because there is no visual difference.

I think the solution to your problem is the "duration" argument - this is the ability to set how long a single frame appears for. See https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif-saving for that, and other possible arguments you can use when saving.

It won't have any effect on your original code with identical images, but for the second scenario you're describing, you can do something along the lines of `staticImage.save("out.gif", save_all=True, append_images=[fadeImage1, fadeImage2, newStaticImage, fadeImage3, fadeImage4], duration=[500, 750, 750, 500, 750, 750])`

**Comment by BastienCagna** [comment]
Ah Yes! 
I tried yesterday but I was using time in seconds instead of ms. Now it works!
Thanks a lot for your support !
Have a good day :)
Bastien
