### ISSUE TITLE
UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by katia-katkat** [python-pillow/Pillow#7763]
Hello everyone, 
I am facing an UnidentifiedImage Error when trying to run the following code : 

![image](https://github.com/python-pillow/Pillow/assets/83125186/0c390a6c-7b6c-41c4-af04-0f6d06bf4b7e)

How can I solve this issue please!!

**Comment by radarhere** [comment]
Could you attach a copy of COCO_train2014_000000121235.jpg?

**Comment by katia-katkat** [comment]
yes here's a link to it : https://drive.google.com/file/d/19t9lZzmH_3k_DSS20UPaad_Dx7WTnje1/view?usp=sharing

**Comment by radarhere** [comment]
I'm able to run the following code without a problem.
```python
from PIL import Image
im = Image.open('COCO_train2014_000000581884.jpg')
im.load()
```
If you can't, then what version of Pillow are you using? Have you tried upgrading to the latest version?

You can find out what version you are using by inserting `print(Image.__version__)` into your code.

**Comment by katia-katkat** [comment]
I am using version 9.5.0

**Comment by radarhere** [comment]
When you run `!pip install --user --upgrade pillow`, does the output of that command say that Pillow 10.2.0 is installed, but `print(Image.__version__)` still reports 9.5.0? If that is the case, then `pip` is attached to a different copy of Python than what you are using to run your script. If you add
```python
import sys
print(sys.executable)
```
to your script, then you should get a path to your copy of Python, probably `/opt/conda/lib/python3.10`. If you then run `/opt/conda/bin/python3.10 -m pip` instead of just `pip`, your commands should work.

**Comment by katia-katkat** [comment]
Running /opt/conda/bin/python3.10 -m pip as you suggested worked for me
Thanks a lot for your time and assistance !!

**Comment by radarhere** [comment]
Cool. My guess is that you originally installed Pillow through conda, which installed https://github.com/conda-forge/pillow-feedstock, and then upgrading through pip installed normal Pillow.
