### ISSUE TITLE
Unable to create images for non Latin languages correctly

### ISSUE THREAD

**Issue by asif-ca** [python-pillow/Pillow#7803]
Unable to create images for non-Latin languages correctly.
For example, I want to create images for Bengali or Gujarati languages by drawing text on them.

Here is what's happening, take Bengali or Hindi as example:

It creates image for Bengali language, however the issue is **_text rendered on the image is incorrect as the sequence of characters sometimes changes_** in images, I tried different fonts but almost each font had issue with those specific characters.

**Examples:**
 থেকে বঞ্চিত
![000347671](https://github.com/oh-my-ocr/text_renderer/assets/86609190/68184af1-5674-4fd6-b553-c10ce060bdff)

--------------
![image](https://github.com/oh-my-ocr/text_renderer/assets/86609190/e44e904b-70c1-4195-9506-8573b75deffb)
![image](https://github.com/oh-my-ocr/text_renderer/assets/86609190/bd1b846f-4633-45e3-a4e2-dfb2a52fc09d)
-------

Look text rendered on the image is incorrect and same happens with Hindi langues etc.

> Code chunk is:

 ```python
 ....
 total_width = sum(font.getsize(word)[0] for word in selected_words) + (len(selected_words) - 1) * font.getsize(" ")[0]
max_height = max(font.getsize(word)[1] for word in selected_words)

# Create a transparent image for drawing text

text_image = Image.new("RGBA", (total_width, max_height), (255, 255, 255, 0))
draw = ImageDraw.Draw(text_image)

# Draw text on the transparent image
current_x = 0
for word in selected_words:
    draw.text((current_x, 0), word, fill=(0, 0, 0, 255), font=font)
    current_x += font.getsize(word)[0] + font.getsize(" ")[0]  # Add space between words

# Apply blur effect 
text_image = text_image.filter(ImageFilter.GaussianBlur(radius=blur_radius))  # Adjust the blur radius here

# Paste the text image onto the background
position = ((background.width - text_image.width) // 2, (background.height - text_image.height) // 2)
background.paste(text_image, position, text_image)

...
```

@radarhere , @hugovk @hasahmed @aclark4life @hugovk @jezdez @twpayne @masklinn @Yay295 or anyone please can you have look at it?

**Comment by asif-ca** [comment]
I orignally faced issue in the script of **text_renderer** and posted [here]( https://github.com/oh-my-ocr/text_renderer/issues/69)

Then i wrote custom script using pillow to draw text on images but issue repeated there as well.

**Comment by radarhere** [comment]
Hi. What version of Pillow are you using?

Could you provide a code example where the code is a short, simple script that can be run by itself, draws specific text with a specific font, and could you attach images showing what you expected and what happened?

At the moment, I don't know what font you're using, and the code you've posted doesn't show how you're loading that font.

**Comment by asif-ca** [comment]
@radarhere i am using **_Pillow version  9.5.0_**

Oh my bad, sorry [here is the full code script](https://gist.github.com/asif-ca/bb12103d36a4179eafdf2a7e41c17e55) I am using to create images for OCR Model training.

> For example, take this image as an example:

![image](https://github.com/oh-my-ocr/text_renderer/assets/86609190/e44e904b-70c1-4195-9506-8573b75deffb)

The **tail** is the expected result and the **head of the arrow is what is being created**. (Notice change of character sequence) 

Corpus files I am using are [guj_news_2020_10K-sentences.txt](https://github.com/python-pillow/Pillow/files/14310477/guj_news_2020_10K-sentences.txt)
and [ben_news_2020_10K-sentences.txt](https://github.com/python-pillow/Pillow/files/14310546/ben_news_2020_10K-sentences.txt)

And [font ](https://fonts.google.com/noto/specimen/Noto+Sans+Bengali?preview.text=%E0%A6%A5%E0%A7%87%E0%A6%95%E0%A7%87%20%E0%A6%AC%E0%A6%9E%E0%A7%8D%E0%A6%9A%E0%A6%BF%E0%A6%A4)I am using

**Comment by radarhere** [comment]
You've attached two 10,000 line files as input, and neither of them is mentioned in the code that you posted.

Could you please simplify your example as much as possible, so that we're talking about just one piece of text, without any randomness?

**Comment by asif-ca** [comment]
OK here is a few lines corpus file (just create few images and see the result)the goal is that the image text should be the same as the text picked from the file.

![image](https://github.com/python-pillow/Pillow/assets/86609190/ca00655d-5033-41dc-a40a-d40a778f5c77)


[ben_news_2020_10K-sentences.txt](https://github.com/python-pillow/Pillow/files/14310789/ben_news_2020_10K-sentences.txt)

Actually, I was experimenting with different non-latin languages.

**Now I have updated the gist according to the files uploaded here.**

----------
You can use this as **bg_colored** images 
![851x315-alizarin-crimson-solid-color-background](https://github.com/python-pillow/Pillow/assets/86609190/c9fa6155-5c8e-4162-b74f-4ca6d22e8067)
![851x315-aero-blue-solid-color-background](https://github.com/python-pillow/Pillow/assets/86609190/1486d1f7-474d-4906-abcc-ce6d9a5ac98b)
-----------

**Comment by radarhere** [comment]
Ok, running the following code on my machine

```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("NotoSansBengali-VariableFont_wdth,wght.ttf", 28)
image = Image.new("RGBA", (550, 50), (0, 0, 0, 0))
draw = ImageDraw.Draw(image)
with open("ben_news_2020_10K-sentences.txt", "r", encoding="utf-8") as fp:
    draw.text((0, 0), fp.read(), font=font, fill="#000")
image.save("out.png")
```
I get

![out](https://github.com/python-pillow/Pillow/assets/3112309/33f9fc24-89e9-49c6-91d6-05db08c5b3d5)

I imagine when you run this code, you are getting this instead?

![out2](https://github.com/python-pillow/Pillow/assets/3112309/bfa7f1a3-48cc-4759-a6ac-e800383f2509)

If so, then the problem is that you do not have raqm working.

https://pillow.readthedocs.io/en/stable/installation.html#external-libraries
> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-link library search order (Microsoft Learn)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps) (fribidi-0.dll or libfribidi-0.dll are also detected). See [Build Options](https://pillow.readthedocs.io/en/stable/installation.html#build-options) to see how to build this version.

**Comment by asif-ca** [comment]
> If so, then the problem is that you do not have raqm working.
> 
> https://pillow.readthedocs.io/en/stable/installation.html#external-libraries

Yes issue is same as you mentioned let me check if I don't have raqm ... do I need to install that library exclusively or it intalls with pillow ? any resource to install that library on windows?

**Comment by twpayne** [comment]
@asif-ca spamming nine people with mentions for help with your personal problem is rude and entitled behavior. I don't know why you mentioned me as my last commit to this project was eleven years ago.

**Comment by nulano** [comment]
> any resource to install that library on windows?

See [my answer on StackOverflow](https://stackoverflow.com/a/77694899).

**Comment by asif-ca** [comment]
Thanks @radarhere for all your time and guidance in putting me in the right direction.

Aafter setting `raqm ` pillow dependency (fribidi actually as suggested by @nulano on StackOverflow, I am able to create the images with the correct layout, the reason behind the incorrect text sequence for non-latin was that missing (fribidi ) dependency for the pillow.

@nulano Thanks your [StackOverflow](https://stackoverflow.com/a/77694899/1648883) answer was really useful.

**Comment by radarhere** [comment]
Did you mean to re-open this, or is this resolved?

**Comment by asif-ca** [comment]
Sorry, the issue has already been resolved. Thank you very much for all your help, @radarhere

**Comment by VikasSanvaliya** [comment]
Okay. as per pillow fork https://pillow.readthedocs.io/en/stable/installation/building-from-source.html building from source. 
Pillow cannot handle non english fonts if they are going for image manupulation.
This is the best way to get things going on win 11 and possibly other win ver.
Assuming python with std lib and pillow are installed.
1 make a folder where you would download the lib.
2 open the folder right click and launch terminal( cmd/powershell)
3 use command 
git clone (url to git lib)
as 20 12 2024 these are
git clone https://github.com/HOST-Oman/libraqm.git
git clone https://github.com/fribidi/fribidi.git
git clone https://github.com/harfbuzz/harfbuzz.git
git clone https://github.com/servo/libfreetype2/tree/master/freetype2
i nulled the c2man depedency for fribidi in the meson setup builddir prompt. something like ddocs=0/false
4 close terminal or cd/folder to go to any folder rather than ramq. Need to install depedencies first.
you would now have 4 foulders for ramq, fribidi, harfbuzz and freetype/freetype2
5 eg go to harfbuzz folder and launch terminal/ use cd to go to the folder
i used powershell so was able to call meson directly. you might need to install that from winstore
you might need to install meson and ninja using this command 
pip install meson ninja
6
run these commands in terminal  in the same order

meson setup builddir
meson compile -C builddir
meson test -C builddir
  *Any error check here or google for its solution/s
meson install -C builddir

this will install the feature
6 do the same for truetype and harfbuzz
7 lastly do the same for ramq

8 get to the top folder where all these were downloaded and search for *.dll
copy (NOT CUT) the dll (about 4/5 dll files) and paste them in the DLLs folder of installed python (something like c://user/mypc/appdata/local/programs/python/python 3**/dlls
9 go to settings /control pannel - system asvanced system settings - enviornment variables - (recommended do this for all users on the pc) go to system variable - double click on path/PATH - in the next window add your top foulder and make sure the python one is there( python adds this when installed)

10 finally run python and use these commands to check if ramq is there

A pip uninstall pillow.
B
 pip install pillow --config-settings="build_ext.enable_raqm=True"
 11. check if raqm fribidi and harfbuzz are installed as features
 run python

use this command 

from PIL import features
 available_features = features.get_supported() 
print("Available features in Pillow:")
 for feature in available_features: 
print(feature)


You should get a list of all features and if alls good pillow would have raqm

alternately this can be done

from PIL import features

print("Raqm:", features.check("raqm"))
print("HarfBuzz:", features.check("harfbuzz"))
print("Fribidi:", features.check("fribidi"))


11 when trying to convert ( well in my case Hindi fonts) non English fonts into image use this argument in your script early on after you import all (pandas as pd os and from pil etc) 

assert features.check("raqm"), "Raqm is not enabled. Ensure Raqm, HarfBuzz, and FriBiDi are correctly installed."

If everything weht well non English fonts should work.
Check them on @ v9ielts on instagram

**Comment by nulano** [comment]
@VikasSanvaliya 
Or you could just read [my StackOverflow answer](https://stackoverflow.com/a/77694899/1648883) that I linked in a previous reply:

> So, to use Raqm on Windows with the precompiled wheels (i.e. after running python.exe -m pip install Pillow), you now need to place fribidi.dll in any of the [searched directories](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps); I usually use the Python install directory, i.e. where python.exe is located, e.g. C:\Program Files\Python312\.

>
> You can download a precompiled fribidi.dll from the [Pillow wheels.yml workflow on GitHub](https://github.com/python-pillow/Pillow/actions/workflows/wheels.yml): select a recent passing build and download and extract the correct fribidi-... artifact for your version of Python, x86/x64/ARM64 (you may have to log in to download artifacts).

And then you don't have to compile anything yourself.
