### ISSUE TITLE
Unable to import module 'endpoint.pdf': cannot import name '_imaging' from 'PIL' (/opt/python/PIL/__init__.py)

### ISSUE THREAD

**Issue by patrick23-commits** [python-pillow/Pillow#8488]
```
Unable to import module 'endpoint.pdf': cannot import name '_imaging' from 'PIL' (/opt/python/PIL/__init__.py)
```

**Comment by hugovk** [comment]
Please follow these guidelines to ensure your issue is handled properly.

If you have a ...

1.  General question: consider asking the question on Stack Overflow
    with the python-imaging-library tag:

    * https://stackoverflow.com/questions/tagged/python-imaging-library

    Do not ask a question in both places.

    If you think you have found a bug or have an unexplained exception
    then file a bug report here.

2.  Bug report: include a self-contained, copy-pastable example that
    generates the issue if possible. Be concise with code posted.
    Guidelines on how to provide a good bug report:

    * https://stackoverflow.com/help/mcve

    Bug reports which follow these guidelines are easier to diagnose,
    and are often handled much more quickly.

3.  Feature request: do a quick search of existing issues
    to make sure this has not been asked before.

We know asking good questions takes effort, and we appreciate your time.
Thank you.

### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```text
Please paste here the output of running:

python3 -m PIL.report
or
python3 -m PIL --report

Or the output of the following Python code:

from PIL import report
# or
from PIL import features
features.pilinfo(supported_formats=False)
```



```python
code goes here
```
