### ISSUE TITLE
What function is called in Resample.c when resizing an image with NEAREST?

### ISSUE THREAD

**Issue by aidevmin** [python-pillow/Pillow#8590]
I want to reimplement pillow resizing method NEAREST and Bilinear in pure C++. I see the file Resample.c, but I don't know exactly what function is corresponds NEAREST and bilinear? Could you point me?
Thank you.

**Comment by aidevmin** [comment]
@radarhere 
Thank you so much for detailed ìnormation.
Do you have any plan to release Pillow C++ library like OpenCV? Actually, Pillow is written by C++ but I only see documentation for Python.
As you know, many Deep learning framework use Pillow as library for image processing.

**Comment by radarhere** [comment]
Pillow is a Python library. As discussed in #4532, we don't currently have a commitment to direct use of our C code.

https://github.com/python-pillow/Pillow/issues/4532#issuecomment-618255798
> Pillow makes a commitment to stable public interfaces, which are defined at the Python layer. The C interfaces are explicitly internal, and no effort is made to keep them stable even between minor releases, and no support or warning is given when they change. (IIRC, there are/were people using the internal interfaces, but they've always been explicitly on their own with that)

**Comment by radarhere** [comment]
@aidevmin has that answered your questions?

**Comment by aidevmin** [comment]
@radarhere 
Thank you so much. I understood the situation.
Moreover I want to know exact algorithm of Nearest resizing method with formulas that is implemented in Pillow. Could you point me a documentation so that I can follow it?

**Comment by radarhere** [comment]
As far as documentation, I can only offer https://pillow.readthedocs.io/en/stable/handbook/concepts.html#filters

> **Resampling.NEAREST**
> Pick one nearest pixel from the input image. Ignore all other input pixels.

I'm not quite sure what kind of answer you're hoping for. You say you would like to run this operation in C, and I've linked you to where the C code is in Pillow. I can appreciate that the code might seem complex, but I would have imagined that explaining how it works in detail is only helpful if you wish to do something different?

Furthermore, the `resize()` operation can have parameters apart from `resample`, and images can have different modes. If you have a specific and simple code example, and have a specific question about the output, then I can put together an answer.

**Comment by aidevmin** [comment]
@radarhere 
Sorry for your confusing.
Actually I reference the repo https://github.com/zurutech/pillow-resize, it uses OpenCV to handle image. I also could rewrite by pure C based on that.

Because there are some different implementation of Nearest (from pillow and some others). I understood the that we get "nearest pixels" but there is some tricks in each implementation. That is reason I want to see exact formulas from pillow to understand correctly (it is more easier than reading code and infer formulas)

I am so sorry again.

**Comment by radarhere** [comment]
I'll try and talk about this example.

```python
from PIL import Image
im = Image.open("Tests/images/hopper.png")
im.resize((64, 64), Image.NEAREST)
```

An affine transformation is used. If the image isn't using one of Pillow's "experimental" modes, then the core logic resides here

https://github.com/python-pillow/Pillow/blob/d66c51a35663247357bf6b625ef093df7ea12a45/src/libImaging/Geometry.c#L883-L919

It maps the pixels to the output image. For each row of the output image, it uses pixels from a single row of the input image. So for our example, because we're halving the image, it uses every second row of the input image.

https://github.com/python-pillow/Pillow/blob/d66c51a35663247357bf6b625ef093df7ea12a45/src/_imaging.c#L1903-L1906

The same thing occurs horizontally. Since we're halving the image, it uses pixels from every second column of the input image. Exactly which column is determined here, by dividing the output image dimension by the input image dimension.

The following code produces the same output.
```python
from PIL import Image
imIn = Image.open("Tests/images/hopper.png")
imOut = Image.new("RGB", (64, 64))
for x in range(64):
    for y in range(64):
        imOut.putpixel((x, y), imIn.getpixel((x * 2 + 1, y * 2 + 1)))
imOut.save("b.png")
```

**Comment by aidevmin** [comment]
@radarhere 
Thank you so much for supporting me.
It is so clear and I understood.

Thank you for your team. Pillow is used widely in popular Deep learning frameworks. 🥰
