### ISSUE TITLE
Building from source on Windows

### ISSUE THREAD

**Issue by Ganeshkumhar1** [python-pillow/Pillow#8603]
trying to build pillow using instructions given here - 
https://github.com/python-pillow/Pillow/blob/main/.appveyor.yml

seems libjpeg-turbo-3.0.3.tar.gz is not present on given location. (ran winbuild\build_prepare.py  )

Fetching https://raw.githubusercontent.com/python-pillow/pillow-depends/main/libjpeg-turbo-3.0.3.tar.gz (attempt 1)...
Fetching https://raw.githubusercontent.com/python-pillow/pillow-depends/main/libjpeg-turbo-3.0.3.tar.gz (attempt 2)...
Fetching https://raw.githubusercontent.com/python-pillow/pillow-depends/main/libjpeg-turbo-3.0.3.tar.gz (attempt 3)...
HTTP Error 404: Not Found

Please check

**Comment by radarhere** [comment]
Hi. I've [restored the file](https://github.com/python-pillow/pillow-depends/commit/08e223570aece1c1fedf619fb7d8ef3a4d2dd7d7), so it should work if you try again.

I gather you're building Pillow 10.4.0 or earlier. Is there any particular reason you're not building the latest version of Pillow?

**Comment by Ganeshkumhar1** [comment]
Thank you @radarhere  for restoring the files. I was able to build it. Yes, I am trying to build 10.4.0. Building this because same version I built on Linux for matplotlib, and want to keep versions same on both platform.

After installation I am seeing this error -

[C:\Temp\4119530650\python\Pillow]python selftest.py --installed
Traceback (most recent call last):
  File "C:\Temp\4119530650\python\Pillow\selftest.py", line 7, in <module>
    from PIL import Image, features
  File "C:\temp\4119530650\python\Lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

**Comment by radarhere** [comment]
Could you uninstall Pillow,
make sure that it is uninstalled by checking that you receive a `ModuleNotFoundError` when you try to import it in Python,
and then try to install it again and copy and paste your full install output here?

**Comment by Ganeshkumhar1** [comment]
I retried all the steps. attaching the logs .
[build.log](https://github.com/user-attachments/files/18148315/build.log)

**Comment by Ganeshkumhar1** [comment]
@radarhere , Please help how can I debug this issue.

**Comment by radarhere** [comment]
I'm not a Windows user, so I'm not as familiar with this as I could be. I've tried searching online, but results involve Conda or MinGW, which it doesn't look like you're using.

I imagine you're deliberately installing from source, and are not interested in the [wheel.](https://files.pythonhosted.org/packages/74/0a/d4ce3c44bca8635bd29a2eab5aa181b654a734a29b263ca8efe013beea98/pillow-10.4.0-cp312-cp312-win_amd64.whl)

I expect we would have received other reports by now if something was broken with normal execution of this script, so I imagine there must be something unusual about your setup. Perhaps @nulano has some insight?

**Comment by Ganeshkumhar1** [comment]
@nulano could you please provide any pointers or suggestions that might help in debugging the issue?

**Comment by radarhere** [comment]
Why are you actually attempting to build from source, rather than installing Pillow normally?

**Comment by nulano** [comment]
> @nulano could you please provide any pointers or suggestions that might help in debugging the issue?

I typically use [ProcessMonitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to figure out which DLL is missing and what paths were used to look for it.

1. Start Python and ProcessMonitor.
2. Set the filters in ProcessMonitor: the Process Name filter to the name of the Python exe and the Operation filter to CreateFile leaving the other filters at the default.
3. Run the failing operation in Python.
4. Stop event capture in ProcessMonitor.
5. Look for anything that looks wrong like a series of NAME_NOT_FOUND errors or a library being loaded from the wrong path.

![image](https://github.com/user-attachments/assets/d28c465f-aa96-4bbb-a41d-97d53c581ec5)

---

However, _imaging should not depend on any additional DLLs if built correctly, so I suspect you have some .lib file leaking in from your system; we can diagnose that if you add `-C debug=true` to your build command, e.g. `python -m pip install -v -C raqm=vendor -C fribidi=vendor -C debug=true .`. IIRC this usually results in a broken build on Windows, but all we need is the build logs to check what libraries are being used.

While it is likely not causing your issue, I should also note that you sometimes need to delete the `Pillow/build` directory to get a clean build of Pillow since not all changes (such as rebuilding the dependencies) are detected automatically.

**Comment by radarhere** [comment]
@Ganeshkumhar1 was that helpful?
