### ISSUE TITLE
Cannot from PIL import ImageGrab

### ISSUE THREAD

**Issue by travellers** [python-pillow/Pillow#901]
Does Pillow2.5.3 ImageGrab still not support other OS except windows?
If not, why we cannot do that?

---

/Library/Python/2.7/site-packages/Pillow-2.5.3-py2.7-macosx-10.9-intel.egg/PIL/**init**.py

Python 2.7.5 (default, Mar  9 2014, 22:15:05)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > from PIL import ImageGrab
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "build/bdist.macosx-10.9-intel/egg/PIL/ImageGrab.py", line 26, in <module>
> > > ImportError: No module named _grabscreen

**Comment by vlaufer** [comment]
#Because it's implemented using the windows api.

In other words an implementation using Quartz is beyond the scope of this project?

**Comment by radarhere** [comment]
I think others were simply commenting on the block of code that is known as ImageGrab, rather than the functionality of it. I've created a PR to add the `grab` method of ImageGrab to OS X, which I'm guessing is what you're after. I didn't need to invoke Quartz - there's a command line utility called `screencapture`.

**Comment by vlaufer** [comment]
right, imagegrab kills python scripts on non-windows machines because its win32api or com, i forget which. you're right a simple implementation based on screencapture will work, but to me the use of image grab has always seemed suboptimal for this reason. quartz seems to me to be a happy medium that enables cross platform functionality without coding solutions for both OS, unless I am missing something.

thank you very much for the response and dialogue.

**Comment by radarhere** [comment]
No problem. The PR has been merged now, so if you download the master branch, it will be there, or you can wait for the release of Pillow 3.0 on October 1.

Perhaps I'm the one missing something. https://en.wikipedia.org/wiki/Quartz_(graphics_layer) is OS X only. What cross platform functionality are you discussing?
